### ISSUE TITLE
What should users who depended on placement="mouse" do?

### ISSUE THREAD

**Issue by lanterndev** [angular-ui/bootstrap#1019]
I just noticed placement="mouse" got nuked in 17163c22, which my project depends on. My use case is described in twbs/bootstrap#7106, and [this comment](https://github.com/twbs/bootstrap/issues/1230#issuecomment-3928077) shows a similar (and probably much more common) case where not having placement="mouse" results in undesired behavior, i.e. when the tooltip is triggered by hovering over text that spans more than one line.

I'd love to be able to keep using the latest version of angular-bootstrap, and could volunteer to maintain the placement="mouse" support if you'd be willing to reconsider it. Would you be interested in discussing this further?

Thanks for your consideration.

/cc @joshdmiller @pkozlowski-opensource

**Comment by badreal** [comment]
+1

**Comment by kwehrle** [comment]
Probably there's a general misunderstanding of this positioning type. For me and probably many use cases (see the other discussions with this topic), the initial mouse position for the tooltip is absolutely ok. It's not necessary, that the tooltip is moving with the mouse. As mentioned above it is more confusing for a user if the tooltip is positioned hundreds of pixels to the left or to the right and in worst case out of the visible region (see slightly modified plnkr: http://plnkr.co/qM43RRgpbn7CQFTcx16L).

This kind of positioning should be named *static-mouse*. If anyone needs a *dynamic-mouse* positioning (tooltip moving with the mouse), this could be a future option.

Please reinvent this positioning! It should be the responsibility of the programmer to decide, if this positioning is ok for his use case or not.

**Comment by icfantv** [comment]
hey guys, this issue is almost 2 years old.  Additionally, the code in your plunker, @kwehrle, is using libraries that are insanely old.  You may wish to try with more recent versions of the libraries (Angular, Bootstrap CSS, and UIBS for starters).

If, after updating to the latest version of the libraries you are still seeing issues, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug) if you think you've found a bug.

I will say that the current `master` build of UIBS has completely overhauled positional placement including support for automatic placement and placement at corners instead of only top, bottom, left, and right.

**Comment by kwehrle** [comment]
hi @icfantv, it never was a bug, but a **sorely missing feature** that was available in earlier versions  (I think up to 0.7.0)

The issue is still a current one (regarding 0.14.3)! I updated my plnkr: http://plnkr.co/aEXsMR

Thank you for the tip, that in the next version there will be additional positioning options. But adhoc I can't see any option that is comparable to the old **mouse**-option, where the tooltip was positioned relative to the mouse pointer.

**Comment by icfantv** [comment]
Ooooh.  Thanks for the clarification - I didn't understand exactly was meant before.  To be honest, I don't know when we'd be able to get to this feature since it's not been in very high demand.  If you'd like to open a new issue with a feature request before spending time on a PR so that we can discuss this as a team, that's fine.

**Comment by kwehrle** [comment]
@icfantv 
There already have been some discussions (issues 832, 7106, ...),  but the core team never gave it a chance (again). 

As @skivvies already mentioned, the placement option **mouse** was kicked because of a little problem (issue 832). On the other hand I found some twbs users, really missing it 
> In the case of #832, that user was able to resolve his issue by using a different placement option anyway, so it seems like my use case was broken to fix a problem that didn't exist. Am I missing something?

Unfortunately I will not find the time to get deep into it and extend this feature.

**Comment by ats17** [comment]
I just started using uib-tooltip today, but can't continue because the placement options aren't appropriate on many of my larger objects. I need initial-mouse as proposed by kwehrle. Frankly, I can't understand how this wouldn't be a problem for a wide swath of users.

**Comment by icfantv** [comment]
@ats17, maintaining a large and popular OSS library requires a lot of work by many people who do it _all in their spare time_.  We have to balance the direction of the library and the needs of its users with ensuring the API doesn't get too large or too complicated.  People think they want flexibility until they're given 4,000 options and then it's just overwhelming.

Again, we welcome quality PRs and now that we've just officially released 1.0 - you, @kwehrle, or anyone else who desires this feature can look at the new positioning code to see how one might implement positioning based on the mouse cursor.  Even Bootstrap's API doesn't support placement based on mouse cursor out of the box - rather, you have to pass a function to the `placement` property and do all the work yourself.  And this gets really tricky when you're close to the edge of a viewport.

**Comment by icfantv** [comment]
I should also point out that with the 1.0 release, we support more out-of-the-box positional placements (i.e., corners) than Bootstrap does.
