### ISSUE TITLE
Make tooltips appear on disabled input fields

### ISSUE THREAD

**Issue by michaelhunziker** [angular-ui/bootstrap#1025]
Dear all!

Does anyone know how I could make tooltips appear on disabled input fields?

JSFiddle: http://jsfiddle.net/mhu23/XVnGn/4/

Obviously I need some kind of workaround since ng-disabled prevents all events from firing on disabled items. I just can't figure out a good way...

Thanks for any help!

Cheers
Michael

**Comment by icfantv** [comment]
@kaihenzler that solution won't work for form elements that are not buttons because it is simply cosmetic - it doesn't actually disable the form element.

**Comment by LuisPalomo** [comment]
Thanks for that solution @KyleMit it works perfectly :)

**Comment by erikdonohoo** [comment]
The real issue with this is in the `prepTriggers` function for `$uibTooltip` provider.  For some reason, it works if you DON'T do `element.on` and instead register the listeners that aren't click with `element[0].addEventListener`.  The problem lies in how jquery lite is handling the events.  I can open a PR that fixes this issue.

**Comment by nishantpandya** [comment]
Hi guys.. if we use ng-disabled in <select> then if ng-disabled is active then when we mouse hover over the select option then a cross icon displayed. Is it possible to remove that icon while hover over select drop down. Please provide the solution if is it possible.

Thanks,
Nishant

**Comment by adgoncal** [comment]
@nishantpandya 
`select[disabled]:hover {cursor: default;}`
