### ISSUE TITLE
Getting modal element

### ISSUE THREAD

**Issue by Charuru** [angular-ui/bootstrap#1057]
In the previous version $dialog we could access the element via modalEl.

I can't find the element through what I assumed to be the equivalent $modalInstance anymore. How do I access the modal element?

Thanks.

**Comment by marcalj** [comment]
I didn't know I can redefine a directive to extend behaviours! Thanks!
But in my case, I want to draw charts inside the modal, and each modal will be different, so no way to extend the ```modalWindow``` directive for the whole app.
The best way is to add CSS classes and create a directive for each class? :/

Thanks!

**Comment by Birowsky** [comment]
Is there a way to make it create a namespace-specific attribute? 

Something like `modal-window-my-modal`?

**Comment by Trindaz** [comment]
+1. Is there still no way to access the element used by the modal? Why does @pkozlowski-opensource make an argument that it's ugly to have DOM manipulation code in the controller for a modal? I ask this because even if as a general rule it is inadvisable (impossible?) to perform DOM manipulation in a controller generally, is that convention worth preserving at the expense of having some giant directive full of if statements, one for each of the modals in your application? I really don't follow this reasoning and would appreciate some more clarification on that.

One solution I am considering that minimizes the requirement of jQuery code without resorting to a global `modal-window` directive is to just provide a `getElement` resolve in the modal, which can perform a lookup in the context of the parent directive (if there is one) and it's element. Still not perfect, but it might be a way to avoid sprinkling `id` attributes throughout your modal template and having to search for them in your controller using jQuery.

**Comment by timhuff** [comment]
I feel that the element should be the value that's resolved in the `rendered` promise. So the code would be something like `open().rendered.then(function(element){})`
