### ISSUE TITLE
How can close other modals before open

### ISSUE THREAD

**Issue by atusoft** [angular-ui/bootstrap#1173]
I want to only one modal window opening , and close other modal before open it. By call "$('.modal').modal('hide')" only works for regular bootstarp modal, but not sure how to made it by angularjs-ui,  it looks hard to call dismiss method in other modal's.  

And I need keep modal window do not keep status when showing each time, in other words, all controls lost value after hide.  So "$('.modal').hide()" also do not works for me.

Is there any solution to destroy all modal window?

**Comment by NivedhithaV** [comment]
@ericprieto Thanks! You saved me.

**Comment by AlbertMelgoza** [comment]
@ericprieto Thank You!!

**Comment by jbownzino** [comment]
thank you @ericprieto !!!

**Comment by arunkrishnna** [comment]
Just a heads up, when we use $compileProvider.debugInfoEnabled(false); to improve your app performance, @ericprieto  solution will not work.

**Comment by wcea** [comment]
@ericprieto Hi, Where should that code snippet be located? In a controller of the first modal, secondary modal, main controller? I'm working with a stack that wants to exclude the JQuery library too

**Comment by ericprieto** [comment]
@wcea hey, this code should close every modal, whenever you run it, or at least it did 2 years ago when I wrote it, I don't really know if it still works, I don't use Angular anymore =\

**Comment by wcea** [comment]
@ericprieto Thanks, but what bigger context file/s does the code get added into? In what scope?

**Comment by ericprieto** [comment]
@wcea sorry, I don't know how to help you, it's been years since I stopped
using Angular... But this code uses jQuery to find the modals and access
their scope, so it should work wherever you run it.

On Monday, 27 June 2016, wcea <notifications@github.com> wrote:

> @ericprieto <https://github.com/ericprieto> Thanks, but what bigger
> context file/s does the code get added into? In what scope?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular-ui/bootstrap/issues/1173#issuecomment-228890474>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACjy6Ky-UqUZ_RCcAkRktZRzo3nt8tUbks5qQEl8gaJpZM4BGxI4>
> .
>


-- 
Eric Magliaro Prieto
Developer & Digital Designer
+55 11 99250-0785
<https://mail.google.com/_/mail-static/_/js/main/m_i,t/rt=h/ver=am293eyFlXI.en./sv=1/am=!v8Czf-oeNMn1BO3aNKsLQlGuxk8xCm64JDJ2Er8xszWKpq7UVAUov3Qmb7mBNv7VNf5Agg/d=1#SafeHtmlFilter_SafeHtmlFilter_SafeHtmlFilter_SafeHtmlFilter_SafeHtmlFilter_>
ericprieto.com

**Comment by wcea** [comment]
@ericprieto Ok, thanks for clarifying
