### ISSUE TITLE
date picker dd.MM.yyyy

### ISSUE THREAD

**Issue by fopsdev** [angular-ui/bootstrap#1289]
hi there, i'm testing the datepicker within angular 1.2.2 and bs 3 using our common swiss (and german) date format dd.MM.yyyy
just recognised that entering the date value manually in the textbox does not work as expected. it still uses the first number as the month.

http://plnkr.co/edit/1pdDca5KuWOWh3vPVRvz?p=preview

**Comment by svarjavand** [comment]
Why is this issue and all its referenced ones are closed? DatePicker still don't work with dd/MM/yyyy format when date is entered manually.
Try the plunker on https://angular-ui.github.io/bootstrap/#/datepicker and enter 24/05/2015
current version is: 
angularjs: 1.3.13
bootstrap-ui: 0.13.0

**Comment by rvanbaalen** [comment]
@svarjavand it seems like either this is broken again or @bekos closed it too fast. Reopening.

**Comment by rvanbaalen** [comment]
On a second thought @svarjavand please create a new issue to prevent this one from being polluted. This is closed because the actual issue is fixed; dates with `dd.MM.yyyy` format work.

**Comment by svarjavand** [comment]
@rvanbaalen I can create a new issue but even dd.MM.yyyy format doesn't work.
Try the plunker on the demo page and enter 24.05.2015 in the popup date picker. Selected date will be empty.

**Comment by rvanbaalen** [comment]
Fair enough. Reason enough to keep this open.

**Comment by realityking** [comment]
That's likely the issue described in #3644 (potential fix in #3682)

**Comment by hendrikebbers** [comment]
With version 0.13 the console shows the following error when typing the date "23.12.2007" (pattern: dd.MM.yyyy) directly after typing 23:
Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date.(anonymous function) @ angular.js:11655render @ ui-bootstrap-tpls.js:1071init.ngModelCtrl.$render @ ui-bootstrap-tpls.js:1059ngModelWatch @ angular.js:23423

Tis is working with version 0.12

**Comment by agriboz** [comment]
I would like to know why the datepicker popup date not updating as expected using `dd.MM.yyyy` format. 

http://plnkr.co/edit/7Fmcsz2rRDsi9U5eaeGz?p=preview
