### ISSUE TITLE
Should the directives support variable templateUrls?

### ISSUE THREAD

**Issue by joshkurz** [angular-ui/bootstrap#1611]
I know that it would be a simple change to allow for the directives in this repo to offer variable templates based off of the markup. As of now, the directives are hardcoded with specific urls, making it a little difficult to plug and play with Bower. 

update: it also makes it impossible to use the same directive with different templates.

Here is an issue https://github.com/angular/angular.js/issues/5867 brought up, which would allow for overwriting urls in $templateProvider. I believe that the templateUrls should be optionally overwritten by some attribute on the directive itself. 

Is this something that you guys are looking at doing or is the templateUrl hardcoded in the directives for a reason i'm not aware of?

**Comment by ackzell** [comment]
Hi everyone, 

I don't mean to stir up the water again, but I think I am facing the actual case where 

> I want to use a different template per directive usage

The thing is, we are using the accordion directive for 2 different purposes in the same app. One is to display a set of data and the other one is because the client wanted the behavior on a FAQ kind of page. 

So, for the set of data, we needed to display one button that would actually toggle the accordion-group but the rest of the heading won't trigger any change (this is where we had to alter the template and use one of our own).

Now for the other accordion, we want the standard behavior, where clicking anywhere on the heading will toggle the contents.

Right now, we have an issue where after modifying the heading for one of the accordions, the other got changed as a side effect.

I guess we could roll our own solution leveraging the collapse directive in either of the cases, but I was wondering if there could be a way to "switch" between templates.

I looked into the related links posted above but wasn't able to figure out what I am trying to accomplish.

**Comment by RobJacobs** [comment]
@ackzell There have been several recent [commits](https://github.com/angular-ui/bootstrap/commits/master) to add 'templateUrl' support, the one for the accordion can be viewed [here](https://github.com/angular-ui/bootstrap/commit/f777c320ccd45531490b2bbb58fd31e9c6472fdc).  Closing this issue as complete.

**Comment by ackzell** [comment]
Thanks a lot @RobJacobs, I didn't go back to the docs after implementing the accordions a couple weeks ago. Awesome timing!
