### ISSUE TITLE
Is it possible to have timepicker pop up like datepicker when you click on the input field?

### ISSUE THREAD

**Issue by eugenekgn** [angular-ui/bootstrap#1637]
Is it possible to have timepicker pop up like datepicker when you click on the input field?

**Comment by wesleycho** [comment]
This seems like something that users can implement - this is not likely to be used by a large number of users, and thus the project's stance is to encourage extensibility over containing all the bells & whistles (and avoid becoming more bloated).

Closing as won't support, but nothing is stopping anyone from creating a repository & implementing this themselves on top of this component!

**Comment by Bakirelived** [comment]
I think this is not something easily implemented. I tried to do it with this lib's popup, but it only accepts html via source file, so I can't pass a directive with context on that source file, and it makes things complicated. The @dduft and @randallmeeker lib is long, witch is also makes me believe that this is not something that user can implement easily. 

Also, I think most people that use this lib would like to have an input group with description, text and a calendar button with a popup to the timepicker widget, so I think this could be used by a large nubmer of users.

ofc I'm not asking to include the current work done because this is a minor issue when the cost is including moment dependence, but I don't think this should be discarded.

**Comment by wesleycho** [comment]
@Bakirelived unfortunately, we just don't have the bandwidth as a team to do this. Most of the team is actively working on [ng-bootstrap](https://ng-bootstrap.github.io), the Angular 2 successor. I currently am the only developer on the team who has pledged to be able to spend time on UI Bootstrap so far, but I too also have some busy moments (about to leave on a 2 1/2 week vacation to Europe).

I would love a well-implemented version, and would welcome a PR with a solid implementation + tests, but I don't see that happening realistically.

**Comment by vallabhvrao** [comment]
weighting eagerly for this important feature to be added!

**Comment by rajezvelse** [comment]
@randallmeeker Nice work
