### ISSUE TITLE
bug(modal) - modal scope is not destroyed on close

### ISSUE THREAD

**Issue by Halama** [angular-ui/bootstrap#1643]
Hi,
since version 0.10.0 modal $scope isn't destroy on modal close.
There are examples of this behaviour, please open browser console while testing.

Example using 0.10.0 (There is a bug):
http://plnkr.co/edit/luXIk8fRD3RaRYvFXUCA?p=preview

Example using 0.9.0 (Works fine):
http://plnkr.co/edit/qLAcaEcGryXOhBXoKp6v?p=preview

thanks

**Comment by chrisirhc** [comment]
@karianna , let's not be hasty to reopen this. #3308 doesn't explain what's broken and doesn't have a reproduction.

**Comment by citosid** [comment]
@chrisirhc did you find any solution?

**Comment by DannyFeliz** [comment]
I can't believe that this bug still messing around at this time. :-1:

**Comment by AndrewIsh** [comment]
I am experiencing this with v1.3.3. Would it be possible to re-open this issue, as far as I can see it is unresolved.

**Comment by barne397** [comment]
I am also experiencing this with v1.3.3. Further the motion to reopen this issue.

**Comment by barne397** [comment]
@AndrewIsh, I was just posting that I'm also having issues with v1.3.3, but turns out I had failed to account for an isolate scope on the directive where I was listing for the destroy event. So, I was listening to the wrong scope. It was getting destroyed, I just wasn't seeing the event.

Just wanted to mention that in case you're doing something similar.

**Comment by T0MASD** [comment]
Error: openedWindows.get(...) is undefined
persists with v1.3.3 on firefox

**Comment by amonsot890** [comment]
any clear solutions on this .?
