### ISSUE TITLE
Support grouping in typeahead

### ISSUE THREAD

**Issue by Urigo** [angular-ui/bootstrap#1691]
Hi, is there a way to support group inside the ui-bootstrap?

http://stackoverflow.com/questions/21430146/grouping-results-in-ui-bootstrap-typeahead

![screen shot 2014-01-29 at 1 41 34 pm](https://f.cloud.github.com/assets/1297448/2029135/a6256e0c-88dd-11e3-99e4-f138eae9e0fc.png)

**Comment by kayhadrin** [comment]
I'm facing the same need on my current project.
So far, we've simulated the option group feature by adding dummy items in the array of matches, that have a special property (to know it's a group header), then we display them differently.
So that's... roughly possible. Now though, I need to make the option group element non-selectable.
I'll probably create a fork where we have the ability to disable some option elements.
Would that interest you?

**Comment by brunowego** [comment]
+1

**Comment by icfantv** [comment]
@brunowego, please do not just add a `+1` to issues as it adds no intrinsic value to the discussion and serves to only clutter up a thread.  You might be interested in the `ui-select` project for this functionality, but I will say that development has stalled somewhat on it - but it still works quite well.

**Comment by brunowego** [comment]
@icfantv, you right, sorry :+1:
