### ISSUE TITLE
Typeahead : Filters do not work with Promise as source

### ISSUE THREAD

**Issue by dcolaizzomarathon** [angular-ui/bootstrap#1740]
Filters work in expressions passed to typeahead for static arrays. They are ignored when the array source is an asynchronous request.

See 'Asynchronous Results' example provided by documentation. http://plnkr.co/edit/w8uxP0?p=preview. Both filter: and limitTo: are ignored in the results dropdown.

**Comment by adonespitogo** [comment]
@ghost - You can use `$filter` service in the controller:

```javascript
function ($scope, $filter, myService, $q) {
  $scope.search = function (query) {
    var deferred = $q.defer(); // https://docs.angularjs.org/api/ng/service/$q
    var searchPromise = myService.querySomething(query);
    searchPromise.then(function (results) {
      var filteredResults = $filter('filterName')(results, arg1, arg2, argNth); // https://docs.angularjs.org/api/ng/service/$filter
      deferred.resolve(filteredResults);
    });
    return deferred.promise;
  };
}
```

Return another promise with the filtered results instead of returning the search promise directly.

**Comment by sigMacity** [comment]
Given the number of requests (for info, how to's, please help's, etc) there are regarding forced selection of async sources i.e. invalidating when initial value not available from source, invalidating if value isn't selected from source list and so on, it may be worth re-opening this item. IMHO it makes sense to do this from within the typeahead code, rather than frigging around in the calling code.

**Comment by worthy7** [comment]
If you are querying your database, you surely want it to stop after X number of results. So the most efficient way to do this is to set/send the limit serverside. And for anyone searching locally instead, then using the filter function seems fine.
