### ISSUE TITLE
Nested results in typeahead

### ISSUE THREAD

**Issue by AlexCppns** [angular-ui/bootstrap#1896]
I need typeahead to show nested results (2 ng-repeats) with a custom template. Is there some way to do it?

**Comment by wesleycho** [comment]
One could implement this via overriding of the typeahead-popup template and creating a custom set of directives.

Otherwise, this is a little complex of a feature for this library to have baked in & not something likely to be used widely, thus we would not want to support this in the library itself, but allow users to extend it to support this.
