### ISSUE TITLE
IE10 Accordion Collapse Fail

### ISSUE THREAD

**Issue by bensquire** [angular-ui/bootstrap#2002]
Hi All,

I've created an app which makes use of three nested accordions, in Chrome, FF, IE11, Safari; these work perfectly.

The problem is in IE10 where the transition that causes an accordions contents to display doesn't complete. Using various inspectors I've determined that an inline style for height is set to some arbitrary pixel value and the 'collapsing' class added to the element. But the height style is never increased and so the content of the accordion expands into an div thats too small, hidden from view.

As far as I can tell its this function which is responsible, but not completing:

        function expand() {
          if (initialAnimSkip) {
            initialAnimSkip = false;
            expandDone();
          } else {
            element.removeClass('collapse').addClass('collapsing');
            doTransition({ height: element[0].scrollHeight + 'px' }).then(expandDone);
          }
        }

Line 119 of ui-bootstrap.js (v0.10).

Any help would be appreciated as otherwise I'm going to have to roll a custom solution which negates the benefits of the library....

Thanks in advance :)

Ben

**Comment by khichar-anil** [comment]
I am also facing the same issue with IE10.

**Comment by khichar-anil** [comment]
Anyone able to get it resolved? I need it desperately.

**Comment by khichar-anil** [comment]
Hi All,
I my case I was having hierarchical accordions (accordions within accordion). The issue was with the inner accordion, which did't get full content height in IE 10. Actually while expanding the inner accordion, parent accordion didn't get resided including new child content. It's working fine in IE 11 and other browsers seamlessly.

The issue was on the following animation (transition) line of code:

````doTransition({ height: element[0].scrollHeight + 'px' }).then(expandDone);````

I get it resolved with a quick patch for IE10:
```javascript
if ($('#ie10').length)
   expandDone();
else
  doTransition({ height: element[0].scrollHeight + 'px' }).then(expandDone);
````

So in IE 10 I will not be getting animations while expanding but other browsers will work seamlessly. I know it's not a good solution, but in my tight deadline I can't dig anymore.

If anyone suggest better way, It will be really helpful.

**Comment by bensquire** [comment]
@khichar-anil I can confirm that I also had the issue with hierarchical accordions.

**Comment by sroberson** [comment]
+1 on this.  I'm having this problem and don't really know what to do to get around it.

**Comment by chrisirhc** [comment]
I'm merging in fixes for the collapse directive. Perhaps after merging #1444, this would be invalid.

**Comment by wesleycho** [comment]
Closing, as there is not enough information to act upon, nor is it known whether this is even an issue still - if there is a reproducible scenario, please open a new issue with the reproduction.
