### ISSUE TITLE
Datepicker popup timezone interpreted incorrectly

### ISSUE THREAD

**Issue by dotcom9** [angular-ui/bootstrap#2072]
This may be related to https://github.com/angular-ui/bootstrap/issues/1031, but I'm not convinced it's exactly the same, so here's a fresh issue.

When you supply the datepicker popup with an ISO date with no timezone information, it interprets it as a UTC date, with the result that it displays the date incorrectly if the browser timezone is not also UTC. 

For example, for a browser in EST (GMT-5) if the popup is given date "1980-03-03T00:00:00", the date displayed is 1980-03-02. Presumably it internally translates the supplied date into local time ("1980-03-02T19:00:00 EST").

As #1031 points out, an ISO date with no timezone information should be treated as a local date, so no adjustment should be made.

Although arguably this should be the default behaviour of the datepicker popup, I was hoping that as a workaround, I would be able to adjust the input using a custom formatter, in the same way that custom parsers are used to adjust the output value, However, when a custom formatter is applied, the popup behaviour is the same. Even though the formatter is called, It appears that the popup uses the raw model value rather than the formatted value.

This can be seen in this plunker; the formatter returns a random hard-coded date value ("01/01/1900") which is applied to the input element. Open the popup and see that the date has been set from the model value, ignoring the formatter. Set your browser PC to EST timezone and see that the popup is set to the day before the model value.

http://embed.plnkr.co/1r2i2IVKQVszXQ4IQXMl/preview

Is there any way the input value to the popup can be intercepted and modified to avoid this behaviour?

**Comment by snoopy72** [comment]
+1

**Comment by paulflo150** [comment]
How about just converting the json date string when you get the data from the server:
i.e.: $filter('date')(data.BirthDate, 'MM/dd/yyyy', 'UTC');

**Comment by pm31** [comment]
+1 works fine

**Comment by iyel** [comment]
+1

**Comment by thuey** [comment]
+1

**Comment by barbolo** [comment]
+1

**Comment by commodoretyler** [comment]
@paulflo150 has the right of it. If you simply use Angular's date filter on the model first it will give you the correct date without consideration of timezone

**Comment by nsilvah** [comment]
Directive to fix issues with negative timezones:

https://gist.github.com/nsilvah/a7a31f017de098a79f38

**Comment by fmancini** [comment]
![687474703a2f2f692e696d6775722e636f6d2f426f3149632e6a7067](https://cloud.githubusercontent.com/assets/1574862/7322328/be9d32e6-ea7d-11e4-97c4-7539dac6fc13.gif)

**Comment by palamago** [comment]
WELL DONE @nsilvah !!!
![CLAP CLAP]
(http://www.gifbin.com/bin/1233928590_citizen%20kane%20clapping.gif)

**Comment by cstefanache** [comment]
+1

**Comment by niranjan-** [comment]
+1 
@weberste  you rock!!

**Comment by wilg** [comment]
I worked around this by using a getterSetter with ng-model-options to perform the time zone conversions.

**Comment by qvaqvaboo** [comment]
Another workaround is to modify JS Date object to always use UTC get/set methods. Not sure how this affects moment.js and other libs/plugins though.

```javascript
Date.prototype.getDate = Date.prototype.getUTCDate;
Date.prototype.getDay = Date.prototype.getUTCDay;
Date.prototype.getFullYear = Date.prototype.getUTCFullYear;
Date.prototype.getHours = Date.prototype.getUTCHours;
Date.prototype.getMilliseconds = Date.prototype.getUTCMilliseconds;
Date.prototype.getMinutes = Date.prototype.getUTCMinutes;
Date.prototype.getMonth = Date.prototype.getUTCMonth;
Date.prototype.getSeconds = Date.prototype.getUTCSeconds;

Date.prototype.setDate = Date.prototype.setUTCDate;
Date.prototype.setFullYear = Date.prototype.setUTCFullYear;
Date.prototype.setHours = Date.prototype.setUTCHours;
Date.prototype.setMilliseconds = Date.prototype.setUTCMilliseconds;
Date.prototype.setMinutes = Date.prototype.setUTCMinutes;
Date.prototype.setMonth = Date.prototype.setUTCMonth;
Date.prototype.setSeconds = Date.prototype.setUTCSeconds;
```

**Comment by skuepper** [comment]
I had the same problem, and found the easy solution here: http://stackoverflow.com/questions/27172394/javascript-doest-convert-angular-ui-datepicker-date-to-utc-correctly
Using the "cs-date-to-iso" directive together with the datepicker-popup corrects the wrong ng-value 
and makes me happy :-)
HTH

**Comment by wesleycho** [comment]
Looking at this further, what looks like is the root of this problem is that `date.toJSON()` is converting the date object into a string with the timezone shifted, which can result in a date shift.

[This fork of the Plunker](http://plnkr.co/edit/ovWR8iATIprS6nGUihcm?p=preview) makes it clear - IMO, this particular issue is not a bug, but actually a subtle aspect of dates one must be careful about.

**Comment by eejai42** [comment]
+1

**Comment by icfantv** [comment]
@eejai42, please do not only add a `+1` to issues as it adds no intrinsic value to the discussion and serves to only clutter up the thread.  Please read the last comment by @wesleycho as to why this will not be fixed.

I should also note that the datepicker now only accepts a JS `Date` object so the onus is on the API user to ensure their date is correct.  If you require a rigid structure for your dates and date conversion you may use our `$uibDateParser` service (included in UIBS) or the absolutely fantastic third party library moment.js.

**Comment by eejai42** [comment]
I have deleted my +1.  I'm confused though.  I understand the complexity of dates/time-zones/etc, but what I understood the original request to be (and the reason I added the +1) was that they wanted to be able to configure the datepicker to operate independently of timezone.  

In other words, looking at the plunker - it shows the selected date as being March 2nd at 6:00 PM.  If I change the timezone of my computer, it changes this date to March 2nd at 7:00 PM which is going to be the desired behavior MOST of the time, because 3/2 at 6:00 CST is the same as 3/2 at 7:00 EST, unless... it isn't.  

In the app I'm working on right now for example, it keeps track of a class that is happening in a specific location.  So the time of the class doesn't change based on where a user is, or what timezone they're in, but rather, the class will be taught at 5:00 PM in the timezone where the class is being taught.  So it's confusing to my users to have it show that as 6:00 PM when they look at the class from a different timezone - because the class is still going to be at 5:00 (where it is being taught).  

So what feels like it would be a good _feature_ would be to have the date picker have an **option ** to show the date as presented, rather than first converting it to a local time.  Maybe I'm just misunderstanding wesleycho's comment - but it feel like are 2 different ways that the calendar could behave when presented with the date '2015-03-02'.

I agree that it it's a bug, for sure - but it feels like there's room for an option to either have the date-picker convert to local time (or not) based on what is appropriate for the app.  No?

**Comment by deeptinair17** [comment]
It still does not work for me :(

**Comment by vaibhavmagon** [comment]
+1 Issue still exists!

**Comment by yuripramos** [comment]
+1 
.
.
2 years passed and we are facing the same issue? 
Trying to force +1 inside the library before return the utcDate but without success..

**Comment by florin-lei** [comment]
2018... issue not resolved

**Comment by tagama** [comment]
Just use another lib
