### ISSUE TITLE
Tab selects fired during scope destruction

### ISSUE THREAD

**Issue by samward1985** [angular-ui/bootstrap#2155]
After updating to 0.11, I'm having issues with the tab select function.

I have a function as follows:
```
<tab select="logOut()">
```

I'm finding that logOut() fires whenever I click any link in any of the tab content areas.

**Comment by mu7amed-abdelfata7** [comment]
The problem is still remaining and did not fix but i made a solution for me to solve the problem:
1- I added this function in <TabsetController>:

 var destroyed = false;
  ctrl.destroyTab = function destroyTab(tab) {
	  console.info("ctrl.destroyTab = function destroyTab(tab) {");
	  destroyed = true;
	  ctrl.removeTab(tab);
  };

2-I calling destroyTab() rather than removeTab() in  $on('$destroy') in tab directive:
scope.$on('$destroy', function() {
          tabsetCtrl.destroyTab(scope);
        });

please see if this solution is proper for the directive or not.

**Comment by karianna** [comment]
@mu7amed-abdelfata7 Can you open a new issue with a plunkr please.

**Comment by wesleycho** [comment]
I am not seeing this issue currently [here](http://plnkr.co/edit/kmpDzRr50TxUT1pO5JT0?p=preview).

Feel free to open another issue with a reproduction if possible as suggested.
