### ISSUE TITLE
feat(popover): support template url for partial

### ISSUE THREAD

**Issue by zero-** [angular-ui/bootstrap#220]
As requested in #202 by @joshdmiller here's my request for external partial support for popover which would make popover much more versatile and lower the need of duplicate code in the apps. Already working implementation can be found in one of the "competing" Bootstrap implementations at http://mgcrea.github.com/angular-strap/#/popover.

**Comment by DaveWM** [comment]
I got fed up waiting for this feature, so I made the [ngPopoverButton directive](https://github.com/DaveWM/ngPopoverButton). Posting it here in case some of you guys would find it useful.

**Comment by madhums** [comment]
can't believe this thread is still open!

**Comment by QuentinFchx** [comment]
What is preventing the PR to be merged (apart from conflicts) ?
I'd be glad to help fixing the last issues!
It needs to be merged asap because this is becoming hilarious (1 year issue, with 200+ comments, on a 7k stars project, just to allow html in a popover...)

**Comment by karianna** [comment]
@QuentinFchx https://github.com/angular-ui/bootstrap#impt---2015-plans-and-angular-13-support

**Comment by QuentinFchx** [comment]
The [0.12.1 milestone](https://github.com/angular-ui/bootstrap/milestones/0.12.1) only contains the https://github.com/angular-ui/bootstrap/pull/2996 PR tagged as `needs:merging`. How can I help to make this happen ?
This will allow us to move forward toward 0.13.

**Comment by karianna** [comment]
We'll be merging that issue at the next maintainers meeting.  @chrisirhc will be teaching the rest of us new maintainers to cherry pick the fix and perform a full release.  Then we get onto the hard work of triaging the ~120 or so PR's out there :-).

**Comment by stramel** [comment]
@karianna :+1: This is great news for this library.

**Comment by nnjpp** [comment]
That is such an enormous relief. I was under the impression that the project had seriously lost momentum but it looks like I'll soon be able to start recommending it again.

**Comment by karianna** [comment]
Well I'm not going to promise miracles as there are 187 outstanding Pull Requests to get through for starters, but yes you should start seeing some movement over the coming weeks.

**Comment by Yappli** [comment]
Marvelous !

**Comment by metanav** [comment]
Any progress? I understand guys are working purely part-time and unpaid and I appreciate that.
But I think this issue is blocking many of us.

**Comment by karianna** [comment]
Meeting tonight to begin the first steps.

**Comment by Alos** [comment]
Hey guys? Did you got a chance to talk about this?

**Comment by karianna** [comment]
No, our priority is to get Angular 1.3 compatibility - next step is to triage 200 open PRs, step after that is to triage 300 open issues.  Then we look at the rest :-)

**Comment by starf** [comment]
I do not comprehend. Been using 1.3 since beta without a problem. The amount of response here is ridiculous.

**Comment by mattdarveniza** [comment]
Wait, so this wasn't discussed at all? I appreciate that you're trying to get this project back on track after it completely fell of the rails for whatever reason, but this issue is coming up on it's 2 year anniversary (and it wasn't even the first to request this functionality), all the while people are forced to use other libraries like angular-strap, fork this repo and make the fix themselves, or do crazy duck-punches in their projects, all for what is a relatively simple change that has a PR ready to go. If this doesn't come through in 0.13 it's going to be hard to justify recommending this library to anyone anymore.

**Comment by forza020** [comment]
Guys, use angular strap (http://mgcrea.github.io/angular-strap/)  until this issue will be fixed. The same number of features + popover has HTML

**Comment by seiyria** [comment]
@forza020 it's not a clean switch. You can't put templates / html in your dropdown menus cleanly, for example. You just have to consider what features you need and pick the best one based on that; it's not as simple as "they still don't have feature x, just go use y."

**Comment by forza020** [comment]
I know. That is why the only way is to combine these 2 modules until
bootstrap ui will not support HTML in popover.

2015-02-25 15:05 GMT+02:00 Kyle J. Kemp <notifications@github.com>:

**Comment by yordis** [comment]
This was in 2013, today 2015 still without any update about it. This is the reason why people great forks and boom a new javascript framework because even when they take the time for create the PR for contribute. 

@forza020  I will take a look to angular-strap, hopefully is a good route to go.

**Comment by danielcompton** [comment]
These comments aren't adding anything to the issue, I recommend locking this issue to contributors, and updating it when the feature is added.

**Comment by yordis** [comment]
@danielcompton you suggestion is shut down the opinion of the people. This add value to the issue, you know why, because you can see the effort from them. People like me trust them and the fact some guys even create the PR + Unit Testing + Doc and they don't do anything about. This was 2 years ago sir, this wasn't 1 month and look the how many +1 are here ..... Close the comments, "good way" of fix problems

**Comment by danielcompton** [comment]
@yordis I think we're all well aware of the need for this feature, and I too am frustrated that it's not available yet. However GitHub issues aren't the place for complaining about a bug or missing feature, they're for fixing it. The negative comments aren't adding anything of value, and they're bringing down the contributors. If you want something to change, your options are:

1. Become a contributor to angular-ui, and land the patch in a way that fits with the contribution guidelines
2. Do nothing and wait for the feature to arrive sometime in the future
3. Use a different UI library with this feature

If you just want to complain, then I suggest you save it for your bartender :wink:.

**Comment by hallister** [comment]
This issue is a tough one, largely because it's been buzzing around for so long. I've been debating the merits of closing this for I don't know how long, largely due to a couple of significant fixes for this issue as open PR's. And since I'm not actively contributing to the project right now, it's debatable whether or not I should.

That being said, this project lost momentum as many of the maintainers had to real-life obligations and other projects take over. As a result the current/new maintainers have *a lot* of work ahead of them with some 200 PR's and over 500 open issues.

As a result, I'm going to close this for now (with the caveat that a current maintainer is more than welcome to re-open for any reason). Not because I have any desire to close down discussion, but because this horse has been dead a long time and it's less a matter of needing a fix and more a matter of needing to fix other things in order for this to get merged in.

**Comment by DaveWM** [comment]
@hallister surely in the time it took you to write that comment you could've just merged in one of the multiple open PRs for this (#1848,#2479, etc.)

**Comment by hallister** [comment]
@DaveWM Both of those have merge conflicts that need to be sorted out and I'm not actively contributing to the project right now, so it's highly unlikely that I could have merged it quickly. 

Furthermore, because there are so many outstanding PR's, merging into master right now is going to do nothing more than cause more problems. With 200 open PR's, a great deal of care has to be taken on what gets merged.

I realize everyone is frustrated with the pace here, but this is still an open source project developed entirely by volunteers. I realize this issue has been around for a long time, but it's going to take a little more patients before this is merged in.

**Comment by RobJacobs** [comment]
@DaveWM @hallister  My thoughts are this should not be part of the library.  We should be focusing on making directives that have a single responsibility that people can use as components to build more complex directives.  We shouldn't build directives that transcludes 2 different content areas, handles dismissing, and handles popup placement all in one.  Rather these should be discreet directives (dismiss, placement, etc...) that are independent and can be re-used.  That being said, here is a [plunk](http://plnkr.co/edit/C6peZ8ZEWgSlcfw3Q65E?p=preview) that demonstrates that approach for the popover.  You will notice I am using the native TWBS markup and classes to build the popover and only have a single directive that handles the dismiss.  No need to transclude content, or trigger a scope.$apply to reposition the element after content changes, or the numerous other rabbit holes we go down to support a 'god' directive.  While it is convenient not to have to write all that html, that should be a convenience reserved for simple cases.

I am also working on an approach for more placement options by using classes (can be bound to ng-class for dynamic placement), which can be seen in this [plunk](http://plnkr.co/edit/XWYE6iIvYmDpwlk8K0A3?p=preview).  This does not use pixels to set top, left, right, or bottom so as content grows, the container will resize without losing the anchor point.

If you are set on template support in the existing popup directive, I have a pull request [here](https://github.com/RobJacobs/bootstrap) with all conflicts resolved against the current master branch,

**Comment by seiyria** [comment]
@RobJacobs I strongly disagree that this shouldn't be part of the library, and clearly so do many others. If the goal of this library is to recreate TWBS functionality with Angular-style markup, anything like this should definitely support templates at the bare minimum.

**Comment by DaveWM** [comment]
Completely agree with @seiyria. @RobJacobs, you seem to be saying that the entire popover directive should be re-written, and regardless of whether that's a good idea or not, it's not really what's up for discussion here. Also, I hardly think adding something as simple as dynamic content would make popover a "god directive".

**Comment by pioneer903** [comment]
Interesting thing, but it looks like popover template worked before. I found working plunkr [http://plnkr.co/edit/5oX2lA?p=preview] with angular 1.2.9. However 1.3.x doesn't work.
As an alternative, i found nsPopover https://github.com/nohros/nsPopover. Going to give it a try

**Comment by jbruni** [comment]
Since my previous [comment on 28 May 2014](https://github.com/angular-ui/bootstrap/issues/220#issuecomment-44452302), I've been away. Surprised to see that this is still an issue, I have just made a new version, mergeable to current HEAD.

- [See it in action](http://codepen.io/anon/pen/XJodJr)
- [Get the ready-to-use code here](blog.jbruni.com.br/javascripts/ui-bootstrap-tpls-0.13.0-jbruni.min.js) or [here](https://github.com/jbruni/jbruni.github.io/blob/master/javascripts/ui-bootstrap-tpls-0.13.0-jbruni.min.js)

There is a difference now. While I was not expecting merge for my previous versions, because I knew they dissonate from the project's "roadmap", so to say... this time the patch does not affect absolutely **nothing** on existing code and **embraces** the design decisions taken. (While I previously made it NOT destroy the tooltip when it was hidden, now I kept the tooltip-removal code untouched.)

This is why, unlike many of my previous attempts, at this time I am opening a new PR. Just as I knew chances of merging were poor in the past - this time I sincerely believe there is no reason for not being embraced. The code is absolutely simple, unobstrusive and harmless. Please, take a look and consider. Thank you.

- [Here is the Pull Request, where you can see the minimal and simple code.](https://github.com/angular-ui/bootstrap/pull/3409)

**Comment by chrisirhc** [comment]
#1848 is pending a name poll, otherwise, it's mostly good to merge.

**Comment by QuentinFchx** [comment]
:joy:

**Comment by nomospace** [comment]
Your guys kicked ass!

**Comment by Yappli** [comment]
I want to cry. Thanks everybody.

**Comment by karianna** [comment]
FYI - Actually resolved in 0.13.0 but due to GitHub DDOS I can't change the milestone

**Comment by metanav** [comment]
Will it be part of 0.12.2 release?
What is the expected release date (or month) of 0.12.2 or 0.13.0?

**Comment by karianna** [comment]
There won't be a 012.2, 0.13.0 is the next release, no concrete ETA yet.

**Comment by sebastianovide** [comment]
fantastic !. any ETA yet ?

**Comment by HeavenGoGo** [comment]
just wait the release version, the issue last for too much time

**Comment by Kizmar** [comment]
Why is this not released yet? The popover is mostly useless without the ability to use templates. Might as well just use tooltips.

**Comment by eabovsky** [comment]
+1

**Comment by funkybaboon** [comment]
+1

**Comment by chrisirhc** [comment]
Locking this issue as the feature has been released. Please open a new issue if there are further comments.
