### ISSUE TITLE
Modal 'windowClass' option not working anymore?

### ISSUE THREAD

**Issue by wasphub** [angular-ui/bootstrap#2319]
I moved fro 0.7.0 to 0.11.0, and now I do not see the value specified with option `windowClass` assigned as a CSS class to the modal window anymore, as it was happening with 0.7.0. The `link` function in the `modalWindow` directive is executed, and with it the `addClass` line, but the incoming `element` has a weird selector with an unresolved `{{windowClass}}` binding expression, which might be related to the issue.

I did not see anything about that in the change log, am I missing something or is it a bug?

Note: I solved my issue anyway playing with CSS, but if I did not miss anything and it's intentional then maybe it should have been listed as a breaking change.

**Comment by jci-yarora** [comment]
I am also seeing the same issue using 0.11.0 version. Adding windowClass parameter is simply adding a custom attribute with the value as the class name you want to add. I had to use custom attribute selector in css to access that to make it work. Just pointing it out as the documentation doesnt say so

**Comment by naveenraina** [comment]
I am using 0.13.0 version and I also faced this issue. However after comparing my templates with the the this version, it seemed I had not updated the templates lately and it was because of the old templates which was causing the bug. After replacing window.html with the one in https://github.com/angular-ui/bootstrap/tree/master/template/modal, this issue was gone.
