### ISSUE TITLE
How to close modal dialog in a angular service

### ISSUE THREAD

**Issue by vb8190** [angular-ui/bootstrap#2398]
Hi,

I want to control the opening and closing of modal dialog from a angular service. Currently, you can open the modal dialog from anywhere including services by following method:

var modalInstance = $modal.open(.....)

but there are only two ways to close it:

either create a controller and then define close function on $modalInstance or use $close or $dismiss on $scope. But none of these mechanism will work if somebody wants to close the dialog from  a service(unless service sends some kind of event on rootscope and the modal controller listens for it and then issue close on $modalInstance) which is not ideal.

What would have been ideal if a close or dismiss methods were available on the same javascript object which holds the reference as shown above. To be more clear here is what would have made life little bit more easier for services secnario:

var modalInstance = $modal.open(.....);

modalInstance.close(..); or modalInstance.dismiss();

I am trying to create a loading spinner functionality but it will display on a modal window and I want to control the show and hode fo this spinner in a http interceptor or wrapper http service. This would be global show and hide for all the http calls in our project.

But with current design there is no good way of closing the modal in a service or interceptor.

**Comment by antoinepairet** [comment]
@vb8190 Here is a fork of your plunkr showing you how to use the close function: http://plnkr.co/edit/6hutLZRrQnwWVAJrYyb9?p=preview
FYI: the relevant part of the source code is here: https://github.com/angular-ui/bootstrap/blob/master/src/modal/modal.js#L342

Your plunkr is not working and throws an error because you call the close method immediately after having opened the modal. As stated by @c-johnson the PR #2325 will prevent an error from being thrown.

Closing the issue.
