### ISSUE TITLE
Nested dropdowns

### ISSUE THREAD

**Issue by Yankovsky** [angular-ui/bootstrap#2421]
Any plans to support nested dropdowns? I made example [jsfiddle](http://jsfiddle.net/5KsLW/1/). Currently, only one dropdown can be open at a time due to [dropdownService's open method](https://github.com/angular-ui/bootstrap/blob/master/src/dropdown/dropdown.js#L10).
I tried to make a use of ```require: '^dropdown'``` in child dropdown directive, but it is returning child dropdown controller, not his parent because of [bug](https://github.com/angular/angular.js/issues/4518).
So, any ideas how to handle this situation?
Thank you.

**Comment by lazercore** [comment]
Anyone?

**Comment by theaqua** [comment]
Anyone?

**Comment by dmitriz** [comment]
Here is a pure CSS implementation if that helps:
http://bootsnipp.com/snippets/featured/multi-level-dropdown-menu-bs3

**Comment by RobJacobs** [comment]
@dmitriz Nice find, thanks for sharing.

**Comment by sebastianhenneberg** [comment]
I added nesting capabilities to the dropdowns and created a PR. Please check out the referenced PR #3776 or grab my [monkey-patch](https://gist.github.com/sebastianhenneberg/acb0a5e7b0e63006c699). Any feedback is highly appreciated!

**Comment by wesleycho** [comment]
I put some more thought about this, and I am making the decision to reject this feature request - this adds complexity for what is a bad UX, which is a net negative for the project.

**Comment by shyamal890** [comment]
@wesleycho WHY?!!! This is very much needed. There are use cases where you would need a dropdown inside a dropdown.

**Comment by wesleycho** [comment]
@shyamal890 the amount of code required to support this, which will have lots of side effects, is not justified with why this is a valid UI/UX for the user.

**Comment by azahreba** [comment]
Actually, I fixed it in 3 lines in JS, without any tricks with CSS or HTML.
https://github.com/azahreba/bootstrap/commit/b86cbda99275670e27aa94f293423ee7cef303d7 (a simple factory pattern is used there).
Now there are 2 failed unit-tests and that's the question - how to fix them.
Because I've tried to reproduce those unit tests on the real app, and everything is working properly with ```class="open"```.

**Comment by Mike-Loffland** [comment]
@sebastianhenneberg Thanks for the monkey patch... works like a charm.

**Comment by notbrain** [comment]
@wesleycho A shame this is outright considered bad UX - the main use case I am trying to support is a Typeahead inside of a dropdown, not another "typical" dropdown for more menu access. Typeahead itself uses a dropdown, and is not a "bad UX" per se if used inside of a dropdown, and would be particularly *useful.*

**Comment by icfantv** [comment]
@notbrain, we've run this by several UX people and devs and we all think it's just bad UX and weird - read:  not normal UX behavior.  as such, this is not something we are going to support.  Also, it looks borderline awful when open.

If you could talk about what you want from a user's perspective, perhaps we could help you come up with a better design/workflow.

**Comment by notbrain** [comment]
@icfantv Not a huge deal, but I just created a sort-of dropdown to house something like a contextual panel that would have a form on it...on the form are 4 fields, two typeaheads and 2 datepickers. The datepickers work fine since they are add to body, but since the typeaheads are position-sensitive they needed to be inline, in which case they interfered with the wrapping dropdown.

In the end the initial wrapper didn't need to be a dropdown, so I just did a custom hide/show panel to house the form. It's really not so bad since it's a different mode (text input) and the only reason the typeahead didn't work is because it itself uses a dropdown for implementation:

![image](https://cloud.githubusercontent.com/assets/67282/12930037/f65cd8de-cf2a-11e5-81cc-910c0d820c34.png)

**Comment by RobJacobs** [comment]
This looks more like a popover with a nested typeahead which is supported.

**Comment by icfantv** [comment]
@notbrain, i'm glad you got something working.  you might take a gander at what @RobJacobs suggested since dropdowns are _usually_ used for navigation or actions.

**Comment by notbrain** [comment]
@RobJacobs thanks, should have done my homework to have seen that. Sometimes tunnel vision sets in when you get comfortable with certain controls.

**Comment by alirezamirian** [comment]
The original gist from @sebastianhenneberg doen't work when `dropdown-append-to-body` is set (because it calls `getElement()` instead of `getDropdownElement()` to look for child dropdowns, which fails when dropdown menu is appended to body instead of dropdown itself).
I've forked and fixed it here: https://gist.github.com/alirezamirian/b6cc3d5bc421d6e5338c002acde5e5bc

I also change it to decorate `uibDropdownService` instead of `dropdownService`

**Comment by ileathan** [comment]
I solved the problem by just home baking it dont even remember how or id mention...

Why is this marked closed anyway? Too much code to implement? Hmm... but that guy did it right after?
Hmmmm... oh well unsubscribed.
