### ISSUE TITLE
Disable Tooltips on Touch Device

### ISSUE THREAD

**Issue by avizuber** [angular-ui/bootstrap#2525]
How would one disable tooltips in touch devices (tablets/phones)? I love using angular-ui bootstrap, but users on touch devices to click tooltip-enabled buttons twice (once to display the tooltip, next to take action). Hiding it using CSS and @media queries doesn't work because technically the tooltip is still there, it's just not visible. Any thoughts?

**Comment by BobbieBarker** [comment]
Looks like OP's question has been answered. Thanks to the community members who pitched in and helped him out.

**Comment by titobf** [comment]
@dust4ngel Thanks for sharing your solution. I actually needed to do it that way because I needed to inject the deviceDetector service so I can check for mobile devices by doing deviceDetector.isMobile().

**Comment by shuhei** [comment]
@AParks Thanks for your clever idea! It looks like we have `none` trigger for this purpose. https://angular-ui.github.io/bootstrap/#/triggers

**Comment by aslepiak** [comment]
@AParks I'm trying to get your solution to work, unfortunately I'm getting _Uncaught Error: [$injector:modulerr]_  all the time.

Any idea, what i'm doing wrong?

**Comment by AParks** [comment]
@shuhei nice! I'm still using bootstrap version 0.12.1, which doesn't have that `none` option, but I will be sure to update this, once I can upgrade the version. :)

**Comment by AParks** [comment]
@aslepiak ah I bet it's because there was a syntax error! It should be 
``` javascript
var options = {
    trigger: 'dontTrigger'; // default dummy trigger event to show tooltips
};
```
instead of 
``` javascript
var options = {
    trigger = 'dontTrigger'; // default dummy trigger event to show tooltips
};
```
Sorry about that! I've updated the original post.

**Comment by shuhei** [comment]
@AParks @aslepiak I guess `;` should be omitted:

```js
var options = {
    trigger: 'dontTrigger' // default dummy trigger event to show tooltips
};
```

**Comment by aslepiak** [comment]
I finally managed to do it as I wanted:

`app.config(['$uibTooltipProvider', function ($uibTooltipProvider) {
    var parser = new UAParser();
    var result = parser.getResult();
    var touch = result.device && (result.device.type === 'tablet' || result.device.type === 'mobile');
    if ( touch ){
      $uibTooltipProvider.options({trigger: 'dontTrigger'});
    } else {
      $uibTooltipProvider.options({trigger: 'mouseenter'});
    }
}]);`

It's worth mentioning, that $tooltipProvider changed name to $uibTooltipProvider in the meantime.
Also, it won't work if you already have popover-trigger set in parent element.

It would be really nice, if we had an option to disable popovers on mobile, since 

> Note to mobile developers: Please note that while popovers may work correctly on mobile devices (including tablets), we have made the decision to not officially support such a use-case because it does not make sense from a UX perspective.
> 

Anyway big thanks to everyone posting in this thread (especially AParks). I'd never done this myself :)

**Comment by bartonsprings** [comment]
This is not working for me. The UA parser is getting the right information but even though the code goes into this section for touch devices but the popovers are still enabled (present). 

What could be the reason? I am using the version: 2.1.3 of ui-bootstrap

**Comment by defields923** [comment]
@aslepiak 's solution no longer works. 'trigger' is not a property that can be globally configured, and neither is 'enable.' A very big disappointment for me, since it looks like I will have to add the tooltip-enable or tooltip-trigger attributes to every since use of the tooltip across the site. Does anyone have another global solution?
