### ISSUE TITLE
datepicker: watchers count

### ISSUE THREAD

**Issue by porjo** [angular-ui/bootstrap#2613]
I've been looking at ways to improve performance in my app. I've read that reducing number of unnecessary watchers is something that can help.

Using a simple [watch counter](http://stackoverflow.com/a/19071095) I see that the number of watchers increases by 296 when a datepicker is introduced into the page. See this [plunker](http://plnkr.co/edit/pDTyIq4STsXoAmUkxfog?p=preview) for a demo. AFAIK this is due to the html template using ng-repeat to create the table of days.

Some questions:
1. Is this a real issue i.e. is my analysis correct?
2. If it is a problem, can anything be done?

**Comment by YaManicKill** [comment]
I was looking into this problem (because we have it too).

One solution would be to do an ng-if on the popup. My thought was to have it just do ng-if="isOpen", but that doesn't work as it loses the data stored in the model then, for some reason.

The other option is to create another variable that a user can pass in to say when they want it to be initialised. This would be bound to ng-if and would mean that once it is opened the first time, it is brought into the html and the watchers are assigned.

This would help people who have multiple, as it ends up being a big problem.

However, when trying to do it, I have 5 tests failing. I reckon these are because of the slight performance hit that you get when using ng-if meaning that the popup isn't ready for when it tries to click a date. I'll work on this a bit later tomorrow, but it's at least something that *can* be done.

**Comment by RobJacobs** [comment]
@YaManicKill See this pull request for the ng-if implementation: https://github.com/angular-ui/bootstrap/pull/1915

**Comment by YaManicKill** [comment]
Ah, yeah that's exactly what I was working on. Any plans to actually merge it in?

**Comment by daric81** [comment]
+1
Is there any update on this?

**Comment by karianna** [comment]
https://github.com/angular-ui/bootstrap#impt---2015-plans-and-angular-13-support

**Comment by cpaof** [comment]
+1
28212 watchers for me ;)

**Comment by RobJacobs** [comment]
There's simply too many watchers on the templates.  Doing a quick look through of the popup.html, the ng-repeat that is building the day/week/cell grid, for each day displayed: id={{dt.uid}} = 1 watch, aria-disabled={{!!dt.disabled}} = 1 watch, ng-class="{'btn-info': dt.selected}" = 1 watch, ng-class="{'text-muted' : dt.secondary = 1 watch, {{dt.label}} = 1 watch which adds up to 5 watches per cell in the grid.

**Comment by cpaof** [comment]
@RobJacobs I decided to create a monkey patched version of the bower library in the end. My use case was the date picker to appear on focus of the input field where the suggested `ng-if` would not work.

https://github.com/cpaof/bootstrap-bower for anyone that's interested.

**Comment by wesleycho** [comment]
We are planning on tackling the performance issue with the datepicker once we release 0.13.0.

**Comment by chrisirhc** [comment]
Looking into this issue and looks like https://github.com/angular-ui/bootstrap/pull/2619 adds 40 watchers on the typical use case, even if no custom class was provided.

**Comment by Foxandxss** [comment]
I think we can continue in #3770
