### ISSUE TITLE
Request interceptor cause ui.bootstrap.tpls request modal base templates from server

### ISSUE THREAD

**Issue by milsosa** [angular-ui/bootstrap#2623]
I included bootstrap.tpls and have a request interceptor but when I call $modal.open all the modal base templates are requested from the server. If I remove the request interceptor the modal works well.

![image](https://cloud.githubusercontent.com/assets/1887888/4016352/78a9f4fa-2a33-11e4-95be-972f3aed69f2.png)

**Comment by wesleycho** [comment]
I'm wondering, is this potentially a problem better handled by Angular?

I am not sure whether this is really a UI Bootstrap problem. A simple workaround is to check $templateCache as shown [here](http://plnkr.co/edit/Cq5BK4z7YzelSBNPQvPb?p=preview).

Otherwise, this is not really a problem with UI Bootstrap.
