### ISSUE TITLE
datepicker does not work with model getter/setter

### ISSUE THREAD

**Issue by uazure** [angular-ui/bootstrap#2661]
I try to use datepicker in that way:
`<datepicker ng-model="model.fromDate" ng-model-options="{ getterSetter: true }" ></datepicker>`
having `$scope.model.fromDate = function(value) {};`

I got error like this:
`Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date.`

datepicker directive should allow model to be getter/setter function

**Comment by yankee42** [comment]
Even if you use getter/setter you somehow need a date. So `$scope.model.fromDate = function(value) {};` does not return a date. Have you tried e.g. `$scope.model.fromDate = function(value) {return new Date()};` ?

**Comment by yankee42** [comment]
But there is another problem which prevents gettersetter from working correctly:

If a user inputs a date, but the date is not valid (yet), then the date formatter will parse the value to `undefined`:
https://github.com/angular-ui/bootstrap/blob/82cb637dd12288d9fa0d42783f672fc71b94ffda/src/datepicker/datepicker.js#L562
https://github.com/angular-ui/bootstrap/blob/82cb637dd12288d9fa0d42783f672fc71b94ffda/src/datepicker/datepicker.js#L567

That is a problem, because the angular example on how to implement setter/getter:
https://docs.angularjs.org/api/ng/directive/ngModelOptions
forsees the usage of `undefined` to determine whether the value is being set or only get. Thus the example setter/getter looks like this:

```JavaScript
function(newValue) {
  return angular.isDefined(newValue) ? (value = newValue) : value;
}
```
The problem now is that the datepicker tries to /set/ the value to undefined which does not work. Thus the date field retains it's original value and cannot assume (not even temporarily) an empty value.

I tried replacing `undefined` with `null` in the two locations linked above and then everything looks fine.

**Comment by pkarikh** [comment]
I have the same issue with typeahead.

**Comment by wesleycho** [comment]
Closing in favor of #4837.
