### ISSUE TITLE
Modal 'windowClass' broken in 0.11.0

### ISSUE THREAD

**Issue by gregtzar** [angular-ui/bootstrap#2696]
After upgrading from 0.8.0 to 0.11.0, the windowClass string that I pass to the $modal.open() method is no longer added as a window class, but is instead added as the value of a new window-class attribute. This is a regression from previous functionality, and it also goes against what the documentation says about how it should work, eg: "windowClass - additional CSS class(es) to be added to a modal window template"

**Comment by jci-yarora** [comment]
I am also seeing the same issue using 0.11.0 version. Adding windowClass parameter is simply adding a custom attribute with the value as the class name you want to add. I had to use custom attribute selector in css to access that to make it work. Just pointing it out as the documentation doesnt say so

**Comment by naveenraina** [comment]
I am using 0.13.0 version and I also faced this issue. However after comparing my templates with the the this version, it seemed I had not updated the templates lately and it was because of the old templates which was causing the bug. After replacing window.html with the one in https://github.com/angular-ui/bootstrap/tree/master/template/modal, this issue was gone.

**Comment by gtczap** [comment]
@naveenraina Brilliant! That would actually explain why I was unable to reproduce it in plnkr, because the latest templates were contained in the import.

**Comment by naveenraina** [comment]
@gtczap thanks, hope it helps others facing this issue as well.

**Comment by jci-yarora** [comment]
@naveenraina - Thanks man, that helps. I will be changing the template now.
