### ISSUE TITLE
ui-tabs: styling issues with jquery flot inside tabs

### ISSUE THREAD

**Issue by bhajunsingh** [angular-ui/bootstrap#2765]
As per the following stackoverflow question:

It appears that ui-tabs affects the rendering of flot tick labels while standard bootstrap tabs do not.  

Bootstrap: http://jsfiddle.net/TDwGF/614/
UI Bootstrap: http://jsfiddle.net/TDwGF/615/

I also notice a slightly different misalignment issue (seen in the image in this stackoverflow question: http://stackoverflow.com/questions/25632543/ui-bootstrap-with-flot-causing-misaligned-ticks) also using flot with ui-tabs, but was unable to reproduce that exact issue in a minimal example.  It also functions perfectly in standard bootstrap tabs.

Using:
angular 1.2.22
jquery 0.11.2
bootstrap 3.1.1
flot 0.8.3
angular-bootstrap 0.11.2

**Comment by wesleycho** [comment]
I recreated this in Plunker [here](http://plnkr.co/edit/mvnFlrzzwDNv29e4tsdC?p=preview) so we can debug this more clearly in the event that there is something we can do in UI Bootstrap.

**Comment by wesleycho** [comment]
Investigating a little, it looks like this is due to the tab component rearranging the DOM - a simple fix to account for that is this little setTimeout hack, as demonstrated [here](http://plnkr.co/edit/Q7Edy5R8HQ9SggrjY14Q?p=preview).

There is not much we can do here, as the custom directive is running before the DOM is set, so I am closing as a support ticket.
