### ISSUE TITLE
$modal leaking DOM

### ISSUE THREAD

**Issue by mohuk** [angular-ui/bootstrap#2875]
Hey 

I created a simple app in which I open and close a modal. I realized with the three snapshot technique that the DOM is leaking. Here are the versions that I am using:

Angular JS: 1.3.0
Bootstrap: 3.2.0
UI-Bootstrap: 0.11.0

Here is a plunkr: http://plnkr.co/ByyPqhb1msBPi2Vw8dPj
![dom-leak](https://cloud.githubusercontent.com/assets/3163551/4748952/035b5318-5a7d-11e4-8335-9c529025ce5a.png)

Please let me know if I am doing something wrong or is it angular/angular-ui leaking the DOM?

Thanks

**Comment by kether667** [comment]
+1

**Comment by wesleycho** [comment]
I did an investigation with an [updated Plunker](http://plnkr.co/edit/dhWJmzFlqGPdhXDyndPC?p=preview), and this is still an issue in `master`.

**Comment by chrisirhc** [comment]
Checking the Retainer tree reveals that this is due to ngAnimate storing a reference to the DOM element. It could be that we're (probably my fault) using $animate wrongly.

<img width="1532" alt="screen shot 2015-08-01 at 11 52 18 am" src="https://cloud.githubusercontent.com/assets/132584/9023142/2bd8f340-3844-11e5-974f-405d406dbe0e.png">

Disabling animations indeed removes those leaked nodes. ([Plunker with disabled animations](http://plnkr.co/edit/6SEmPRjXuuJVlaU2FxEz?p=preview))

On further thought, this might be due to ngAnimate not being aware of the removal of the node.

**Comment by chrisirhc** [comment]
Using `$animate.leave` instead of `.remove()` seems to solve this issue.
[Plunker](http://plnkr.co/edit/006CQ5FnEusR3mS4casM?p=preview)

**Comment by mohuk** [comment]
thanks a lot guys .. its great to see progress on an issue opened long before. :+1:
