### ISSUE TITLE
Typeahead use bind-html-unsafe

### ISSUE THREAD

**Issue by albertein** [angular-ui/bootstrap#2884]
The typeahead directive uses bind-html-unsafe for the template of matches, https://github.com/angular-ui/bootstrap/blob/master/template/typeahead/typeahead-match.html.

The property on the directive doesn't indicate on any way that it can be dangerous, it should either:

  a) Remove html-bind-unsafe entirely 
  b) Having typeahead use html-bind-unsafe should be a parameter set explicitly.

I would be happy to do any of those.

**Comment by fernando-sendMail** [comment]
Hello:
I found this issue too, and since I need to create a workaround for this I want to work out this this weekend. Is anybody working on this currently or is it done yet?

If not, let me know so I can do it, and do a pull request.

On a side note I've never made a contribution, do you have any additional guidelines besides the ones posted on github, say for this project in particular?

Thanks for your time!

**Comment by karianna** [comment]
Nothing special, except for make sure it's covered by tests :-) go for it!

**Comment by nschloe** [comment]
This is also popping up for our project; a fix for this would be appreciated. :)

**Comment by erik-slack** [comment]
Same here.

**Comment by Frondor** [comment]
bindHtmlUnsafe is now deprecated. Use ngBindHtml instead (Google Chrome console warning)

**Comment by andrzejpiasecki** [comment]
Same here.

**Comment by kikar** [comment]
+1

**Comment by bambooyzj** [comment]
same here

**Comment by wesleycho** [comment]
This is now removed in `master`, and should be resolved in the next update.
