### ISSUE TITLE
$modal.open should support passing promises into resolves further down the chain

### ISSUE THREAD

**Issue by kfarst** [angular-ui/bootstrap#2900]
An example of this is found here:

http://plnkr.co/edit/tZJ2OYL8HonogATzlTiU?p=preview

Opening web inspector and clicking the 'Open me!' button will show the following error in the console:

```
 Error: [$injector:unpr] Unknown provider: fooProvider <- foo
errors.angularjs.org/1.2.16/$injector/unpr?p0=fooProvider%20%3C-%20foo
    at angular.js:78
    at angular.js:3705
    at Object.getService [as get] (angular.js:3832)
    at angular.js:3710
    at getService (angular.js:3832)
    at Object.invoke (angular.js:3859)
    at ui-bootstrap-tpls-0.11.2.js:2104
    at Object.forEach (angular.js:330)
    at getResolvePromises (ui-bootstrap-tpls-0.11.2.js:2102)
    at Object.$modal.open (ui-bootstrap-tpls-0.11.2.js:2137)
```

**Comment by default0** [comment]
Just saying I ran into this today, and it's really bothersome because I expected it to work like the UI-router resolves, and it doesn't despite your claims that it ought to.
This is obviously because the ui-router is actually smart enough to figure out certain types of dependencies between the promises, while the modals are not able to do that.
Since your stated intention was to have these two behave identically, I think you should remove the "Invalid" resolution and actually make it behave the same, instead of just saying that it should and then having it just not do that.

**Comment by arkin-** [comment]
I've just checked this, after thinking there was still a problem, there is not.
