### ISSUE TITLE
Support for Bootstrap 3.3.0 

### ISSUE THREAD

**Issue by adben** [angular-ui/bootstrap#2910]
What are the plans for support Bootstrap 3.3.0?: http://blog.getbootstrap.com/2014/10/29/bootstrap-3-3-0-released/

**Comment by AdamBuczynski** [comment]
Bootstrap 3.3 also seems to have some additional glyphicons which are not present in angular-ui/bootstrap. I've tried the following, but they don't work:

````
glyphicon glyphicon-triangle-right
glyphicon glyphicon-triangle-left
glyphicon glyphicon-triangle-bottom
glyphicon glyphicon-triangle-top
````

Possibly more are missing.

**Comment by krnlde** [comment]
Hey guys. Since it's two month without any commit or any progress on this issue I wanted to kindly ask how this is being held. What are the problems, who addresses them, who solves them, who tests them? Bootstrap 4 is on its way - if we wait a little longer this task will be obsolete and so is the work that is already done. We have a lot of issues in stackoverflow that are a pita to fix at the current state.

How can I help you guys? The progress, at least for me, is too slow in this project.

**Comment by krnlde** [comment]
Bump

**Comment by realityking** [comment]
@krnlde Are there any issues you're seeing with Bootstrap 3.3? We've been using UI Bootstrap together with Bootstrap 3.3 since October without any issues.

**Comment by krnlde** [comment]
Yes I do. Even if they are not directly correlated to the 3.3 version.
> We have a lot of issues in stackoverflow that are a pita to fix at the current state (example).

Why is this issue still open and what is the "investigation" that is needed?

**Comment by realityking** [comment]
I'm not running this project, so no idea why it's still open.

I don't doubt there are a lot of issues. I'm facing several of them myself. I was wondering if you have any issues *specific to Bootstrap 3.3*. Because I'd like to fix them since we're running with Bootstrap 3.3. Any other bugs are off topic for this issue.

**Comment by krnlde** [comment]
Of course there are. Example: `placement="auto right"`doesn't work as [documented](http://getbootstrap.com/javascript/#tooltips-options) for tooltips and popovers.

**Comment by RobJacobs** [comment]
I have been running the Bootstrap 3.3 (css only) version against this library for quite some time with no issues.

**Comment by krnlde** [comment]
Of course CSS only, because the JS provided by bootstrap is (most of the times) useless in an angular environment.

**Comment by RobJacobs** [comment]
@krnlde I realize that, you realize that, but others may not so I wanted to add that disclaimer.

**Comment by krnlde** [comment]
But you agree it is an issue that @realityking asked for.

**Comment by krnlde** [comment]
Another pita would be that there is no consistent solution to add a simple close button to popovers. Because of the scope isolation and the data hiding policy this library is following, it is not possible to trigger either the close handler of the opener element or to call `hide()` directly anyhow. All solutions out there want me to not use your lib and instead use another library which firstly has nothing to do with your implementation anymore and secondly has nothing to do with bootstrap. I more and more drift apart from being agile and lean thanks to the all-praised "angular way".

**Comment by realityking** [comment]
@krnlde I don't want to pick a fight, but those are feature requests. Not bugs. Configuration for behaviors frequently works different than in Bootstrap + jQuery. UI Bootstrap has huge issues, mainly due to it not being maintained for a while.

That said, I missed #2925 which appears to be an issue with Bootstrap 3.3. Apparently the only one.

**Comment by krnlde** [comment]
I don't want to pick a fight either, sorry if I came across like that. I want to solve this stuff since I rely on the library and you guys, and these issue really hurt my feelings. You asked me to point out issues, and it is an issue when the so called bootstrap-ui is not the same as bootstrap especially when it uses the exact same CSS, so that it seems it really likes to be the same.

**Comment by krnlde** [comment]
I created an own [issue](#3906) for the close button.

**Comment by wesleycho** [comment]
Please open tickets for any issues you find - putting each one in a catchall issue is not the way to properly get them addressed, as it makes issue tracking a nightmare.

**Comment by icfantv** [comment]
closing per above comments.  please create a separate issue for any issues found.

**Comment by wesleycho** [comment]
This issue is fine for informing our plans for 3.3 support. I meant specific issues should be in new issues.

**Comment by icfantv** [comment]
My bad.  Sorry.

**Comment by wesleycho** [comment]
It appears that all of the outstanding 3.3 issues are addressed currently - closing this issue as I believe we are now supporting it fully.

If there are any issues with 3.3 specific CSS related problems, please open a new ticket.

Thanks all!
