### ISSUE TITLE
datepicker - Invalid date manually input is correctly detected in chrome but not in Firefox or IE.

### ISSUE THREAD

**Issue by fortesl** [angular-ui/bootstrap#3037]
for example entering date '50/12/2014' is detected as an invalid date in chrome as it should, but not in ie or firefox. Sample input tag shown below:

input type="text" class="form-control" datepicker-popup="MM/dd/yyyy" ng-model="ngModel" is-open="opened" close-text="Close" show-weeks="false" placeholder=""  ng-required="true"

**Comment by jmayday** [comment]
Do you use the datepicker as a forms control? Did you check how the form field looks like by printing it as json? (<pre>My date object is: {{ myform.mydate | json }}</pre>). 

Please do so and observe the model value. Probably it was parsed as "Monday, February 12, 2018" (exactly like here http://angular-ui.github.io/bootstrap/#/datepicker).

I just commented on other issue (https://github.com/angular-ui/bootstrap/issues/3104) so just check it at the evening - I'll share my approach how to handle this problem.

**Comment by karianna** [comment]
plunkr showing the problem please.

**Comment by jmayday** [comment]
http://plnkr.co/edit/yNuSZPiQYFn0Zy2COPdA

**Comment by jmayday** [comment]
PR created: https://github.com/angular-ui/bootstrap/pull/3288
Please review.

**Comment by rapmue** [comment]
I found also something interesting today. Maybe it's the same place to search the problem.

Using the newest version (0.13.0)

If you select a date format other than yyyy-mm-dd and your date input numbers aren't zero padded, the date is parsed wrong in Chrome. In InternetExplorer and Firefox it's not parsing at all, doesn't matter if with padding zeros or not.

Example: http://plnkr.co/edit/9TzjocE0P8F9gD7OwPoH?p=preview

Select date format dd.mm.yyyy and take as example today:

Chrome
input -> 8.5.2015
expected -> 2015-05-08
output -> 2015-08-05

input -> 08.05.2015
output -> 2015-05-08 as expected

Firefox
input -> 8.5.2015
error -> "Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date."

IE
input -> 8.5.2015
no output or error
