### ISSUE TITLE
datepicker can't react on changes of $locale

### ISSUE THREAD

**Issue by sclausen** [angular-ui/bootstrap#3050]
if $locale changes (eg with [angular-dynamic-locale](github.com/lgalfaso/angular-dynamic-locale)) the locale doesn't affect the datepicker. Its, because the popup is initially rendered and doesn't react on any $locale changes.
There should be an eventlistener for locale changes or something which should redraw the popup.

**Comment by DieterLi** [comment]
We really need a good solution for this, because our users are multilingual ones. Please help, thanks.

**Comment by rvanbaalen** [comment]
Feel free to help out and submit a PR, @DieterLi.

**Comment by DieterLi** [comment]
@rvanbaalen Thanks for the suggestion, I will give it a try , and here what I got for the localisation with a good idea: angular-dynamic-locale, https://github.com/lgalfaso/angular-dynamic-locale. It can change the locale dynamic without inject any javascript into html page, quite fantastic.

Unfortunately, since ui.bootstrap 0.11.0, the new mechanism for datepicker popup, it only works for the version under 0.10.0. 

Hope more guys could help in this issue. And I'm still working on it to find a way out.

**Comment by DieterLi** [comment]
@rvanbaalen Althought I didn't submit a PR for the issue. But I did find a solution for this, which is quite brilliant, and can do the dynamic locale switch with little efforts on codes, suiting for all versions of ui.bootstrap.

It's angular-dynamic-locale, https://github.com/lgalfaso/angular-dynamic-locale. And the plunker for reference: http://plnkr.co/edit/SriQrUbqzbDzfIaeyeO8?p=preview

Great thanks to @lgalfaso. 

And since Chrome has already supported the HTML5 date input tag, with its own popup datepicker. Don't get confused on Chrome one with the one from ui.bootstrap.

**Comment by MalteFabian** [comment]
@DieterLi Some comments in your Plunker would be very helpful. I don't get where the $localeChangeSuccess event is fired. It wasn't simple to find the scope.move method (ui.bootstrap, datepicker directive), either.

**Comment by DieterLi** [comment]
@MalteFabian Please refer to this git repo: https://github.com/lgalfaso/angular-dynamic-locale, in line 112 of the source, you can find $localeChangeSuccess is broadcasted.

And as to "scope.move(0)", I think it's in the mechanism of AngularJS decorator function, which will be injected during the directive being compiled. While not a ui.bootstrap.datepicker scope, but a general scope under directive compile context  in AngularJS.

The above is my superficial understanding, because the whole solution was provided by the owner of angular-dynamic-locale, as the above git link.

**Comment by wesleycho** [comment]
I'm a bit confused as to the resolution here - is this workaround sufficient for getting around this issue completely?

**Comment by wesleycho** [comment]
This is now addressed via https://github.com/angular-ui/bootstrap/commit/d9a521a4e5328ad9d231b086092ecf0408061ef9
