### ISSUE TITLE
Purpose  feature :fire event before after tab shown  or hide

### ISSUE THREAD

**Issue by DarkmanMuMoo** [angular-ui/bootstrap#3082]
I found bootstrap tab.js in jquery version have a event support like below
hide.bs.tab (on the current active tab)
show.bs.tab (on the to-be-shown tab)
hidden.bs.tab (on the previous active tab, the same one as for the hide.bs.tab event)
shown.bs.tab (on the newly-active just-shown tab, the same one as for the show.bs.tab event)

It must be good if angular version of tab have implement this 

As i know we can use $emit and $broadcast to fire event and pass information in eachstate

sorry for my Eng

**Comment by wesleycho** [comment]
Eventing does not provide a good API interface to work with, especially considering that Angular is about observing model values for changes and reacting to them. We have `select` and `deselect` callbacks that can be bound to.

Closing this as something we are not interested in supporting in its proposed form.

**Comment by DarkmanMuMoo** [comment]
I agree with you, but In my use case i need to check some thing just before the tab is active. Not sure select ,deselect call back support this (since i was try it  in  version 0.11 )

**Comment by wesleycho** [comment]
Can you explain your use case more in detail as to why you would want to check it before it is active, as opposed to the `before-select` callback?

**Comment by cihadturhan** [comment]
Hi, sorry for bumping this issue. I understand why it doesn't provide a good interface especially for Angular, but I must definitely know that the content of the selected tab is visible because I'm adding a chart to the tab content.

What I'm asking is, could you point me a workaround which helps me ensure if tab content is visible. I'm planning one of the methods below but I wonder if any of you have a better solution to this

- set a timer with a safe duration (say 100ms) to ensure tab is visible
- periodically check (such as 50ms interval) if tab content is visible

Thanks

**Comment by wesleycho** [comment]
That is a question better suited for StackOverflow - I would try to set a $watch on the active property of a tab and use a setTimeout there if I wanted to work around something like that.

**Comment by cihadturhan** [comment]
Thanks @wesleycho, I ended up with setting a timeout even though it's quick and dirty solution.
