### ISSUE TITLE
datepicker doesn't work with angular 1.3

### ISSUE THREAD

**Issue by tamtakoe** [angular-ui/bootstrap#3089]
http://plnkr.co/edit/zOB0A7TC8JN8yGQ59wE6?p=preview

**Comment by shilan** [comment]
the datepicker-options doesn't work in new release.
the options is undefined at line 1522, here:
      if ( attrs.datepickerOptions ) {
        var options = scope.$parent.$eval(attrs.datepickerOptions);
        if(options.initDate) {
          scope.initDate = options.initDate;
          datepickerEl.attr( 'init-date', 'initDate' );
          delete options.initDate;
        }
        angular.forEach(options, function( value, option ) {
          datepickerEl.attr( cameltoDash(option), value );
        });
      }

**Comment by harm-less** [comment]
I've the same problem as @shilan. It happened when I was migrating to 1.13.0 (and Angular 1.3 of course). 
It's weird because the `scope.$parent` has the object it is looking for and `attrs.datepickerOptions` has the same name of that object.

Is it perhaps a problem of the $eval method in 1.3?

Btw, I don't think #2659 is a duplicate of this issue.

**Comment by shilan** [comment]
Yes you are right, as soon as I add this datepicker-options="{{dateOptions}}" it works, and of course I have dateOptions in $scope like this:

  $scope.dateOptions = {
    formatYear: 'yy',
    startingDay: 1
  };

However I still have problems with datepicker-options="yyyy-MM-dd"
It does not work properly with this format! strange!
