### ISSUE TITLE
Add ability to manually hide tooltips

### ISSUE THREAD

**Issue by jasonsavage** [angular-ui/bootstrap#3114]
Currently, in the application I'm working on, I've re-implemented the $tooltip directive like you have done with ui.popover so that it can use it to display validation errors. 

The client wants a little "x" in the top corner of the popup so that it can be closed either by clicking the error icon again or by clicking the "x". With this change, there doesn't seem to be anyway to manually close a popover, except to trigger a 'click' event on the icon when the user clicks the "x".

![example](https://cloud.githubusercontent.com/assets/930252/5459460/303199f2-8529-11e4-8dc0-b73dfc131ad8.png)

**Comment by jivinivan** [comment]
:+1: This would be useful.

**Comment by jgdenoo** [comment]
:+1: Same for popover please

**Comment by wesleycho** [comment]
The tooltip now comes with support for programmatic triggers, as can be seen in the documentation [here](http://angular-ui.github.io/bootstrap/#/tooltip).

However, it should be noted that you should probably be using a popover for this purpose, not a tooltip, since tooltips are strictly text only (along with a wrapper element).
