### ISSUE TITLE
Datepicker invalid week numbers

### ISSUE THREAD

**Issue by bolemeus** [angular-ui/bootstrap#3120]
I've set the first day of my datepickers to 1, meaning the weeks start on monday.

I'm encountering a strange bug now though. December of this year (2014) shows a full week of January (5-1 / 11-1). The datepicker also says this is week 54. The week before that is week 53 according to the datepicker. These weeks should be week 1 and 2.

![image](https://cloud.githubusercontent.com/assets/1689125/5474760/1d6b5e7a-8614-11e4-87db-a6433787c2ba.png)

Even stranger behaviour is when I check out December 2015 and January 2016.

![image](https://cloud.githubusercontent.com/assets/1689125/5474800/43c7fc86-8614-11e4-954a-e8e25165c5c2.png)
![image](https://cloud.githubusercontent.com/assets/1689125/5474808/52d21df6-8614-11e4-8223-2a175c8ff4f8.png)

The numbering of weeks is wrong. The numbering is correct again in February 2016. I haven't checked out more years, but I'm guessing thesame problem arises...

**Comment by brentmiller** [comment]
I confirmed this bug in the following environment:
* Angular Bootstrap version 0.12.0
* Angular version 1.2.19
* Chrome 39 (in addition to IE 11)
* Windows 7

**Comment by picodealion** [comment]
An additional problem with this is that even the week numbers in December are wrong. According to multiple sources 2014's week 52 was the week that started with December 22 (or December 21 if you start on Sundays). The week numbers are off by +1.

All this was already covered in https://github.com/angular-ui/bootstrap/issues/2506, it seems a fix for that issue was already committed but the guy never updated his code after review feedback was provided. I will look into this tomorrow and update the pull request.

**Comment by picodealion** [comment]
A fix for the starting day that PR references had already been made in the meantime, I added fixes for the January week numbers  and adjusted the algorithm to remove the wrong offset in all week numbers. New PR here: https://github.com/angular-ui/bootstrap/pull/3158
