### ISSUE TITLE
datepicker re-rendering doesn't work properly

### ISSUE THREAD

**Issue by itkin** [angular-ui/bootstrap#3124]
When re-rendering an input with the datepicker-popup directive, ui-datepicker doesn't seem to take into account the previously selected model value.

Please take a look to [this plunker](http://plnkr.co/edit/7JDJhacNMMOpVuLLzYSM?p=preview), pick a date, then toggle the checkbox two times to remove and recreate the datepicker form field. 

You'll notice that the form field value changed (date formatting is lost), which to form validation issues

Opened a [stackoverflow question](http://stackoverflow.com/questions/27460550/re-rendering-angular-ui-boostrap-datepicker-inconsistency)

**Comment by fitefoe** [comment]
@hamfastgamgee thanks for the fix! Maybe you can prepare a pull request?
Would be great to have the fix in the official repository.

**Comment by hamfastgamgee** [comment]
Finally figured out how to get git all set up on my side.  Yay for corporate firewalls.  I've submitted a PR with the "if" check, but it turns out angular 1.2 "worked" without that (in that it "failed" but immediately auto-recovered in a way that angular 1.3 doesn't).

The PR does *not* fix the datepicker to be fully 1.3-compliant.  I may have some time to help with that as well, but not necessarily immediately.

**Comment by wesleycho** [comment]
This has been fixed by 2c2dba6d145c95500efe7f6be6248d56ae1aebee.
