### ISSUE TITLE
"Take what you need and no more" for bower

### ISSUE THREAD

**Issue by hgoebl** [angular-ui/bootstrap#3139]
It would be nice to have single js files of each module when using bower.

I'm using `<!-- build:js js/bc.js --> ... <!-- endbuild -->` with **grunt-usemin** and reference only used modules, so it doesn't help so much when bower fetches all-containing ui-bootstrap.js.

Thanks for your work BTW.

**Comment by richardTowers** [comment]
I was also surprised by this. For now I'm pointing bower at this repository so that I can point directly at the dropdown directive (which is the only one I need).

bower.json looks like this:

```json
{
  "name": "Example",
  "dependencies": {
    "angular": "1.2.27",
    "angular-bootstrap": "https://github.com/angular-ui/bootstrap.git#~0.12.0"
  }
}
```

It might be nice if [angular-ui/bootstrap-bower ](http://www.github.com/angular-ui/bootstrap-bower) contained a components folder with the individual directives as well as the compiled versions to support this use case. If the authors are interested I'd be happy to put together a PR for that.

**Comment by hgoebl** [comment]
I don't understand why there is a special github project for this. Should be sufficient to use bower.json with excludes or a list of files to be included IMO.

**Comment by pkozlowski-opensource** [comment]
@hgoebl there needs to be specific bower repository since:
* bower doesn't have its own repository where we could upload deliverable from the build process
* we don't want to check-in build results in this repo (we've been there, it is nightmare to manage)

So, if you want to grab individual files point your bower thing to this repo. If you need build results than use https://github.com/angular-ui/bootstrap-bower. I'm afraid that we don't have individual bower-specific repos for build results of each directive.

**Comment by kcaron-cst** [comment]
This was working great under bower using the

```
"angular-bootstrap": "https://github.com/angular-ui/bootstrap.git#~0.13.3"
```

trick in bower.json. However I am trying to accomplish this with NPM now. This would work great except `src` is in the `.npmignore` file, so it effectively kills this hack. I understand this use case is fringe but I would be thrilled if the src directory was exposed to NPM.

Can open a new issue if this gets any traction, but being so similar to the bower issue, I figured I'd post here.
