### ISSUE TITLE
mode selection on multiple datepickers

### ISSUE THREAD

**Issue by trickpattyFH20** [angular-ui/bootstrap#3185]
http://plnkr.co/edit/PJdi08mcHwYyX8Ibf6DA?p=preview
1) open both datepickers
2) chose a year for one of them

The current selection mode changes for both datepickers, this problem also occurs after choosing a month or any other mode of selection.  Any idea what the problem is or how to work around it? Is my configuration wrong or is this a bug?

**Comment by antoinepairet** [comment]
Somehow, both directive instances share the same `datepickerMode`. As far as I understand, your config is OK and you hit a bug. After a first look, minDate and maxDate might also be impacted.
Notes for myself: https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L481 and https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L494 should be investigated.

**Comment by antoinepairet** [comment]
Actually, it's your config which is wrong. You messed up with quotes and the `datepickerMode` attribute. You in fact created a scope variable named `year` which coupled the `datepickerMode` of both directive instances.

Your config should have been:
````
datepickerMode="'year'"
````

instead of
````
datepickerMode='year'
````


Here are 2 working plunkr:

http://plnkr.co/edit/dpRgWJaaYDFK0jNyHBWt?p=preview
http://plnkr.co/edit/YZQuNdgmnc2ChulHePpt?p=preview

**Comment by trickpattyFH20** [comment]
<3 ui-bootstrap!!! TY @antoinepairet !!!
