### ISSUE TITLE
Tooltip is hidden if parent element have scrollbar

### ISSUE THREAD

**Issue by augustas2** [angular-ui/bootstrap#3194]
Problem is that using tooltip in parent element which have vertical scrollbar, tooltip gets cut if it doesn't fit...

Solution should be use fixed position, but JS should get currently hovered tooltip element position. Any ideas solving this one?

See image...

![example](https://cloud.githubusercontent.com/assets/7789787/5758622/8b1ed132-9ccf-11e4-925d-84c73cd598fc.png)

**Comment by karianna** [comment]
Can you supply a plunkr showcasing this problem?

**Comment by wesleycho** [comment]
The problem here is that the implementation puts the tooltip next to the DOM element it is providing contextual information for - this differs from Bootstrap's JS where it puts the tooltip globally to avoid this sort of clipping problem.

The proper solution may end up meaning that we need to refactor the tooltip to allow it to append it to the body element instead & manage a stack similar to the modal (maybe abstract the modal's stack logic).

**Comment by wesleycho** [comment]
It should be noted that to support this may cause a problem when it comes to accessibility.

**Comment by RobJacobs** [comment]
Tooltip will accept tooltip-append-to-body: https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/tooltip.js#L123

**Comment by icfantv** [comment]
@augustas2, as @RobJacobs mentions, this problem should be solved by using the `tooltip-append-to-body` attribute.

I'm going to close this, but please feel free to reopen and attach a working plunker that demonstrates the problem if it is not solved.  Thanks.
