### ISSUE TITLE
Bootstrap default alert styling not applied

### ISSUE THREAD

**Issue by fiznool** [angular-ui/bootstrap#3304]
There are some styling rules in the bootstrap stylesheet that aren't applied, due to the way that the alert module uses transclusion.

For example:

``` less
.alert {
  // Improve alignment and spacing of inner content
  > p,
  > ul {
    margin-bottom: 0;
  }

  > p + p {
    margin-top: 5px;
  }
}
```

The child `>` selector doesn't work as the alert markup resembles:

``` html
<div class="alert alert-danger alert-dismissable">
    <button ng-show="closeable" type="button" class="close" ng-click="close()">
        <span aria-hidden="true">×</span>
        <span class="sr-only">Close</span>
    </button>
    <div ng-transclude="">
        <p>Validation failed</p>
    </div>
</div>
```

**Comment by karianna** [comment]
plunkr please

**Comment by fiznool** [comment]
http://plnkr.co/edit/CgEqt9sCzoe2K8cUJhsV?p=preview

**Comment by RobJacobs** [comment]
@fiznool You are correct the transclude div is wrapping the alert content and those css selectors are direct descendant selectors.

**Comment by fiznool** [comment]
It looks like it is fairly straightforward to replace the transcluded element with the contents, but some custom work needs to be done.

As per [this SO post](http://stackoverflow.com/questions/21092885/how-to-replace-the-element-with-ng-transclude), there are a couple of ways to achieve the goal:

- Add some code to the existing alert link function to find the transcluded element and perform the transclusion manually.
- Create a new directive which mimics `ngTransclude`, but replaces the element rather than appending to it.

I prefer the second option, particularly due to the fact that the alert template is configurable - the brittle nature of the first option will stop working if the template is changed. I can look into adding this in and submitting a PR, but I'm unsure where the new directive should live, and what it should be called. Does ui-bootstrap have a dependency on ui-utils?

**Comment by RobJacobs** [comment]
I was thinking the easiest fix would be to change the transclude element in the template from a div to a p.

**Comment by fiznool** [comment]
Personally I don't think that's such a great idea, as the transcluded content might not just be text. I'm personally using alerts with h4, ul inside them.

**Comment by rvanbaalen** [comment]
I agree with @fiznool. Using a `p` is not very semantic. What about manually performing the transclusion as said in the SO post?

**Comment by wesleycho** [comment]
I am not sure whether we should support this - the only options we have are

1) Make a breaking change with put ng-transclude at the top level element and remove the close button
2) Create a custom html swapper directive which bypasses sanitization by Angular

The HTML swapping is slowly going away and being replaced with behavior built into Angular itself, so I do not think it is a good idea to go with option 2. The breaking change is also onerous in this case, since many rely on the existing behavior, and the gains are trivial in comparison.

I think that it is trivial to modify the CSS to the user's content with minimal overhead.

I welcome other thoughts on this, but my belief is that the tradeoffs available make this not worthwhile to support.

**Comment by wesleycho** [comment]
I am closing this as the other options are not appealing - in particular, creating custom directives to replace default transclusion is troublesome, as it often involves doing risky things such as appending new DOM elements. The performance overhead does not appear to be worth it, while this is an easy problem to fix on the user's end through custom CSS.
