### ISSUE TITLE
Datepicker input value not updated in html

### ISSUE THREAD

**Issue by Saabertooth** [angular-ui/bootstrap#3305]
This issue pertains to ui.bootstrap.datepicker. The issue is that when using .val() to set the value of the datepicker input field, the value is set in the DOM but not in the html whereas by using .attr() to set the 'value' attribute sets both.

I have what may be a unique situation where I need to extract the html and render elsewhere, causing the value in the DOM to be lost and a blank input to be displayed.

**Comment by karianna** [comment]
plunkr please

**Comment by Saabertooth** [comment]
Here is a plunkr demonstrating the behavior: http://plnkr.co/edit/JLAQ1rAtGJac5qybTuIP?p=preview

I realize my initial comment is a bit cryptic.  The solution I propose is simply:
Use the jqLite .attr() method to set the value of the input instead of .val()

**Comment by wesleycho** [comment]
This works perfectly fine, as demonstrated by [this Plunker fork](http://plnkr.co/edit/ZoaaXXepw5A7QBUrdIqn?p=preview).

There is not much that should be done on UI Bootstrap's side - the data is available in the DOM and the model value, it is up to the developer to make use of their JavaScript to extract the necessary values, since it is something that the developer can control.
