### ISSUE TITLE
Copy-Paste value match with one result in drop-down should be auto-selected if typeahead-focus-first=true

### ISSUE THREAD

**Issue by dimylik** [angular-ui/bootstrap#3310]
By my opinion, if you have typeahead-focus-first=true
and I copy-paste existing item from buffer, and in drop-down result I see the only value with exact name, that value should be pre-selected automaticcaly

http://plnkr.co/edit/9LOkH1zVTTvdlJXN7wct?p=preview

paste 'Arizona' value in the input and click somewhere else on the screen, without Enter or mouse click on drop-down value

value is not preselected, I think should be found

**Comment by dmitriz** [comment]
When I copy-paste "Arizona" and click away - it does remain in the `input` form as it should.

When I do the same with "Ariz", then it also remains "Ariz".
Which seems to be the correct behaviour too as the user might want to come back
to continue typing further rather than have the string jump to something else.
Just my view.
