### ISSUE TITLE
bug(Typeahead): Cannot select item with mouse or keyboard

### ISSUE THREAD

**Issue by wesleycho** [angular-ui/bootstrap#3393]
Currently, the only way to select an item with typeahead and Angular 1.3 is to tab - selecting with the mouse or keyboard does not work.

[Here](http://plnkr.co/edit/4i5qJYlyCrE4bWkvBV20?p=preview) is a plunker illustrating it.

**Comment by antoinepairet** [comment]
The demo in the plunkr uses ui-bootstrap version 0.11 (my fault). 

It actually works using a snapshot build from master:
http://plnkr.co/edit/tVbMKvvFLB6yZG7Qes5o?p=preview


The issue with 0.11 is the usage of`ng-if="isOpen()"` in the default template which creates a new scope. Replacing it by a `ng-show="isOpen()"` fixes the issue since no childscope is created. Master branch now uses `ng-show`:
https://github.com/angular-ui/bootstrap/blob/master/template/typeahead/typeahead-popup.html#L1
