### ISSUE TITLE
Prefix controllers and services

### ISSUE THREAD

**Issue by chrisirhc** [angular-ui/bootstrap#3396]
Just aggregating all the issues that would be resolved when we get to this task. This is related to #157 but not exactly the same issue. We can do this task before we get to resolving #157.

This should be a non-breaking change for majority of users and a minor inconvenience for the few that are depending on the services declared.

Root cause of #3302, #2458, #1753

**Comment by chrisirhc** [comment]
So we've pretty much decided on using a prefix of `uib-` for directives and `uib` for controllers and services.

**Comment by wesleycho** [comment]
would it be `uibAccordionController` then? (as an example)

**Comment by RobJacobs** [comment]
@wesleycho I think the prevailing style guide has controllers named with the leading character capitalized, i.e: UibAccordionController.

**Comment by wesleycho** [comment]
That makes sense.

**Comment by chrisirhc** [comment]
I initially intended `uibAccordionController`, but I'm completely open to this. If there's a prevailing style guide, let's go with it.

**Comment by wesleycho** [comment]
Those who use the older versions should also see a $log message mentioning that the old usage is deprecated. Use of `$compileProvider.directive` and `$provide.factory` (and similar) should be useful for defining the old names.

**Comment by dmitriz** [comment]
Guys, 

Can anyone please update what is the real problem here?

I have nearly broked the leg of my chair from laughing - so true:
https://github.com/angular-ui/bootstrap/issues/1994
:laughing: 

Beside my own issue https://github.com/angular-ui/bootstrap/issues/2581 over half year ago, there is a whole sophisticated network of highly interlinked discussions on that matter. If I could export it to a nice graph diagram, I would sell it to an important art museum :smile: 

This is a top public repo on Github and 2nd to Angular's original one to whoever is using Angular and that issue seems to be most frequently discussed, causing all sort of annoyances, pushing people away from the project and even from Angular. Yet this issue(s) is(are) dragging for over 2 years at least.

Can anyone please explain why and what is it that holds it back and clarify what kind of help is needed?

Any plans to open a branch dedicated to this issue/milestone/nicetohave/annoyingnottohave... ?

**Comment by karianna** [comment]
@dmitriz You can see its been scheduled for 1.0.0.

**Comment by rvanbaalen** [comment]
@dmitriz as said before me it is indeed planned for v1.0.0. The reason we didnt make this a higher than 1.0 priority is mainly due to two things:

- Make it work first. We have hundreds of PRs and issues related to functionality/bugs
- Its a boat load of work as you can imagine. That shouldnt be a reason but given the limited time we all have available to spend on this project, this can be an issue. 

Im confident that this will be tackled in the upcoming months rather than years though. We have a new team of maintainers and lots of issues and PRs are being closed and merged every day now. 

:+1: bear with us!

**Comment by chrisirhc** [comment]
I welcome PRs on this issue to speed things along but be aware that it might need some rebasing later.

**Comment by dmitriz** [comment]
Thanks for the update!

Unless I am overlooking something, a simple job would be:
- Add names to the anonymous functions defining directives.
- Additional prefixed directives declarations linking to those functions.

That would allow both custom prefixed and un-prefixed versions.

Would that not do it? 
Am I too naive? :)

**Comment by chrisirhc** [comment]
This change isn't referring to directive prefixes, which is in #157 . This change is to ensure that controllers, services, constants, anything we declare on the module (except directives) must be prefixed.

For example, in https://github.com/angular-ui/bootstrap/blob/master/src/tabs/tabs.js, the `TabsetController` will now be `UibTabsetController`. Note that the references to the controller, in the `tabset` directive need to be changed as well.

**Comment by RobJacobs** [comment]
Should we try introducing a style guide as well?  [Todd Motto](https://github.com/toddmotto/angularjs-styleguide) and [John Papa](https://github.com/johnpapa/angular-styleguide) have published a couple that do a good job of explaining the how and why of their recommendations.

**Comment by dmitriz** [comment]
Sorry for the confusion and thanks @chrisirhc for clarification (I am sort of lost in the interlinked network :)

## So here is a proposal (hopefully in the right issue :) that looks simple to me:
- Create a dedicated "prefixed" branch for all the work on prefixes.
- Manually add prefixes to all **internal** controllers and services.
- Release prefixed versions as `1.0.x-prefixed-prereleased` or something like that.
- Write clear explanation what this prerelease is and how to use it.

## Am I proposing to maintain two separate releases? 
No! It should suffice to clearly declare it as unstable prerelease meant for folks who know what they are doing. Plus invite them to rebase onto more recent bug fixes and submit PR if they want to.

Occasionally we may rebase and update the release ourselves. I imagine this can be completely automated, e.g. Mr. Travis can do it for us :)

## What about folks who use those controllers in their code?
Since these are not officially documented, that would be again folks who know what they are doing. Probably a small percentage of users. They have the options:
- keep using current version and do nothing;
- switch to the prerelease version and update their code, likely in very few places.

## Further suggestions
- Decide on which controllers and services are encouraged to be used and which are not.
- Document all of them meant for public use.
- Prefix with `$` all the others and state clearly that they are for **internal use**.

**Comment by Foxandxss** [comment]
We will continue in #4373. We decided how to do it and we just need to work on it.
