### ISSUE TITLE
Two digit year returns 20th century in IE but 21st in Chrome

### ISSUE THREAD

**Issue by ajayparsana** [angular-ui/bootstrap#3408]
Hi,
We are setting datepicker-popup to MM/dd/yyyy in bootstrap datepicker. 
Now,If I enter date as 3/3/15 then date is set to 3/3/1915 in calendar in IE11 but it set to 3/3/2015 in chrome.
Please help & let us know how we can fix this for IE11. 

Below is code snippet(please test in IE): 
Step: Enter 3/3/15 in Pop Up field & select Format MM/dd/yyyy.
http://jsbin.com/zuvirebupe/1/

**Comment by wesleycho** [comment]
Doing some investigation, the reason this seems to be an issue is because the format being entered is actually M/d/yy, not MM/dd/yyyy.

This is broken in the current 0.12 release, but is fixed in master currently.

You can see the correct behavior in this updated [jsbin](http://jsbin.com/hobemu/6/edit) based off of a build of current master.

**Comment by wesleycho** [comment]
Closing this as already fixed.

**Comment by AngularJsChamp** [comment]
You can also create custom date picker using bootstrap date picker code

**Comment by ajayparsana** [comment]
Thanks Wesley & AngulaJsChamp!!

**Comment by worldspawn** [comment]
When using the date format provided by angular using the browser language and its en-US this fails. It fails running 1.3.2.

Running `new Date('1/1/98')` doesn't do this (i get 1998, not 2098) so its a function of angular ui??
