### ISSUE TITLE
Add Example/Documentation for collapsing Navbar

### ISSUE THREAD

**Issue by varmint09** [angular-ui/bootstrap#3481]
As per this thread, the following extracts work if added;

http://stackoverflow.com/questions/28667517/angular-ui-bootstrap-respopnsive-navbar-dropdown-not-working-properly-in-new-ver

```
<button type="button" class="navbar-toggle" ng-click="isCollapsed = !isCollapsed" aria-expanded="false" aria-controls="navbar">

 <div class="navbar-collapse collapse in" collapse="isCollapsed" aria-expanded="true">
```

In your controller (Such as NavController); 

```
$scope.isCollapsed = true;
```

Just think its such a useful part of Bootstrap for it to not be mentioned is a waste.

**Comment by blackat** [comment]
Hi,
thanks a lot for the hint, I have looked around a bit and I have notice the problem was not showing with ui-boostrap-tpls version 0.6.0.

May be it is even possible to refer [this plunker](http://plnkr.co/edit/dUGbvnmc089C9rnKFh4f?p=preview) some attributes have been introduced but not documented, moreover no need to add a controller everything smooth on the same line.

It would be cool if you could add a section in the documentation page about navbar, there are a lot of example around but none on your site, this will avoid the use of jquery and boostrap.js by many people.

Have a good day ;-)

**Comment by wesleycho** [comment]
Feel free to file a PR!
