### ISSUE TITLE
there is no build in the project

### ISSUE THREAD

**Issue by zwhitchcox** [angular-ui/bootstrap#3507]
Under installation, all it says is to download the project. It doesn't tell you how to build. I downloaded and included tooltip.js, and added ui.bootstrap to the dependencies, but I get a module error, because it could not find that dependency, so I feel like I'm supposed to include some other javascript file or build it or something.

**Comment by rvanbaalen** [comment]
Im working on improving the README soon. All the information you need should be in the Wiki. Let me know if that helped you.

**Comment by zwhitchcox** [comment]
Ok! Got it. Thanks :)

**Comment by covus-benjamin-schuch** [comment]
You really don't need to update the readme in order to explain how to use grunt, just ship the compiled files like it's normal. If somebody wants to exclude some components from build he can still use a custom build. 

This is really the only library where I have to manually compile from source and I use a lot of libraries.
