### ISSUE TITLE
Tooltip $apply in progress error when using focus trigger

### ISSUE THREAD

**Issue by chrisirhc** [angular-ui/bootstrap#3557]
Reported by @gufigueiredo in #516

> Another scenario:

> If i use tooltip with "tooltip-trigger=focus" and ui-datepicker, same error occurs:

> ```
                    <div class="form-group">
                        <label for="DateField" class="required">Date Field</label>
                            <div class="input-group date">
                              <input name="DateField" type="text" class="form-control" 
                                     tooltip="Choose a date"
                                     tooltip-trigger="focus"
                                     datepicker-popup="dd/MM/yyyy" 
                                     ng-model="vm.DateField" 
                                     is-open="vm.opened" 
                                     show-button-bar="false" />
                              <span class="input-group-btn">
                                <button type="button" class="btn btn-default" ng-click="vm.open($event)"><i class="glyphicon glyphicon-calendar"></i></button>
                              </span>
                            </div>
                        </div>
```

Most likely due to the fact that blur events must be handled with evalAsync.

**Comment by bretkikehara** [comment]
Please let me know your thoughts and if it is good, then I will make a PR! =]

https://github.com/angular-ui/bootstrap/compare/master...bretkikehara:0.13.4

The tooltip should prefer to applyAsync or evalAsync because it doesn't matter if the commands are run on this tick or next tick. We have two cases, 1 where the digest cycle is running and 2 where it is not. If we applyAsync or evalAsync, it ensure the commands are executed without interfering with the digest cycle. Even if the same code is executed in two digest cycles, there isn't any negative side effect.

Why do we need to create the tooltip? Please correct me if I am wrong, but the tooltip should be inserted into the DOM once per "open" trigger and removed from the DOM after "close" trigger. Hence, even if the browser fire multiple "open" triggers, the createTooltip should fail silently as the tooltip is already in the DOM.

**Comment by RobJacobs** [comment]
LGTM a PR off current master would be great.
