### ISSUE TITLE
pagination not working well with angular google maps

### ISSUE THREAD

**Issue by gerlstar** [angular-ui/bootstrap#3594]
I'm currently having an issue where the google maps and pagination does not work well together. I'm also using the accordion in this project. My maps is called when I click on the accordion header. I've tried to remove the pagination and the maps are called when I click on the accordion header. Please take a look in http://jsfiddle.net/gerlstar/7m4oLxo8/ for an example.

**Comment by rvanbaalen** [comment]
To me, this seems like a very specific use case where you need some help wrapping the three directives together. Not sure if this is a bug in the pagination or accordion directive.

https://github.com/angular-ui/bootstrap#need-help

Leaving this open for others to look into since I don't have enough time right now to determine of this should be closed.

**Comment by Balrog30** [comment]
Reading this, "Not working well together" doesn't tell me much.  I checked out your fiddle and was surprised how well you have them working together (there are several common issues with Google Maps and hidden elements, and you seem not to have any of these problems).  Can you describe the undesired behavior in more detail?

**Comment by gerlstar** [comment]
@Balrog30 When it first loads and you click on any of the first 5 locations, the map is displayed. However once you hit either page 2, 3 or 4  and you click on any of the 5 locations, the map is not loaded. The content isnt displayed at all. Hope that explains things.

**Comment by rvanbaalen** [comment]
Well based on this fiddle I suppose we can conclude that this is an implementation issue rather than a bug in one of the UI Bootstrap components:

http://jsfiddle.net/1471kzLh/

Without implementing Google Maps, I'm able to generate and re-generate content within the accordion when I navigate back and forth between the page navigation.
