### ISSUE TITLE
Tests to catch for invalid attributes?

### ISSUE THREAD

**Issue by dmitriz** [angular-ui/bootstrap#3601]
Is there any policy for checking directive's attributes for invalid values?
There aren't seem to be many tests doing that, like testing numeric attributes for `-1`, `"1.2"`...

For instance, `typeahead-min-length` is only tested set to `2`:
https://github.com/zacronos/bootstrap/blob/master/src/typeahead/test/typeahead.spec.js

**Comment by wesleycho** [comment]
For the most part, the tests are testing for functionality. I think it is safe to ignore those types of problems and leave it up to the user to fix, unless there is something special about a particular value type.

Closing this issue as overly broad, since if there is a legitimate missing test, then another issue/PR should be filed for it that describes it in detail.
