### ISSUE TITLE
Modal fade out effect disappeared in version 0.13?

### ISSUE THREAD

**Issue by Rafal2228** [angular-ui/bootstrap#3615]
Hi,
fade out effect for modal appears to not work properly in version 0.13, however in 0.11 it is present. Maybe the plunker will explain it better than I did:
Working version 0.11:
http://plnkr.co/edit/McVs72?p=preview

Not working version 0.13:
http://plnkr.co/edit/t5zlRd?p=preview

Is it really a bug or did I missed some feature or already closed issue?

**Comment by rvanbaalen** [comment]
Lets get things straight first:

The previous version of UI Bootstrap was 0.12.1 which supported the latest Angular 1.2 release (currently 1.2.28). This is a more accurate plunkr if I'm not mistaken: http://plnkr.co/edit/HsuTC6?p=preview

In your 0.13 and Angular 1.3 plunker, I can't see the animation either. Seems like a legit bug to me therefore I'll tag @chrisirhc in this one since he's the animations expert here.

**Comment by rvanbaalen** [comment]
Probably related: #3624

**Comment by chrisirhc** [comment]
ngAnimate is now needed if you want animations: http://plnkr.co/edit/d9PxCHXQH8yLv4wkNbhi?p=preview

**Comment by karianna** [comment]
@chrisirhc - So this isn't a bug?

**Comment by Rafal2228** [comment]
Thank you for your commitment. Closing :)
