### ISSUE TITLE
Datepicker: "...ng-model" value must be..." on Clear action

### ISSUE THREAD

**Issue by fifonik** [angular-ui/bootstrap#3617]
1. Open http://angular-ui.github.io/bootstrap/
2. Ctrl+Datepicker
3. Open popup datepicker
4. Choose any date
5. Open popup datepicker again
6. Click 'Clear' button
=>
In console you'll see error "Datepicker directive: "ng-model" value must be a Date object, a number of milliseconds since 01.01.1970 or a string representing an RFC2822 or ISO 8601 date."

I have not expected any errors on clearing date (setting it to null).
At least in 0.12.1 I had not have any errors.

**Comment by Grottkjell** [comment]
Having the same issue. Using angular 1.3.15.

**Comment by chrisfoster78** [comment]
I have this problem too and have had to downgrade to an older version to support nullable dates. Any other workaround?

**Comment by DieterLi** [comment]
Same issue with 0.13.0, but good with 0.12.1

**Comment by anilnatha** [comment]
I am running Angular 1.3.16 and get the same error message upon clicking 'clear' in the datepicker modal.

What makes it worse is that I am checking my forms $invalid property which is returning `true` even though the datepicker field in my form is not a required field, so a blank datepicker field should be valid, not invalid.

**Comment by anilnatha** [comment]
Probably worth mentioning the following:

 1. If you open up firebug while viewing the DatePicker demo at [https://angular-ui.github.io/bootstrap/](https://angular-ui.github.io/bootstrap/), it throws the error.
 2. In the example shown at the link, a `clear` function is set in `$scope`; however, in my setup, which is identical to that, the `clear` function is never called. Perhaps because the error is thrown prior to the clear function being called? I thought the clear function is called first if you click the 'clear' button on the datepicker modal, but that doesn't appear to be the case.

**Comment by anilnatha** [comment]
I have created a plunker, with documentation that describes the various problems related to this bug:

http://plnkr.co/edit/Iild15cgR9NXaX0iWjti?p=preview

This example aims to highlight the issue isn't just with the datepicker's model being cleared, but also how it affects form validation.

**Comment by jackpimbert** [comment]
:+1: Same issue here.

**Comment by askucher** [comment]
+1

**Comment by icfantv** [comment]
@askucher, please do not simply add `+1` to issues as it adds no intrinsic value to the discussion and serves to only clutter up the thread.  That said, I'm not sure what you're trying to imply with your support of this issue as we've made the switch to only support JS `Date` objects due to how different browsers handle dates differently.

**Comment by saurabh67** [comment]
+1

**Comment by icfantv** [comment]
@saurabh67, did you even read this thread?  the last post in this issue specifically asks you not do what you did.  you may use the response emojis to specify a reaction.  in the future, please be respectful of our time and processes by not being lazy.

**Comment by shanzilla** [comment]
It's not clear if this has been resolved. I'm still seeing the issue in Angular UI-Bootstrap 2.2.0. @icfantv When you say you've made the switch to only support JS `Date` objects are you saying that disallowing `null` as valid input for the datepicker is by design? Is there a workaround for date fields that are not required?
