### ISSUE TITLE
Provide Snapshot builds

### ISSUE THREAD

**Issue by JohannesRudolph** [angular-ui/bootstrap#3706]
It would be awesome if you could change the Travis build to also provide snapshot builds for download. Either as build Artifacts stored in travis or comitted to gh-pages branch. The former has the advantage of not bloating up the repo unnecessarily. 

Using snapshot builds would make it much easier for possible contributors (like me) to quickly test recent changes and verify pull requests.

**Comment by rvanbaalen** [comment]
Keep an eye on #3450

**Comment by icfantv** [comment]
@JohannesRudolph, this is going to be very low priority for us but we kind of like the idea of a nightly snapshot build.  That said, you can easily clone the repo and do the build yourself via executing the `npm install` and `grunt` commands.

**Comment by wesleycho** [comment]
Going to close this as something we won't support.

Hoping we have the main repository on npm within the next couple of weeks though so that anyone consuming the library via npm can then pull in the main library and specify the `master` branch or a particular commit in order to consume a specific version.
