### ISSUE TITLE
Remove inline styles from templates

### ISSUE THREAD

**Issue by lutzwuelfing** [angular-ui/bootstrap#3717]
In the timepicker template (maybe in others too, i didn't check) the input elements have inline styles difining their width. This really isn't a good way to do it since we can not override these styles in our css. Instead the timpicker element should have a class="timepicker" so we can apply our own styles to it.

**Comment by rvanbaalen** [comment]
I agree that there shouldn't be any inline styles in the first place. However UI Bootstrap aims to have **no external stylesheets**. We only use Bootstrap's CSS. That's probably how this inline style got in the template.

On another note: you can easily overwrite the default template with one of your own and style it as such. That's one of the main aims of this project: extendibility by customising the templates to your needs.

Therefore, I'm closing this issue since there wouldn't be another way to style the timepicker that fits the project's philosophy.
