### ISSUE TITLE
bug(popover): overflowing window borders

### ISSUE THREAD

**Issue by yangit** [angular-ui/bootstrap#375]
Popovers are overflowing over window borders.
http://plnkr.co/edit/q2Zj1F
Solution might be to add "Auto" positioning option.

**Comment by ilovett** [comment]
:+1:

**Comment by rzschech** [comment]
+1

**Comment by knorrus** [comment]
+1

**Comment by drewbeck** [comment]
Still need this! Were I JS ninja sufficient I would whip it up. Alas :(

**Comment by cleversprocket** [comment]
A workaround is to add another directive to the element and bind a mouseenter event or whatever is being used to fire the tooltip and adjust the position:
```javascript
angular.module('app')
    .directive('positionTooltip', ['$timeout', function ($timeout) {
        return {
            restrict: 'A',
            scope: false,
            link: function (scope, element, attrs) {
                var el,
                    arrow,
                    offset;
                element.bind('mouseenter', function () {
                    $timeout(function () {
                        el = element.next();
                        if (el[0].offsetLeft < 0) {
                            offset = el[0].offsetLeft;
                            el.css('left', 0);
                            arrow = el[0].querySelector('.tooltip-arrow');
                            arrow = angular.element(arrow);
                            arrow.css('margin-left', (offset + -5) + 'px');
                        }
                    })
                });
            }
        }
    }]);
```

**Comment by thegreatmichael** [comment]
Does https://github.com/twbs/bootstrap/pull/12328 end up in here somehow?

**Comment by jpmnteiro** [comment]
+1

**Comment by efosmark** [comment]
+1

**Comment by RobJacobs** [comment]
I have a couple of ideas I've been working on for this issue I'd like to share.  I need to pull them together in a plunk, then will post them shortly.

**Comment by chrisirhc** [comment]
@thegreatmichael thanks for mentioning that issue, we can use that as a reference implementation.

**Comment by rufinitsw** [comment]
+1

**Comment by pyella** [comment]
+1

**Comment by rvanbaalen** [comment]
It's already clear that this is a wanted feature. 

#### Please stop all the +1 responses

We'd like to keep this open for on-topic discussion instead of having to receive notifications for all +1 responses.

**Comment by pads** [comment]
Just thought I'd post my [work-around](https://gist.github.com/pads/3bbc1c9d45fe84b10977) if it's of use to anyone.  This enables a position to be set just before the popover becomes visible.  I had to tweak the CSS to initially hide the popover until positioning was complete as there were times when the popover would show and then jump into the correct position.

**Comment by Alexintosh** [comment]
is this solved?

**Comment by gruberjl** [comment]
I was having this issue with the uib-popover-template directive. It took me a while to figure out how to hack this dang thing (I'm new to coding so it may be simple and I'm an idiot [2 $timeouts were required])

This hack is for **uibPopoverTemplatePopup** but you could just find out what directive ui-angular is using for the tooltip or w/e by looking at the code.

if you don't use **popover-append-to-body="true"** the popover will be inline (the next element after your button). If you allow the popover to insert directly after the button the offset left may not work (because it offsets to the nearest parent with position relative (I should probably check that).

Lastly, I only tested the code if you use **popover-placement="top"**. It will probably work if you use *popover-placement="bottom"* but I didn't test it. It won't work for left or right (because I'm using margin-left)

```
<!-- In the Template -->
<a href popover-placement="top" uib-popover-template='"popovers/ProgramProgressionHelp.html"'  popover-append-to-body="true">Button</a>
```

```
// Directive code
app.directive('uibPopoverTemplatePopup', ['$timeout', function($timeout) {
  return {
    restrict: 'A',
    link: function (scope, element, attrs) {
      $timeout(function() {
        $timeout(function() {
          var popover = element;
          var offset = popover[0].offsetLeft;

          if (offset < 0) {
            var arrow = popover[0].querySelector('.arrow');
            angular.element(popover).css('margin-left', (offset*-1) + 'px');
            arrow_margin_left = angular.element(arrow).css('margin-left');
            angular.element(arrow).css('margin-left', (offset + parseInt(arrow_margin_left)) + 'px');
          }
        });
      });
    }
  }
}]);
```

Sorry I can't do a better fix. I looked at the source and your using fancy providers, I don't know how to use those things :)

**Comment by icfantv** [comment]
@gruberjl, we have smart/fixed positioning on our radar.

**Comment by icfantv** [comment]
Closing in favor of #4762.
