### ISSUE TITLE
Datepicker disables months if the first day in a month is a disabled day

### ISSUE THREAD

**Issue by michael34** [angular-ui/bootstrap#3775]
*  version of AngularJS used: 1.3.15
*  version of this library that you are using: 0.13.0
*  3rd-party libraries used, if any: select2
*  and most importantly - a use-case that fails:
As described in the title datepicker disables the selection of months of which the first day is a disabled day.
See here:
http://plnkr.co/edit/7vOiIFppcexvPe3hXq6B?p=preview
Click und the year to select the months. As you can see August is disabled because 1.8. is a Saturday which is disabled.

**Comment by wesleycho** [comment]
This is a bug, most likely in the check in the monthpicker.

I believe this should be simple to fix.

**Comment by wesleycho** [comment]
Hmm, this is a little trickier - this is partially a usage issue, but also partially something that is the result of an unexpected update timing.

[Here](http://plnkr.co/edit/ZkXNEi4fv7Q0HmLJWXFL?p=preview) is the fixes to the expected usage.

However, if one inspects this carefully to see the incorrect behavior, this is because the isDisabled check is firing before the update of `datepickerMode`.

I think to get around this, one should use a custom template instead of the isDisabled function, and disable the dates if they are a weekend for the daypicker.
