### ISSUE TITLE
Typeahead(Asynchronous results) doesn't works with Angular 1.4

### ISSUE THREAD

**Issue by jakubkowalczyk-pl** [angular-ui/bootstrap#3789]
Error: [filter:notarray] Expected array but received: {}
http://errors.angularjs.org/1.4.0/filter/notarray?p0=%7B%7D

**Comment by pkozlowski-opensource** [comment]
Plunker, please: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

I can't reproduce with the example from our demo page: http://plnkr.co/edit/vTB8bWad9MuEMB7kX1CM?p=preview

**Comment by dosapati** [comment]
Getting same error and the issue only comes when you use filter with Async HTTP Request
Here is the example:
http://plnkr.co/edit/uj82lr53GdnRs9s6Z4eF?p=preview

Please suggest if u have a quick solution, trying to find a workaround by my self too...

**Comment by allentong** [comment]
+1

**Comment by xtreemrage** [comment]
Getting the same error as @dosapati plunker, with an async call, [this has changed since 1.4.x](https://code.angularjs.org/1.4.1/docs/error/filter/notarray). It will work if you remove the filter, see [plunker](http://plnkr.co/edit/aygnt9Rr8C58slwYnqDQ?p=preview). But I don't know if this is what you want.

This only happens if I do an async call, if I already have the list (array), it works like it should (with filter:$viewValue).

I use angular v1.4.x and angular-bootstrap v0.12.1 (same error with: v0.13.0). How to resolve, is the filter needed?

**Comment by pkozlowski-opensource** [comment]
Guys, the way you use fitter suggest that you want to apply a filter to a ... _promise_ which obviously doesn't make sense. You need to filter the results in the JS code, see: https://github.com/angular-ui/bootstrap/issues/1740

**Comment by xtreemrage** [comment]
@pkozlowski-opensource thanks, didn't think about that ffs, fixed for me. You don't need the $filter of course if your back-end is filtering them.

**Comment by pkozlowski-opensource** [comment]
> You don't need the $filter of course if your back-end is filtering them.

Right, this is the usual approach. But you still might want to do some adjustments on the client side. Anyway, this works as expected, nothing to fix here.
