### ISSUE TITLE
Collapse flickers at page load in 0.13.0

### ISSUE THREAD

**Issue by arn80** [angular-ui/bootstrap#3801]
In 0.12.1 'collapse' works well, but in 0.13.0 the element 'flickers' at page load when I set an initial $scope.collapse = true; as the first line in my controller. 

The 'collapsed' content just pops into view in a fast moment just after page load. It is very obvious on pages, were a lot of elements are collapsed at page load.
It happens the most in Chrome and Firefox, but IE seems to handle it better !?!

I have made a <a href="http://plnkr.co/edit/VSbgaHR4vlxOyAz69iVz?p=preview" target="_blank">Plunker</a> with the issue.

Try to Run / Stop the Plunker a few times, because the issue is not as obvious in all cases.

**Comment by pcnate** [comment]
I couldn't get the plunker to show the issue by changing `$scope.collapse = true;` to `$scope.collapse = false;`. There seems to be enough of a delay to mask the issue.

**Comment by arn80** [comment]
I have changed the background color of the collapsed element to red. This should make the issue more visible.

Sometimes i have to Run / Stop the plunker up to ten times, before the issue appears. But it will eventually.

**Comment by arn80** [comment]
I have made a new <a href="http://plnkr.co/edit/nLfOB0JtjIXItAs1qnX4?p=preview" target="_blank">Plunker</a>

Now I use a ngIf on the element, and a timeout that makes it appear 500 ms, after page load. This should highlight the issue even more.

**Comment by RobJacobs** [comment]
Seems to be related to this [commit](https://github.com/angular-ui/bootstrap/commit/36e6363765dbae2872ef86b4cba890c9b197d74b) where collapse was refactored to use ngAnimate.  I believe the issue is with this [line](https://github.com/angular-ui/bootstrap/blob/master/src/collapse/collapse.js#L24) where the height for the collapse animation gets set to the element height.  If the element is collapsed initially, it still calls the collapse function and runs the animation.

**Comment by wesleycho** [comment]
Thanks for this investigation @arn80 - I have a proposed fix in the referenced PR above, please take a look and let me know if there are any issues there.

**Comment by arn80** [comment]
Yes, that seems to have fixed it. Great work, that was fast :-). Thanks @wesleycho.

**Comment by mseancole** [comment]
@wesleycho I still get flickering when I tried this.

I set some breakpoints in the watch and discovered that this might be caused by the `collapsing` class being added when the directive is initially run. I fixed it by adding a check at the beginning of the `collapse()` function to verify the element had either the `collapse` or `in` class before allowing it to proceed.

**Comment by crkjl** [comment]
Hi, in latest version 2.5.0, when load page if uib-collapse is true the flickering problem appears again.
