### ISSUE TITLE
Collapse animation depends on ngAnimate, but no mention of that anywhere

### ISSUE THREAD

**Issue by ryancrisp** [angular-ui/bootstrap#3822]
Collapse depends on ngAnimate being included into animate properly, but there is no mention of that in any of the documentation.  Even your own plunkr does not successfully animate since it doesn't include ngAnimate.  

http://plnkr.co/edit/vSwhJ8WGjOZPib0Iutxd?p=preview

I believe this should be called out somewhere to avoid unnecessary headaches trying to figure out why it does not work in other developer's projects who have not already included ngAnimate.

**Comment by rvanbaalen** [comment]
Technically, none of the UI Bootstrap parts *depend* on ngAnimate. Everything works fine without it. 

*However* I know what you mean. The *animations* don't work without ngAnimate. This should indeed be updated in the docs. I'm closing this issue for now since we are aware of it and there are plenty other issues mentioning the same request.
