### ISSUE TITLE
Alert always shows close button

### ISSUE THREAD

**Issue by flosky** [angular-ui/bootstrap#3848]
The alert directive always shows the close button ('x'), even if no close attribute is present.
This behaviour only occurs when using Angular.js v. 1.4.1. With version 1.4.0 everything is Ok.

To reproduce:
Use Angular.js v. 1.4.1 and use alert directive without 'close' attribute.

**Comment by antoinepairet** [comment]
Could you setup a plunkr please? thx

**Comment by rvanbaalen** [comment]
We don't officially support Angular 1.4 yet so it is possible that some bugs occur. In the meanwhile, it helps if you provide a plunkr like @antoinepairet asked.

**Comment by flosky** [comment]
http://plnkr.co/edit/gcnHKbhzbt6u7eFCDisK?p=preview

**Comment by wesleycho** [comment]
This should be an easy fix on your side via CSS.

However, this does appear to be a bug in Angular 1.4 though.

**Comment by wesleycho** [comment]
Linking a version of the Plunker based off of current `master` [here](http://plnkr.co/edit/ntYo3X0dlSV2FdS0pvqn?p=preview) for reference.

**Comment by soletan** [comment]
According to my setup including AngularJS 1.4.2 this fix isn't working for `$attrs` always containing property `close`, most probably due to its explicit declaration in `scope` definition of directive `alert`. Putting aside concerns about using `in`-operator it might require some more complex logic like this:

    $scope.closeable = !!$attrs.close && $attrs.close !== "undefined";

I tried the previous test - not the one proposed here, but the one "fixed" above - with

    <alert type="danger"></alert>

(no close attribute at all)

    <alert type="danger" close></alert>

and

    <alert type="danger" close=""></alert>

In every case `$scope.closeable` is falsy in AngularJS 1.4.2, thus not showing close icon.
