### ISSUE TITLE
ui.bootstrap dropdown directive in a flex container doesn't work

### ISSUE THREAD

**Issue by neesonqk** [angular-ui/bootstrap#3969]
Reference: [plunker](http://plnkr.co/edit/DiAPr6dsxY5M2PLipyy9?p=preview).

I found once put `dropdown direction` into a flex container, the dropdown menu won't appear anymore.

I debugged found two workarounds

##### workaround 1
```html
<div style="display:flex">
        <div>
         <span class="dropdown" dropdown>
               <a href="" class="dropdown-toggle" dropdown-toggle>
                 Click
               </a>
               <ul class="dropdown-menu" dropdown-menu>
                 <li> 
                     <a ng-click="action1()">Action1</a>
                 </li>
              </ul>
        </span>
       </div>
</div>
```

##### Workaround 2
```html
<div style="display:flex">
         <span class="dropdown" dropdown>
               <a href="" class="dropdown-toggle" dropdown-toggle>
                 Click
               </a>
               <ul class="dropdown-menu" dropdown-menu style='top: 15px;'>
                 <li> 
                     <a ng-click="action1()">Action1</a>
                 </li>
              </ul>
        </span>
</div>
```
Workaround 2 is a bad approach, because different dropdown requires different top value.

**Comment by wesleycho** [comment]
Can you explain more clearly or produce a reproduction? I am not able to observe the behavior you are describing in [this Plunker](http://plnkr.co/edit/7trojb1LlphoYBH8VvHz?p=preview) - note that the `Click me for a dropdown, yo!` dropdown is encapsulated in a div with `display: flex`.

**Comment by neesonqk** [comment]
@wesleycho Sorry I put the wrong reference link, I've updated the link, also you can find from http://plnkr.co/edit/DiAPr6dsxY5M2PLipyy9?p=preview.
There are two necessary settings for reproduce this issue
1. set `html`, `body` height width to 100%
2. set container div to `display: flex; flex: 1 1 auto` 

In fact, the `dropdown menu` appeared, but it's out of the browser range, in the example Plunker, you can scroll down to the end to see the `dropdown menu`

**Comment by wesleycho** [comment]
Oh interesting, I see what is happening now. The element with the `dropdown` attribute has 100% height due to `flex-grow: 1` (which is the first argument to the `flex` CSS property), so `top: 100%` is causing the dropdown menu to be pushed down. Removing `flex: 1 1 auto` would fix this problem.

Another solution would be to use `position: absolute` in your dropdown element - [here](http://plnkr.co/edit/TNUjx7zybb4qNnDFhOhv?p=preview) is an example in action.

This looks like a CSS bug to me in your code though, and not a bug in the library.

**Comment by neesonqk** [comment]
Hmm.. indeed, in my case, I need a dynamic full height setting to the container, so to be able to achieve this I have to set `flex-grow: 1` to auto the height.

The second approach fixed the example problem, however once set to `position: absolute`, it won't be treated as a `flex-item` anymore, see [here](http://plnkr.co/edit/0Mpgsl9JSUz0iCsCd0Ks?p=preview), I applied `justify-content: space-around` to the container, due to the `position:absolute` setting, the dropdown link won't be calculated as `space-around`.

I can put a wrapper to the dropdown link to work around, the only problem is it looks ugly and tedious, I would like to know if there is a better way to solve my problem, thanks so much.

**Comment by wesleycho** [comment]
The problem is that the dropdown menu element shouldn't have any knowledge about the size of the container, just positioning itself just below the dropdown toggle. This means that the height should not be 100% of the page.

This implies strongly that it should be a css workaround on the user side that is adjusted to workaround the issue, since it works correctly out of the box excepting this edge case - I think the workarounds are much preferred over any potential component modification that might be flawed.

**Comment by neesonqk** [comment]
Correct, I'll make a css workaround to my case, thanks for the help.
