### ISSUE TITLE
ui-select inside a bootstrap dropdown menu

### ISSUE THREAD

**Issue by jbonigomes** [angular-ui/bootstrap#3989]
I am using ui-select inside a bootstrap dropdown menu, this menu only closes when I click outside the dropdown menu area, this is good, however, with an ui-select there, the bootstrap dropdown closes when I select a value from ui-select

**Comment by RobJacobs** [comment]
Questions of this nature will get a better response on Stackoverflow, see the [faq](https://github.com/angular-ui/bootstrap#need-help).  You have 2 separate popup implementations fighting each other, not sure why you would want to use ui-select in a dropdown as ui-select itself is a dropdown?  Closing for now, I will re-open if you feel there is an issue we can address.

**Comment by jbonigomes** [comment]
Thanks @RobJacobs, but I think we may have a misunderstanding here, I have taken a screenshot of the UI to demonstrate better what is happening:

![menu](https://cloud.githubusercontent.com/assets/746143/8825344/4bf64cfc-3076-11e5-9707-d0c5df932ab6.png)

The bootstrap dropdown englobes a sequence of ui-select items.

**Comment by dasrick** [comment]
Same problem here ... the selection of an item of the inner ui-select will close the outer bootstrap dropdown (ui-bootstrap dropdown with auto-close="outsideClick") ...
@jbonigomes did you find a solution/workaround/pull-request for this behavior?

![outer bootstrap dropdown - inner ui-select](https://cloud.githubusercontent.com/assets/377702/10222591/2dc1e054-6855-11e5-9092-ac79b6bd46d6.png)

Screenshot: the selection of a role will close the complete dropdown ...

**Comment by icfantv** [comment]
Without researching it further, It sounds like the issue _may_ be with event propagation.  I would encourage you guys to use the un-minified version of the UI bootstrap library and see if this is the case.  However, it may boil down to what library is actually causing the issue, UI Bootstrap or UI Select.

If the latter, I'm afraid that active development on that project has appeared to stall so unless you REALLY need all the features of UI Select for that select box (find-as-you-type, tagging, etc...) I would strongly encourage the use of the native `<select>` element w/ `ng-options`.  Doing this may also help discern where exactly the problem lies.

In general, it's really just a good idea to only use 3rd party libraries to provide specific functionality where you need them and not "just because you're using it elsewhere."  This is what we've done at work and, like us, I think you'll find that you'll have a lot less headaches.  Think of it as "using the right tool for the job."

Hope that helps and please let us know what you find.  Thanks.

**Comment by Rabbit-IQ** [comment]
@icfantv I have the same problem and solved it with a plain select element instead of ui-select. But it looks not so good in any browser and sometimes i need the "find-as-you-type" feature. So is there any progress in that discussion ?

**Comment by icfantv** [comment]
@Rabbit-IQ would the typeahead widget work in this scenario?
