### ISSUE TITLE
Update angular-ui NPM configuration to export a string

### ISSUE THREAD

**Issue by jasonrose** [angular-ui/bootstrap#3999]
Currently, `angular-bootstrap@0.12.2` and its previous versions exports `ui-bootstrap-tpls.min.js` as its main file.  The file defines the `ui.bootstrap` module in angular, which is all well and good.

However, the convention seems to be for the entry point in angular npm modules to define the module in angular, then export the module name via `module.exports`.  I will include my current application's module definition here, to see how some third parties are packaging their libraries:

To support @kentcdodds, here is my module's definition in the application that I'm currently working on.  Pardon the coffee if you're not a fan:

    module = angular.module 'mmb', [
          require 'angular-route'
          require 'angular-translate'
          require 'angular-sanitize'
          require 'angular-ui-bootstrap'
          require './components/flux/Flux.coffee'
          require './components/config/Config.coffee'
          require './components/logging/Logging.coffee'
          require './components/user/User.coffee'
          require './components/upp/Upp.coffee'
          require './components/header/Header.coffee'
          require './components/wizard/Wizard.coffee'
          'mmb-templates'
        ]

`angular-translate`, and the temporary `angular-ui-bootstrap` have a convention, as shown below in `index.js`:

    require('./ui-bootstrap-tpls.js');
    module.exports = 'ui.bootstrap';

I think that this format is much cleaner, and at the very least removes one of the magic strings from the application.

@kentcdobbs blogged about this same topic.  I will paste his comment here, which he originally brought up in https://github.com/angular-ui/bootstrap/issues/3992#issuecomment-123836419: https://medium.com/@kentcdodds/how-to-distribute-your-angularjs-module-e04d4dd58ddc

**Comment by Foxandxss** [comment]
I am sorry, long day battling with NPM packages. What do you need then? To update the previous `angular-bootstrap` to support browserify/webpack or to do something with the new one?

**Comment by jasonrose** [comment]
`angular-bootstrap` works for me, as long as I do this:
    require('angular-bootstrap');
    angular.module('mmb', ['ui.bootstrap']);
I don't think that this should change in the 0.12.x branch since that is what people expect.

`angular-ui-bootstrap@0.13.0` works almost as-is, except for the restrictive `peerDependencies` which are not part of this issue.

If `angular-ui-bootstrap` is the way forward, then it behaves like `angular-translate` and other browserify-compatible npm packages, and does not require any modifications on that front.

However, if `angular-ui-bootstrap` was a fluke, then I suggest that we adopt the convention I described above for `angular-bootstrap@0.13.0` or whatever the next version will be.

**Comment by Foxandxss** [comment]
Oh, I understand.

@jasonrose there were no official ui-bootstrap packages, so two third party users created `angular-bootstrap` and `angular-ui-bootstrap`.

I got access to both of them and we decided to stick with `angular-ui-bootstrap`.

I bumped that `angular-ui-bootstrap` to use `0.13.0` (our latest release) and also to be able to use browserify / webpack.

So that is the good package and the one that everyone should use.

People complained about having now two packages is now confusing so stupid of me I decided to get rid of one of them, that is my bad, completely.

So I recreated `angular-bootstrap` just for the sake of not breaking it for you guys.

About the restrictive peerDependencies, yes, that is right, I read the doc and technically `~1.3.17` was for matching from 1.3.0 to the latest 1.3.x version. Obviously I was wrong but I cannot fix it without releasing a new package.

**Comment by wesleycho** [comment]
We should probably look to do a release for 0.13.1 sometime soon then (this Friday perhaps?) and bump all unresolved issues to 0.13.2.

**Comment by jasonrose** [comment]
Then, I think that this issue is a no-op and can be closed.  Should I create a new issue for relaxing the peerDependencies for a 0.13.1?

**Comment by Foxandxss** [comment]
@jasonrose yeah, you can do that.
