### ISSUE TITLE
Adding Half Star Functionality To ui.bootstrap.rating?

### ISSUE THREAD

**Issue by johnjspiteri** [angular-ui/bootstrap#4020]
Has anyone offered to help integrate this feature?

Thank you
John

**Comment by wesleycho** [comment]
This would only work with Font Awesome I believe - I don't see the necessary icon present in Bootstrap's glyphicons. I am not sure that is something we want to support, although you're more than welcome to fork the component and add support in a standalone library.

**Comment by johnjspiteri** [comment]
There is a half star icon with Font Awesome "fa fa-star-half"... I will have to add this functionality into a project, will take a fork and start working at it.

Thank you @wesleycho

**Comment by wesleycho** [comment]
Closing for now - if Bootstrap adds support for a half star font, then I would be more than welcome to revisiting this.

**Comment by davecyen** [comment]
+1

**Comment by dularion** [comment]
+1

**Comment by icfantv** [comment]
@davecyen, @dularion, please do not merely add `+1` to issues with no other content.  it provides no intrinsic value and serves to only clutter up a thread.  Additionally, GitHub has now added emojis to posts so you can indicate support for a feature by adding an inline reaction rather than a physical response.  Please use them in the future.  It's the smiley face icon next to the pencil and X icons in the upper left corner of a post.

Also, as @wesleycho noted, this is not a feature we are not going to support.

**Comment by dularion** [comment]
Sorry, didn't know they had implemented that yet!

**Comment by icfantv** [comment]
@dularion no worries - they didn't exactly issue a press release.  i found out about it from someone's Slack post w/ the link.

**Comment by quicoto** [comment]
@johnjspiteri have you had any luck implementing the half-star rating on your own?

**Comment by johnjspiteri** [comment]
Yes I did @quicoto, in a pretty primitive way... had to slap something together quickly so:
A directive that would take the model value of 4.5, and checked

`if(scope.rating % 1 !== 0)`

Then I would show a half star after the ng-repeat, using CSS to keep things neat.

[games.rating.directive.js.zip](https://github.com/angular-ui/bootstrap/files/205403/games.rating.directive.js.zip)

Hope this helps.

**Comment by quicoto** [comment]
@johnjspiteri Thank you.
