### ISSUE TITLE
Support multiple position options for popover

### ISSUE THREAD

**Issue by SMHFandA** [angular-ui/bootstrap#4024]
Thanks very much, guys, for your jobs. Very useful module.

i have suggestions relatively popover component. Be nice if, maybe in future, popover component have following position settings: top-left, top-right, bottom-left, bottom-right. Something like this:

![popover-bottom-left-position](https://cloud.githubusercontent.com/assets/5597196/8911056/cb2b9912-3492-11e5-9c74-b87bff3be2cb.png)

Thanks.

**Comment by wesleycho** [comment]
There are already multiple tickets on this - see my PR at #3900 for a preliminary implementation that would allow support of this feature.

**Comment by ksheedlo** [comment]
+1 to this and for #3900.

One concern I want to raise here is that we may need to put the directions in different order to mean different things. For instance, the popover in the issue comment screenshot is to the right of the button and aligned with the bottom edge. I've mostly worked with popovers that are above or below the button and align with the sides. For example, this is what I would call a `bottom-left` popover.

![screen shot 2015-08-26 at 2 18 24 pm](https://cloud.githubusercontent.com/assets/1271410/9506611/ff76ad9c-4bfd-11e5-8087-8a77298b83f7.png)

Since it is below the target element and aligned with the left edge. By this scheme, the popover in the issue screenshot would be a `right-bottom` popover, not a `bottom-right`.

**Comment by wesleycho** [comment]
Please don't +1 issues - rest of the commentary is fine, just adding that to educate since it alone adds no valuable signal or information :) .

Thanks for that particular use case though - that is useful information for when we tackle this on full.

**Comment by ksheedlo** [comment]
Understood. BTW @wesleycho - is there anything I can do to help move the needle on this? My day job is stuck on an ancient forked version of ui-bootstrap and this is something we desperately need. I'd be glad to help out in whatever capacity.

**Comment by wesleycho** [comment]
If you're willing to put in the legwork to implement it properly based on `master` with proper test coverage, we'd gladly accept pull requests.

**Comment by icfantv** [comment]
Closing in favor of #4762.
