### ISSUE TITLE
Dropdown btn issue

### ISSUE THREAD

**Issue by s4m4n** [angular-ui/bootstrap#4111]
Hello,

Anyone having idea regarding this issue on stackoverflow?
https://github.com/angular-ui

Thanks,

**Comment by wesleycho** [comment]
I think you linked the wrong link.

**Comment by wesleycho** [comment]
Closing due to lack of actionable evidence.

Take note of https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md when filing an issue.

**Comment by s4m4n** [comment]
http://stackoverflow.com/questions/31785941/angular-ui-bootstrap-dynamic-dropdown-not-working-in-datatables
http://plnkr.co/edit/WEtnEeyiYyyGd2gsyd4w?p=info

angularjs v1.3.15

**Comment by wesleycho** [comment]
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md when filing an issue - this is a support issue that is a usage problem, not a library problem, and thus is not appropriate for a GitHub issue, which disrupts developer attention from maintenance & feature development (in this case, developing support for plugging in a custom dateparser such as moment.js into use with UI Bootstrap, a highly requested feature).

The culprit here is that the HTML generated in the render function of the datatables plugin is uncompiled, and thus Angular has no way of knowing that it should be handled by Angular. [Here](http://plnkr.co/edit/dAPQKNSdgWQDv5PnEQYa?p=preview) is one way to get it working. In the future, please do your research on the libraries you are using, there is a wealth of material out there in the API documentation.
