### ISSUE TITLE
ng-controller with tabs

### ISSUE THREAD

**Issue by ericman93** [angular-ui/bootstrap#4118]
Hi

I'm using tabset and I want each tab to have his on controller.
The problem is that tab is creating his own scope and if will sepcify the controller on the tab's DOM i will receive an error that multiple directives asking for new/isolated scope.

One fix is to set the controller in a div inside the tab, but in that way I can't pass a function from the controller to the "select" callback of the tab.

Is there any workaround for my problem?
Thanks

**Comment by icfantv** [comment]
In the future, please do not use the Issues queue for support and usage questions.  Questions of this nature will get a better response on Stack Overflow, please see the Need Help section [here](https://github.com/angular-ui/bootstrap#need-help).

If I understand your question correctly, you want to use the tab's select callback to call a controller function in your tab's controller?  What are you trying to accomplish that makes you feel you need to do this?  At first glance, it sounds like you're trying to call an initialize function.

**Comment by wesleycho** [comment]
You are better off creating a custom directive with directive controllers for your tabs - it leads to cleaner HTML.

We do not want to recommend using ng-controller for this purpose, as it is an antipattern.

**Comment by SergeyKulgan** [comment]
Also have the same problem, I have separate controller for content of each my tab, I want call some controller function from DOM using "select" attribute.
**wesleycho**, I do not understand, how can I use my custom directive with your tab/tabset controls (directives)? Is it possible to combine, to use your component in my case or I need to write own tab logic by myself? Please give some example if that possible.

**Comment by icfantv** [comment]
@SergeyKulgan, it's not clear what exactly you want to do from a UX/UI perspective.  Can you be more clear?  Thanks.

**Comment by SergeyKulgan** [comment]
@icfantv, thanks for quick response. Please point correct way, how can I use your uib-tabset/uib-tab directives to reach this:
<div ng-controller="parentCtrl">
   ...
   <uib-tab heading="TabA" ng-controller="tabACtrl" select="initializeTabA()">
            ...
            here I also using some scope properties from parentCtrl
            ...
   </uib-tab>
   ...
</div>
Where initializeTabA() - function, defined in $scope of tabACtrl controller, it downloads some content, should be executed on tab selecting, thus tabACtrl should be accessible from "select" attribute of tab.

**Comment by icfantv** [comment]
Per @wesleycho's suggestion above, don't do this.  You need to create a directive and put that in your `uib-tab` element.  We've seen issues surrounding errors due to the `replace: true` property on our directives such that angular will complain about not being able to find the appropriate controller for the `uib-tab` or `uib-tabset` directives.

You can then use the observer pattern to implement inter-directive communication (don't use events).

**Comment by SergeyKulgan** [comment]
Thanks for suggestion, but, what I think about it:
It is so complicated...I need just execute method on tab select, this is the most wanted function and should be out from the box, It should be so easy...I'm .NET developer, have also simple sites on Angular. It was never so hard for me to make such simple things in .net... Why I can not make this tab as part of my tab class (controller) and somehow (in my class) set handler for exposed onSelect event? I do not need directive, not going reuse it, it is not like control. And, as I understood, to implement inter-directive communication I need to modify source code of that uib-tab directives (to add methods for event handlers registration and call that handlers in needed place). I'm consumer/user and should not modify code of base components to add such functionality, again in terms of OOP, it should be encapsulated (I, as user not interested about internal details and implementation and do not want to dig in it), all that I need: interface/api to use it and have most used functions out from the box, without dance with tambourine. I dislike that angular directives approaches, they far from ideal and contradicts with OOP, I'm sure that somehow it can be done much more better.
BTW, I completely read and understood http://blog.carbonfive.com/2015/03/25/communication-between-collaborating-directives-in-angular/

**Comment by icfantv** [comment]
@SergeyKulgan, IMO, far too often, we as engineers think tend to think about things at a macro level.  E.g., I want to do _x_, how do I do it?  Sometimes, a better solution is to think about it from a UX and end-user perspective.  E.g., I would like to do _x_ when the user does _y_.  Perhaps if you start there I can be of further assistance.

---

I come from an OOP background (Java) as well and the thing you need to realize is that Javascript is not an OO language so you can't think of things in terms of OOP.  Yes, you can kinda/sorta do it, but it's not the same thing.  When you did .ASP you had full control over everything, which is why, in general, it wasn't hard to do stuff like executing a callback when the user clicks something because there's no real sense of scope.  And if you used jQuery, you exposed two of the core problems that angular attempts to solve:  1) being able to look at a component and know exactly what happens when you interact with it (because the callback bindings are right there), and 2) automatic two-way data binding so you don't have to do stuff like:  `$('#myInputField').val()` to get some input data or `$('#myStaticDiv').text('snoopy')`.

But angular also gives you the framework to break stuff up into smaller functional pieces - something you'd have to do all on your own in jQuery - and part of that is following the rules of how to properly use those functional pieces.  I admit it's a bit esoteric at first and there's not a lot of great resources on how to properly design/architect an enterprise application - rather the books/tutorials tend to focus on how to use one small piece of the API.

**Comment by SergeyKulgan** [comment]
Yes, I agree, 2-way data biding and declarative approach, when you looking on directive element in html, it like an object, name is intuitive and allows you to understand what it do, attributes- like properties of that object and implementation is hidden/encapsulated in directive js. It is cool no doubt. But angular very strict, interaction between directives, controllers are restricted, we have easy access parent from child but not vise-versa or between siblings, but in real they should often communicate. Hard to model in accuracy real objects and their relations, often I need some workaround, angular puts you in a strict matrix, if you want to implement some simple and popular - it very easy with angular, but you loosing flexibility and it becomes even more difficult when you want to make some difficult custom functionality. Anyway, thanks for answer, I will learn angular more. 
___
I used following to solve that problem:
```
<div class="nav nav-tabs" ng-controller="tabACtrl">
     <uib-tab heading="Tab A" select="initializeTabA()">
         ....
     <uib-tab>
</div>
```
or can use directive instead:
```
<div class="nav nav-tabs">
     <tabA-directive></tabA-directive>
</div>
```
where template of tabA-directive contains: 
```
<uib-tab heading="Tab A" select="initializeTabA()">
      ....
<uib-tab>
```
and directive controller is tabACtrl, which scope contains initializeTabA() function, it will be executed on tab select.

**Comment by icfantv** [comment]
Be careful with that latter approach - you can break the Bootstrap CSS which is, unfortunately, tightly coupled to DOM structure (i.e. they use direct child selectors `>` rather than the descendent selector).

**Comment by coreystinson2** [comment]
All of these suggestions are great, but it looks like you're all taking the simplest approach possible in an attempt to close this issue without actually addressing the problem at hand.

Your suggestion @wesleycho to create a directive to avoid the `ng-controller` approach is fantastic. I would like to extend on that and say not only is it good for an increase on performance but to encapsulate each tabs properties and controller methods opens up component reusability and separation of concerns which we should all be looking for in our applications.

Now @icfantv from the last suggestion @SergeyKulgan has taken the advice from @wesleycho and created these custom directives for each tab except this won't work as bootstraps css rules force a particular DOM structure which is impossible to achieve with any form of directive approach.

Now if you're following along you will see the crux of this support ticket.
You've altered a core component of this library without testing the range of ways it was used in previous versions, and then instead of coming up with an answer to the problem you've just suggested a bunch of 'best practises' this guy should adhere to that are literally impossible to use due to what i've mentioned above.

@SergeyKulgan What you want to do in order to solve this problem is create a new set of styling rules from the default `bootstrap.css`, anything that references the following:
```
.nav-tabs > li {}

.nav > li {}
```

you want to create in your css file the same rules but with a middleman, this middleman can be any given class/selector that you apply to the element in which your directive is set to:
```
.nav-tabs > .foo > li {}
.nav > .foo > li {}
```

For example:
```
<tabset>
  <tab-one class="foo"></tab-one>
  <tab-two class="foo"></tab-two>
</tabset>
```
This is the cleanest approach to resolve this problem.

Feel free to re-open this ticket and close it now that a real solution has been given.
Thanks
