### ISSUE TITLE
[q]is 'rendered' promise for modal still available?

### ISSUE THREAD

**Issue by ZuBB** [angular-ui/bootstrap#4147]
I am would like to know if next line from doc is still valid

> `rendered` - a promise that is resolved when a modal is rendered

**Comment by icfantv** [comment]
Yes, it is still valid.

**Comment by ZuBB** [comment]
My guess is that its not 
![2015-08-08-180536_1920x1080_scrot](https://cloud.githubusercontent.com/assets/597016/9150909/5cbee05a-3df8-11e5-94ee-132c4d1e5f0e.png)

Besides I did a search for 'rendered' keyword in your code and did not find anything related to that

**Comment by icfantv** [comment]
https://github.com/angular-ui/bootstrap/blob/master/src/modal/modal.js#L559

**Comment by ZuBB** [comment]
Ok, I figure out what happened. For some reason we have old version of you package in node_modules.

Btw. Github cant find line you mentioned

https://github.com/angular-ui/bootstrap/search?utf8=%E2%9C%93&q=rendered
 
Thanks a lot for help

**Comment by icfantv** [comment]
You're welcome.  BTW, the link works fine for me:

![image](https://cloud.githubusercontent.com/assets/370054/9158897/ccababb2-3edb-11e5-88f4-19435782788c.png)

Your search link isn't valid because GitHub is only showing the first two matches for `modal.js` and indicates thus above each window.  Look for the text: "Showing the top two matches. Last indexed 2 days ago."
