### ISSUE TITLE
btn-radio directives not working on 0.13.3 if combined with ng-repeat directive

### ISSUE THREAD

**Issue by lucienbertin** [angular-ui/bootstrap#4185]
i did this [plunkr](http://plnkr.co/edit/QFxZPRhedJau4jiz2XuE?p=preview) to show the issue.

basically i have this
```js
$scope.choices =['a','b','c'];
$scope.value='a';
```
and this
```html
{{value}}
<div class="btn-group">
	<label class="btn btn-primary" ng-model="value" btn-radio="c" ng-repeat="c in choices">{{c}}</label>
</div>
```
clicking on the buttons doesn't work, doesn't update value

funnily enough, when i add the same group of choices without the ng-repeat
```html
{{value}}
<div class="btn-group">
	<label class="btn btn-primary" ng-model="value" btn-radio="c" ng-repeat="c in choices">{{c}}</label>
</div><div class="btn-group">
	<label class="btn btn-success" ng-model="value" btn-radio="'a'">a</label>
	<label class="btn btn-success" ng-model="value" btn-radio="'b'">b</label>
	<label class="btn btn-success" ng-model="value" btn-radio="'c'">c</label>
</div>
```
`value` will be updated when i use the second group of buttons and the first group of buttons will also be updated, showing the correct option being active

#### version used
 - angular 1.4.3
 - ui-bootstrap with templates 0.13.3
 - bootstrap 3.1.1

**Comment by RobJacobs** [comment]
Questions of this nature should be posted on stackoverflow, please see the readme section [here](https://github.com/angular-ui/bootstrap#need-help). The behavior you are seeing is due to prototypal inheritance as described [here](https://github.com/angular/angular.js/wiki/Understanding-Scopes) as ng-repeat uses isolate scope.  The updated plunk [here](http://plnkr.co/edit/WLUmFBJSHWJUaasTtYG8?p=preview) demonstrates how this should be implemented.

**Comment by lucienbertin** [comment]
makes sense, thanks
