### ISSUE TITLE
Datepicker Not Parsing Date from String

### ISSUE THREAD

**Issue by Zyquivilly** [angular-ui/bootstrap#4188]
It looks like going from v0.13.1 to v0.13.2 the datepicker no longer handles parsing a date from a string. Is this intended functionality?

Please see the following Plunker, which shows that the form is being marked invalid when given a string version of a date in v0.13.2 but works as expected when switched to v0.13.1: 
http://plnkr.co/edit/jjbvdsabeSWlARRAl4PP?p=preview

**Comment by wesleycho** [comment]
Support for falling back to a string that uses the date constructor has been removed - this is due to side-effects this had on validation and differing behavior between browsers due to what strings each browser assumed were valid date strings.

I would recommend turning your date into a date instance in this case, like [this](http://plnkr.co/edit/yiNw8jZ3l0mxfOnhmYG1?p=preview).
