### ISSUE TITLE
Empty date picker leads to invalid form element

### ISSUE THREAD

**Issue by hypery2k** [angular-ui/bootstrap#4208]
When resetting an date picker via emptying the field the field gets invalid. Bug is not depending on AngularJS version, as it happens already with the Bootstrap demo page.

Just go to http://angular-ui.github.io/bootstrap/#/datepicker and hit the clear button

**Comment by wesleycho** [comment]
This is correct behavior - if the field is not present, it should be invalid.

What are you expecting?

**Comment by hypery2k** [comment]
For a required field it's totally true, but if I want to clear an optional field within edit it should not become invalid, or I'm wrong? How can I clear an previous set date picker without form validation errors?

**Comment by wesleycho** [comment]
Being optional has no bearing on validity - [here](http://plnkr.co/edit/4kuXU4MT2w1XyIGq6kid?p=preview) is a barebones example of an optional field with Angular.

It is up to the user to handle whether to use the validation information.

**Comment by hypery2k** [comment]
I see, would be a nice feature. I know written a custom validation directive to set required. Would be nice if date picker evaluates the ng-required too

**Comment by wesleycho** [comment]
`ng-required` has no bearing on how validation happens - validation is independent of validity, as my example shows.

**Comment by wesleycho** [comment]
Closing as a usage issue - the datepicker's validation is behaving as it should be.

**Comment by rythos42** [comment]
This behavior is continually a thorn in my side, and I feel like the issue hasn't been argued well enough.

This is a UI framework. It should not be making model decisions for me, and yet that's what it's doing. An empty date is definitely an invalid **date**, but it is not necessarily an invalid **datepicker**. The current implementation requires that my datepicker be labelled invalid, and there's nothing I can do about it.

Because of this, I cannot use form.$invalid to determine whether my form is vaild or not. I can't show/hide error messages for the datepicker based on datepicker.$invalid.

This framework should stick to UI things, and leave model things to the users of the framework.

**Comment by MJunghenn** [comment]
Did anyone got a workaround for that?

**Comment by rythos42** [comment]
Our workaround was to not check $invalid on the datepicker. Instead, we wrote a function that looks for specific errors and checks that the field isn't empty. 

Here's an example, from a re-usable directive used in many places around our application (ie, it has to be super generic)
`
function isEmpty() {
     return ctrl[scope.modelName].$viewValue === '';
};
scope.isInvalid = function () {
    return !isEmpty() && ctrl[scope.modelName].isInvalid();
};

scope.isInvalidDate = function () {
    return !isEmpty() && ctrl[scope.modelName].isInvalid() && ctrl[scope.modelName].$error.date;
};
`

(The modal `isInvalid` is a helper function that checks if the user is in the field, fixing their mistake and, whether the field has changed, **and** checks `$invalid` on the model, so we don't show validation at certain times. I don't think it's relevant to the question.)

**Comment by chokdee** [comment]
@wesleycho: This is a wrong argument, cause the plunker script is showing the opposite of this you are writing.
If the field is set to required then is must be invalid.
Please see http://plnkr.co/edit/cmRoyK?p=preview

**Comment by pavanesh2009** [comment]
@rythos42: Would it be possible to share the directives? I have spent hours to fix it with various proposed solution and nothing seem to be working. In my case, It was detected during QA test therefore becomes high priority to fix it at earliest.

Thanks in advance!

**Comment by rythos42** [comment]
I can share a bit more, but I can't share "the workaround", because it's pretty heavily integrated with other irrelevant code.

ValidationHelperDirective, used by DatePickerDirective (among other directives) to do some common work:
`function ValidationHelperDirective($document, $timeout) {
    return {
        require: '^form',
        restrict: 'A',
        link: function (scope, element, attrs, ctrl) {
            var inputElementName = attrs.oppValidationHelper,
                fieldController = ctrl[inputElementName],
                inputElement;

            // If this directive is used in another directive, that directives elements aren't in the document until after the thread has finished.
            $timeout(function() {
                inputElement = angular.element($document[0].getElementsByName(inputElementName)[0]);
                inputElement.on('blur', function () {
                    $timeout(function() {
                        fieldController.inField = false;
                        fieldController.$setPristine();
                    });
                });

                inputElement.on('focus', function() {
                    $timeout(function() {
                        fieldController.inField = true;
                    });
                });
            }, 1);

            fieldController.isUserEditing = function () {
                return fieldController.inField && fieldController.$dirty;
            };

            fieldController.isInvalid = function () {
                return !fieldController.isUserEditing() && fieldController.$invalid;
            };
        }
    };
}`

DatePickerDirective:
`template:
            '<div class="datepicker tooltip-wrapper" opp-validation-helper="{{modelName}}" uib-tooltip="{{disabledTooltip}}" tooltip-enable="pickerDisabled" tooltip-placement="{{disabledTooltipPlacement}}">' +
                '<input ng-class="{\'field-error\': isInvalid()}" ng-model="model" id="{{modelName}}" name="{{modelName}}" uib-datepicker-popup="{{format}}" /><div class="field-error-message" ng-show="isInvalidDate()" ng-bind-html="validationMessage"></div>'`

More of DatePickerDirective, this is the important stuff, as I showed above.
`function isEmpty() {
     return ctrl[scope.modelName].$viewValue === '';
};
scope.isInvalid = function () {
    return !isEmpty() && ctrl[scope.modelName].isInvalid();
};

scope.isInvalidDate = function () {
    return !isEmpty() && ctrl[scope.modelName].isInvalid() && ctrl[scope.modelName].$error.date;
};
var input = angular.element(element).find('input');
input.bind('blur', function() {
     if (input.val() === '')
           ctrl[scope.modelName].$setValidity('date', true);
});
`


Usage of DatePickerDirective:
`<opp-date-picker model="bankAccountSearchController.bankAccountStartDate" input-name="bankAccountStartDate" format="@UserManager.Identity.UsableDateFormat" validation-message="@Common.NotAValidDate"></opp-date-picker>`

I hope this makes some sense. I've cut a bunch of code out to condense it, but it's been a few months since I dealt with this code so it's not fresh in my mind. You will likely be unable to copy/paste the above into your project to make it work, you will have to figure out your own solution.

**Comment by DavidRogersDev** [comment]
I totally agree with rythos42. 
**An empty date is definitely an invalid date, but it is not necessarily an invalid datepicker.**

**Comment by carmelolg** [comment]
This behavior is really strange.
For me an empty date could have a lot of meanings, maybe for my application I want that "null" or empty date is looked as infinite date or something else.

**I think that users have to be leaved free in this decision.**

**Comment by saratbhaswanth** [comment]
+1

**Comment by raunakmali** [comment]
Setting ng-required="false" to input fields allows you to have empty value and doesn't show red border

**Comment by mindietea** [comment]
I'm confused as to how this behavior is intended?

If you have a datepicker input with required set to false, and you leave it empty, the input should be considered still valid. Sure the input is not a Date but shouldn't the input be empty OR a valid date? Yet the input and thus the entire form is invalidated and this makes things incredibly messy when working with form validations.

I kind of see where you're coming from that the invalid date class is attached due to empty not being a valid date, but it's incredibly common to use an optional date field, yet it's really messy to implement.

**Comment by makjoobali** [comment]
+1 If ng-required="false" then empty date should be valid

**Comment by MatheusArleson** [comment]
Any additional information on this issue?
required + empty == invalid
optional + empty == valid

**Comment by oruganti1289** [comment]
setting the initial ng-model attribute value to null removed red line from a invalid date , hope it helps someone who is still working in angular js 💯
