### ISSUE TITLE
Responsive Pagination

### ISSUE THREAD

**Issue by jarzuaga** [angular-ui/bootstrap#4225]
Hi,

I'm wondering if making the pagination control responsive to screen size is something that's on your plans. What I mean is making the number of pages visible adapt to the screen. For example, if I have 100 pages, show 50 at full resolution (with an ellipses to see the next 50) and show maybe 5 or 10 on a smart phone. Something similar to http://auxiliary.github.io/rpage/.

**Comment by icfantv** [comment]
This is an incrediy difficult problem to solve because it relies on walking the DOM to see how much height is actually used so the remaining height can be calculated (and heights applied because overflow scroll doesn't work unless the parent has a fixed height).  Additionally, this is a problem best solved via a layout manager; something that is beyond the scope of the UI Bootstrap library - and really, angular as a whole since there's really no "data binding" that ever occurs.
