### ISSUE TITLE
custom templateUrl appears behind custom windowTemplateUrl in $modal

### ISSUE THREAD

**Issue by StevenDewey** [angular-ui/bootstrap#4232]
I've made a plunker here: http://plnkr.co/edit/xv0LuJ1kqJ1t0BBsP3Ue?p=preview 

In my application this is happening as well. Although it appears to work fine in version 0.12.0. For some reason it seems as though the presence of the custom windowTemplateUrl causes the the templateUrl to be hidden. 

I could have easily missed something in my implementation. I tried to make the plnkr as simple as possible. Let me know what you think. 

-Steven

**Comment by wesleycho** [comment]
This looks like because you didn't include the other necessary components for your custom template - [here](http://plnkr.co/edit/sfTN9H54DgdAyLnxcPW1?p=preview) is a working version of your Plunker.

If you are going to override the window template, check out the original template https://github.com/angular-ui/bootstrap/blob/master/template/modal/window.html .
