### ISSUE TITLE
[tabs] : inside the tab datepicker is not showing after first time 

### ISSUE THREAD

**Issue by krisurnok** [angular-ui/bootstrap#4258]
inside the tabs datepicker is given,first time  showing datepicker then clicking button it not showing .

http://plnkr.co/edit/7YKNL1N1nyObIrxlrAMw?p=preview

**Comment by krisurnok** [comment]
in ui-bootstrap-tpls-0.10.0.js its working  ,current master is not working

**Comment by wesleycho** [comment]
Doing some investigation, this appears to be a broken scope issue, as can be seen [here](http://plnkr.co/edit/2XtWX2Ck2qRaH3VFJ0Uy?p=preview) - I'm going to close this as won't fix, since given how the tabs work, this is not something we should support. If one wants to use a datepicker in a tab, one should have the controller inside the tab or use a directive which manages the scope of that particular tab.

**Comment by mrudult** [comment]
Well this can fixed by doing:
```javascript
$scope.open = function($event, elementOpened) {
    $event.preventDefault();
    $event.stopPropagation();
    $scope.datePicker.opened = !elementOpened;
};
```
Focus on `elementOpened` :)
