### ISSUE TITLE
Parent context keeps a reference on destroyed children through closures

### ISSUE THREAD

**Issue by yoann-antoviaque** [angular-ui/bootstrap#4298]
While looking for memory leaks in our application I noticed references to destroyed contexts, preventing them from being garbage collected:

line 2149:
  $scope.$on('$destroy', function() {
    scope.$destroy();
  });
line 4805:
      var scope = originalScope.$new();
      originalScope.$on('$destroy', function(){
        scope.$destroy();
      });
both keep a reference to child scope, those listener should be removed when child scope is destroyed:
  var offDestroy = $scope.$on('$destroy', function() {
    scope.$destroy();
  });
  scope.$on("$destroy", offDestroy);
and
      var offDestroy = originalScope.$on('$destroy', function(){
        scope.$destroy();
      });
      scope.$on('$destroy', offDestroy);

**Comment by pkozlowski-opensource** [comment]
> line 2149:

Line numbers are not very helpful without knowing which version you are using :-(
Would be good to provide more context: https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug

How about sending a pull request to this repo since you've got already the issue identified?

**Comment by yoann-antoviaque** [comment]
Sorry I forgot the version number... I was referencing the latest but will send a pull request

**Comment by yoann-antoviaque** [comment]
pull request: https://github.com/angular-ui/bootstrap/pull/4299
