### ISSUE TITLE
Right alignment is off for dropdown-append-to-body .dropdown-menu-right when there's a vertical scrollbar

### ISSUE THREAD

**Issue by ilameda-RA** [angular-ui/bootstrap#4317]
This is related to issue #3820 
https://github.com/angular-ui/bootstrap/issues/3820

The right alignment is off when there's a scroll bar. 
Demo link: http://plnkr.co/edit/y6qOfyjM54YE8Ft1Vxj6?p=preview

Both dropdowns have dropdown-menu-right.
The first dropdown has the dropdown-append-to-body white the second doesn't.

If the height of the "TRIGGER SCROLL" div is changed to 200px, for example, then the alignment is fine in both dropdowns.

The alignment should be the same in both scenarios

Thanks

**Comment by wesleycho** [comment]
@RobJacobs given your scrollbar work, I'm pointing you to this issue for comment :) .

**Comment by almeidap** [comment]
This fix solves the positioning problem with right-aligned dropdown menus but the menu position is not correctly updated when a window resize occurs and the Bootstrap grid collapses.

You can see the issue here if you open the first dropdown menu and shrink the window until grid collapses:
http://plnkr.co/edit/l2wW2ydgnRVuV86q8TEV?p=preview
