### ISSUE TITLE
popover.html throws compile error...

### ISSUE THREAD

**Issue by jonfasking** [angular-ui/bootstrap#4323]
Error: [$compile:tplrt] Template for directive 'popoverPopup' must have exactly one root element. template/popover/popover.html
http://errors.angularjs.org/1.4.5/$compile/tplrt?p0=popoverPopup&p1=template%2Fpopover%2Fpopover.html
    at REGEX_STRING_REGEXP (angular.js:68)
    at angular.js:8418
    at processQueue (angular.js:14634)
    at angular.js:14650
    at Scope.$get.Scope.$eval (angular.js:15878)
    at Scope.$get.Scope.$digest (angular.js:15689)
    at Scope.$get.Scope.$apply (angular.js:15986)
    at done (angular.js:10511)
    at completeRequest (angular.js:10683)
    at XMLHttpRequest.requestLoaded (angular.js:10624)

Right out of the box.... Just updated it from an older version. The directive that is using the template at template/popover/popover.html is complaining about a root element because of the replace:true.

**Comment by icfantv** [comment]
I suspect it's your use of the popover directive.  `replace:true` can break the DOM if not used correctly which is why the Angular team had deprecated its use - though it will not be pulled from the code base.

That said, it's impossible to debug without further information from you.  Can you please create a plunker that shows this issue or gist your code and link it here?  Thanks.

**Comment by jonfasking** [comment]
icfantv,

You were correct, it was how I was using the directive. I was wrapping that directive in my own and how I was declaring the template in my own directive (which contained the popover directive) was throwing that error. Thank you for your insight.

**Comment by icfantv** [comment]
Sure thing.
