### ISSUE TITLE
NuGet Package for version 0.13.4

### ISSUE THREAD

**Issue by pascalberger** [angular-ui/bootstrap#4338]
Please update the NuGet Package to version 0.13.4. Thanks!

**Comment by Foxandxss** [comment]
https://www.nuget.org/packages/Angular.UI.Bootstrap/

That seems to be upgraded.

And none of the actual core team is responsible for nuget I am afraid, so you would need to ask to the package maintainers if this happen again.

**Comment by icfantv** [comment]
It appears Pawel is on the list of authors for the project.  But that said, as @foxandxss notes, we are not responsible for updating nuget.

**Comment by pascalberger** [comment]
Thanks! I'll chase the maintainers of the NuGet package directly in the future

**Comment by icfantv** [comment]
I think it's already out there...

**Comment by xt0rted** [comment]
I used to get notifications when a new release was made to either [angular-ui/bootstrap-bower](https://github.com/angular-ui/bootstrap-bower/) or this repo but that hasn't happened for awhile. Now I need to check the releases page to see if a new one has been made which is why I don't publish the updates as quickly as I used to.

**Comment by wesleycho** [comment]
@xt0rted would it help if we contacted you each time there was a release? Feel free to send me an email to my email address listed on GitHub if you would like me to do so.
