### ISSUE TITLE
Prevent modal from scroll to top when opening

### ISSUE THREAD

**Issue by NetanelBasal** [angular-ui/bootstrap#4355]
When i open the modal when i am not at the top of the page, it automatically go to the top of the page and then open the modal.

How can i stay in the same position and open the modal?

**Comment by icfantv** [comment]
I am unable to reproduce this and [our demo](http://angular-ui.github.io/bootstrap/#/modal) works fine.

If you can reproduce this in a plunker, please feel free to reopen this issue, otherwise, for support issues, please follow the instructions [here](https://github.com/angular-ui/bootstrap#support).  I would encourage the use of StackOverflow.
