### ISSUE TITLE
Popover template with html templates shows template contents outside popover

### ISSUE THREAD

**Issue by kruser** [angular-ui/bootstrap#4422]
I have a popover template that contains another directive, like

```
<div><my-directive></my-directive></div>
```

myDirective loads some data asynchronously over http, then binds the response properties to some elements. For a split second, the contents of the popover are outside of the popover.
![image](https://cloud.githubusercontent.com/assets/2208700/9896076/c9d83e62-5bfc-11e5-994c-0a02e3141fb7.png)

Then it snaps into place afterwards.
![image](https://cloud.githubusercontent.com/assets/2208700/9896080/d023104e-5bfc-11e5-88e4-d8ffcc998a29.png)

These screenshots were taken from a snapshot build of master.

**Comment by dfsq** [comment]
Can you create a demo? It might be the problem with your directive too.

**Comment by kruser** [comment]
@dfsq - sure, I put it in a plunkr. 
http://plnkr.co/edit/AcfbEOvzhrAsSJYLZvn9?p=preview

Here's how it shows up there.
![image](https://cloud.githubusercontent.com/assets/2208700/9907879/ccc789b6-5c56-11e5-80b6-771205f8ca51.png)

**Comment by icfantv** [comment]
IMO, the problem here is that you are not injecting the dependency you need ahead of time similarly as to what one would do for routing - or you are not controlling when the tooltip shows.

There are two solutions here:

1.  Preload the data in a service and inject it in your directive.
2.  Use the `popover-is-open` attribute to programmatically control when the popover is opened/closed.

Note that the problem with number 2 is that if you have any network lag, the UX is crappy.  Another thing you could do is change your popover template to add a please wait spinner or something.

**Comment by kruser** [comment]
@icfantv - that's too bad. I was hoping the template addition to popover would allow me to use any directive seamlessly in popovers.

> Preload the data in a service and inject it in your directive.

My requirement is to defer loading of data until we know the user wants that specific data, i.e. they hover over something of interest. So that's a non-starter.

I'll throw a pull-request your way if I have time to dig into a solution. I don't think the problem is with the $http call for json data necessarily, more so with the template loading asynchronously.

**Comment by kruser** [comment]
I updated the plunkr to control the size and overflow of the popover. This gets by my issue.
http://plnkr.co/edit/AcfbEOvzhrAsSJYLZvn9?p=preview

**Comment by icfantv** [comment]
I think I may have missed the original issue.  Can you please test this against `master` and see if it's still an issue?  Thanks.

**Comment by kruser** [comment]
Yes, I can reproduce the same thing on master.

**Comment by icfantv** [comment]
@kruser, I've discussed with the other project devs and we feel this is an error on your end.
