### ISSUE TITLE
Datepicker does not validate when bound to a ISO date string?

### ISSUE THREAD

**Issue by bp5800** [angular-ui/bootstrap#4424]
The date picker no longer validates when it is passed an ISO date string. 
[Plunk](http://plnkr.co/edit/ecBKERzfRpMnk2aiILR7?p=preview)
This is a consequence of [#4062](https://github.com/angular-ui/bootstrap/pull/4062).

**Comment by wesleycho** [comment]
The PR linked makes it clear - we are no longer supporting that due to various cross-browser issues & more.

**Comment by bp5800** [comment]
The PR makes it clear you don't want to accept any string that the browser interprets as a date using new Date().

I'm getting dates from a web service in this format. It seems this would be fairly common. It seems to me you should be able to handle this particular format.

**Comment by wesleycho** [comment]
Problem is that different browsers will even handle ISO dates in different and unexpected ways - it also overly complicated the model-view interplay with ng-model. The best workaround on the user's side is to convert it to a date object before binding to the model - for any properly built application, this should be a trivial change since there should always be a parsing layer that converts the api response before binding to a model.

**Comment by bp5800** [comment]
Okay, I will (with regret) leave it at that. Thanks.

**Comment by almeidaalex** [comment]
I'm facing this issue right now.. I've changed version from 0.12.0 to 0.13.5.The Date format came from server as "2015/09/17 15:50", for example, and it worked, however since I've changed version it no longer works anymore, the model is invalid
So, I noticed that throughout the comments that I must parse date format, to work with 0.13.4 version, is it ?
