### ISSUE TITLE
Changing input value, not change model value

### ISSUE THREAD

**Issue by requtize** [angular-ui/bootstrap#4433]
When we change value of input directly from browser, alert shows still old value (default value defined in controller scope). The same code, but without AngularUI works as expected.

http://plnkr.co/edit/G8oV5Arar4vWDtbASp5U?p=preview

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular-ui/bootstrap/wiki/FAQ#my-input--select-element-doesnt-work-as-expected-inside-the-tab--accordion-directive

**Comment by icfantv** [comment]
This is because tabs have an isolate scope and you're not using dot-notation on your model.

**Comment by icfantv** [comment]
Whoops, @pkozlowski-opensource, you beat me to it.  :-)

**Comment by icfantv** [comment]
@requtize, just a note that you may want to consider giving each of your tabs their own controller rather than wrapping them all with one giant one.  to be sure, you can still wrap it with one - just watch the amount of work that that tab is actually doing.  you probably want to restrict it to just providing the information for the tabs.
