### ISSUE TITLE
Stop / Default pagination to pre-defined page number on initialization / load

### ISSUE THREAD

**Issue by jamespsterling** [angular-ui/bootstrap#4434]
Looks like the pagination is setting the page to 1 when it's generated on the page. Is there a way to stop this default action?

**Comment by pkozlowski-opensource** [comment]
Could you elaborate? It is not clear what you mean here.

**Comment by icfantv** [comment]
@jamespsterling, do you mean that you would like to control the selected page when the directive is first rendered?  If so, take a look at our plunker example for pagination [here](https://angular-ui.github.io/bootstrap/#/pagination) (the blue button).

**Comment by bramcordie** [comment]
This only happens when you use the items-per-page attribute, see plunker: http://plnkr.co/edit/HoStFd9m0EdsQCZgwJcr?p=preview.

The initial page value will be overwritten to 1 and a change event occurs. My current work-around is to use an intermediate view value to silence the first change event and revert the view based on the actual model value.

**Comment by huguangju** [comment]
already resolved in #3118 . add `ng-if`  to check `totallItems`  whether exist.
```html
<div ng-if="totalItems">
  <pagination ...>
</div>
```

There are some explanations: http://www.ngroutes.com/questions/1a9e63c/ui-bootstrap-pagination-resetting-current-page-on-initialization.html

**Comment by icfantv** [comment]
Closing due to above explanations and lack of response from original author.
