### ISSUE TITLE
replace typeahead filter function 

### ISSUE THREAD

**Issue by felipembbraga** [angular-ui/bootstrap#4484]
Hi,

I'm brazilian and my natural language is portuguese. In our language, there are many words that use accents and other Unicode characters. To make the search easier, we generally use a filter that replaces the accented character by not accented. Example:

ó -> o, ã -> a, ç ->c.

How can I customize the results filtering function to accept these replaces?

PS.: Sorry for my english.

**Comment by wesleycho** [comment]
I think your best solution would be to create a custom template that uses your custom filter.

**Comment by felipembbraga** [comment]
No, because i don't wanna to "show" the character without accent. 
An example to illustrate:
When I type 'espanol', the component must show 'español' in your filter list.

**Comment by wesleycho** [comment]
This is a user-side modification - you can make the modification by using the appropriate filter with Angular. This is independent of the typeahead.

Closing, as either this is not being made clear or an understanding of how to use the typeahead is lacking. This issue seems more appropriate for StackOverflow than here as far as I can understand.
