### ISSUE TITLE
Accordion tabindex

### ISSUE THREAD

**Issue by PetrusStarken** [angular-ui/bootstrap#4538]
I need an option to manually set the tabindex option for the link of accordion-group. I've made this change on my fork (https://github.com/PetrusStarken/bootstrap), it's working well for me, but, I'm beginner with AngularJs, so, can someone take a look in my changes to see if everything is ok?

Any suggestion is welcome.

**Comment by icfantv** [comment]
Hi @PetrusStarken, please do not use the issues forum for support requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

You were oh so close to the right code and probably just missed it.  If you take a look at [the docs](http://angular-ui.github.io/bootstrap/#/accordion) for accordion, you'll see the `template-url` option which allows you to override the default template and provide your own.  This is, in essence, exactly what you've done, but your solution is quite heavy handed.  If you like the existing `accordion-group.html` template, copy it, make your modifications, and use it instead of the default.

If you need that tab index parameter to be configurable, you'll need to create a wrapper directive around your template in order to get it into the template as we don't support passing extra attributes to the directive.

**Comment by PetrusStarken** [comment]
Thanks for the response, I'll pay more attention next time.
