### ISSUE TITLE
need archive versions of docs more accessible

### ISSUE THREAD

**Issue by ChadStrat** [angular-ui/bootstrap#4565]
As the project grows in adoption there is an increasing need for archive docs readily available.  Our application has over 40,000 files and updating libraries is not quite as easy as some.  We work to update as often as possible, but majority of the time, because of the size of our app, library updating can take one to two weeks, sometimes three depending on bugs and QA.  All library updates have to go through build servers, testing, fixes, and then deploy.  More often than not, we simply can not afford this lifecycle update routine for every point release.  PLEASE please please find/make a way for archive docs for at least 2-3 versions.  If you want your project used in large-scale enterprise applications, this is a must.

**Comment by wesleycho** [comment]
This may take us a while since the release process (including documentation updates) is very much manual currently & we started work on converting to angular 2 - unfortunately we are in huge need of manpower.

If it is a pain point for a major project for a major company, it would be extremely helpful if developer resources could be spared to help implement a build process that could accommodate this feature. Otherwise, there are other major issues & interests that we have to balance this with, including how costly each feature request is vs. gains - all of us on the project contribute on our spare time (and several team members work at large companies).

For now, the autogenerated [change](https://github.com/angular-ui/bootstrap/blob/master/CHANGELOG.md) should help with what changed.

**Comment by Foxandxss** [comment]
Closing for duplicated. Anyway I hope to fix this real soon. #3670

**Comment by Foxandxss** [comment]
I fixed this.
