### ISSUE TITLE
Typeahead does not open

### ISSUE THREAD

**Issue by lehnen** [angular-ui/bootstrap#4609]
I tried to isolate the issue on http://cmadmin.abs-net.de/typeahead
The source is based on the plunker demo site. I think I could be dependency problem, but I could not fugure out it up to now. 
I included jquery, bootstrap and some angular modules that I need from my project. 

Maybe someone could help me - or detect a real issue in the ui-bootstrap code.

**Comment by icfantv** [comment]
please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

Unfortunately, if you think you have found a bug and do not follow the above instructions within a reasonable amount of time, we will close the issue due to lack of activity.
