### ISSUE TITLE
Printing the Accordion -() appearing in the print preview as well as printed page

### ISSUE THREAD

**Issue by pendliforu** [angular-ui/bootstrap#4619]
![print](https://cloud.githubusercontent.com/assets/8366546/10488708/f8f9394a-7267-11e5-9f68-904925bd0717.JPG)

Am trying to print the Bootstrap accordiion content ,after i print there is a () appearing in the print in all the browsers am not able to figure that out what  exactly that is

**Comment by icfantv** [comment]
@pendliforu, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

Unfortunately, if you think you have found a bug and do not follow the above instructions within a reasonable amount of time, we will close the issue due to lack of activity.
