### ISSUE TITLE
Printing the Accordion -() appearing in the print preview as well as printed page

### ISSUE THREAD

**Issue by pendliforu** [angular-ui/bootstrap#4620]
![print](https://cloud.githubusercontent.com/assets/8366546/10489312/8f8d7aea-726a-11e5-8f7e-260ca5642e93.JPG)

Am trying to print the Bootstrap accordiion content ,after i print there is a () appearing in the print in all the browsers am not able to figure that out what exactly that is

**Comment by icfantv** [comment]
@pendliforu, this is the second time you posted this.  Please stop.

Do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

Unfortunately, if you think you have found a bug and do not follow the above instructions within a reasonable amount of time, we will close the issue due to lack of activity.

**Comment by shershen08** [comment]
That can be fixed by adding to ```@media print``` media query:
```
a[href=""]:after {
    content: "";
}
```
