### ISSUE TITLE
Behaviour of popover-is-open is unpredictable

### ISSUE THREAD

**Issue by BParnikel** [angular-ui/bootstrap#4627]
Hi all,

i have a little question about popover-is-open. If i have a popover with popover-is-open="some_model" and in popover i have button to set this model to false, then i can close popover by click on it. But if i set same handler to button, which actually has popover, then popover is opening despite the fact that some_model is set to false. See example and environment on plunkr: http://plnkr.co/edit/qKJeh5qCUq6qBsqosphf?p=preview

So how can i implement next functionality: i want to open popover when and only when some expression returns true (for example, i have a download modal dialog to save file and i want to show popover with warning only if size of file is greater than some limit)?

Thank you!

**Comment by RobJacobs** [comment]
Questions of this nature should be asked on Stackoverflow, please read the [FAQ](https://github.com/angular-ui/bootstrap#faq) section: Need Help?

The popover is responding to the button click due to the default 'click' trigger that is added.  To use the *is-open attribute exclusively, you need to set the popover-trigger="none" as documented in the [tooltip](http://angular-ui.github.io/bootstrap/#/tooltip) Triggers section.

**Comment by BParnikel** [comment]
@RobJacobs Stackoverflow didn't help me.

Thank you, your solution helped!

**Comment by icfantv** [comment]
@BParnikel, @RobJacobs meant you should follow the instructions we post on how to ask for help and post your question on StackOverflow.  The issues forum is for bugs, not support requests.

**Comment by progmars** [comment]
I have found a related problem but I'm not sure if I should create a new issue for that.

Here is a Plunker example:
http://plnkr.co/edit/ZwQgKgMoQI7MOLNtM8Yl

Essentially, if you have set `popup-delay` and the value of a property bound to `popover-is-open` has been changed to false, then after the delay time passes popover thinks that it should be open because that's what the property was before the delay. 

I think, if using `popup-delay`, popover should check the `popover-is-open` property once more after the delay timeout has passed to avoid showing popover based on out-of-date value of `popover-is-open`.
