### ISSUE TITLE
date picker min-mod="month" select the last day of the month

### ISSUE THREAD

**Issue by kirangsa** [angular-ui/bootstrap#4658]
Hi,
Am using angular bootstrap  datepicker in min mode month. Now its taking the first day of the month. How can i select the last date of the month.

Can any one help one this issue ?

Thanks & Regards,
KG

**Comment by Foxandxss** [comment]
Create a plunker so we can debug it.

**Comment by icfantv** [comment]
@kirangsa, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).

If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

Unfortunately, if you think you have found a bug and do not follow the above instructions within a reasonable amount of time, we will close the issue due to lack of activity.
