### ISSUE TITLE
popover-trigger=focus isn't working on spans, but is working on buttons

### ISSUE THREAD

**Issue by adamzerner** [angular-ui/bootstrap#4679]
`popover-trigger='focus'` isn't working on `spans`, but is working on `buttons`.

http://plnkr.co/edit/sz07Umnl3o87eUSWL5FL?p=preview

**Comment by icfantv** [comment]
@adamzerner, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.

This is because spans are not focusable by default (and by design) in HTML.  If you want this to work in your case, you can add `tabindex="-1"` to make it not tabbable, but focusable and thus, your popover will work.  But, there may be ARIA ramifications to doing this so you may want to do some research and possibly reconsider your design if you need to have any accessibility support.

**Comment by adamzerner** [comment]
> @adamzerner, please do not use the issues forum for support related requests. Rather, please follow the instructions here. The issues forum is reserved for bugs.
I posted here because I mistakenly thought this was a bug; I know for the future to only post bugs here. Thanks for your help though!

**Comment by icfantv** [comment]
Thanks.  And you're welcome.

**Comment by icfantv** [comment]
I should also note that in the future, if you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

**Comment by adamzerner** [comment]
I read that and thought I followed them, no?
