### ISSUE TITLE
'isOpen' of undefined $destroy popover

### ISSUE THREAD

**Issue by therealtomas** [angular-ui/bootstrap#4683]
I thought this was fixed in #4552 but seems not, when destroying a directive this shows:
TypeError: Cannot set property 'isOpen' of undefined

            if (isOpenParse) {
              scope.$watch(isOpenParse, function(val) {
                /*jshint -W018 */
                if (!val === ttScope.isOpen) {
                  toggleTooltipBind();
                }
                /*jshint +W018 */
              });
            }

Shouldnt there be a ttScope check before?

**Comment by RobJacobs** [comment]
Please provide a plunk demonstrating the problem.

**Comment by icfantv** [comment]
@therealtomas, if you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

Unfortunately, if you think you have found a bug and do not follow the above instructions within a reasonable amount of time, we will close the issue due to lack of activity.

**Comment by wesleycho** [comment]
@RobJacobs this seems related to the garbage collection issues we had - we should probably do
```js
if (!ttScope.isOpen || !val === ttScope.isOpen) {
  toggleTooltipBind
}
```
