### ISSUE TITLE
Modal Crashes on iOS

### ISSUE THREAD

**Issue by pontusespe** [angular-ui/bootstrap#4684]
Hey,

Im using this package for hanedeling my Bootstrap functions. I have a modal that popup when a button gets triggered, everything works fine on all mature webbrowsers. The only problem i keep getting is that the webpage refreshes when modal gets triggered on a iOS device. This problem seems to happen more often on an iPad.

Im currently using an iPhone 6+ and an iPad model MD794KS/A.

The only error message i can catch up in the console before the refresh is:

Failed to load resource: the server responded with a status of 404 (Not Found)

My modal:
<script type="text/ng-template" id="myModalContent.html">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" ng-click="cancel()"><span
                    aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Lägg till frågor</h4>
        </div>
        <div class="modal-body">
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-info btn-block" ng-click="cancel()">Finnish</button>
        </div>
    </div>
</script>

The button:
<button ng-click="addQuestionsForm(formid)" class="btn btn-primary btn-sm pull-right"><i class="fa fa-edit"></i> Change</button>

In the controller:
var modalInstance = $uibModal.open({
                animation: true,
                templateUrl: 'myModalContent.html',
                controller: 'ModalInstanceCtrl',
           });

Thank's,
Pontus

**Comment by icfantv** [comment]
@pontusespe, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.

If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

Unfortunately, if you think you have found a bug and do not follow the above instructions within a reasonable amount of time, we will close the issue due to lack of activity.

**Comment by wesleycho** [comment]
This seems app-specific, since I see it working in UI Bootstrap's docs and in a live app for work that uses 0.14.2.

We need a stripped down reproduction for us to do anything here, but I highly suspect user error here.

**Comment by wesleycho** [comment]
Closing due to lack of response - need a reproduction in order to investigate this issue.
