### ISSUE TITLE
Large modal won't mouse scroll on small page

### ISSUE THREAD

**Issue by Janneman84** [angular-ui/bootstrap#4685]
I'm using a modal to show a list that is often bigger than the screen so you need to scroll. However mouse scrolling often doesn't work (using arrow keys still works though).

I found out that this happens when the page behind the modal is smaller than the screen (so it has no scrollbar).

So basically when the page is too small to scroll any modal that you open on it can't be scrolled either even if the modal is too big for the screen.

I already tried this css to always force the scrollbar:
body {
    overflow-y: scroll !important;
}

This doesn't fix the problem, only 'solution' so far is this css:
html {
    height:101%;
}

Which I 'improved' to doing this when the modal opens (coffeescript):
$('html').css('height', '101%')
@timeout ->
	$('html').css('height', '100%')
, 300

I haven't tried the new $uibModal yet.

Any else encountered this issue?

**Comment by icfantv** [comment]
@Janneman84, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.

If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

Unfortunately, if you think you have found a bug and do not follow the above instructions within a reasonable amount of time, we will close the issue due to lack of activity.

**Comment by wesleycho** [comment]
It is up to the user to control the CSS - my recommendation would be to use `max-height` on the modal to control the viewport for smaller screens.

Closing as a usage issue.

**Comment by Krisa** [comment]
I'm having this problem too, though only on Windows and on Chrome (not tested in IE). On Firefox in Windows it's fine, and on Mac there is no problem either (both Chrome / Firefox). Both solutions proposed work (either setting an height in the modal, or making the body height at 101%) but these solutions are more workarounds than a solution and making such a workaround for just 1 browser for 1 platform (affecting everything else) is a bit awkward. 

I understand it's a CSS issue, but the uibModal is much about CSS ... :)

A plunkr: http://plnkr.co/edit/qkgRpZlVGy5hSfygMwNz?p=preview

You need to "Launch the preview in a separate window" in Windows/Chrome for seeing the issue. In the embedded Window, it scrolls well.
