### ISSUE TITLE
Date Picker not able to differentiate b/w invalid date and no date.

### ISSUE THREAD

**Issue by goyatparmod** [angular-ui/bootstrap#4703]
I need to accept correct date or blank in my ng-modal. But date picker supply me undefined if date is wrong as well as even if its blanks. So my application logic not able to differentiate b/w invalid date and blank date. I wish i could get null in return if date is blanks and undefined is dates are wrong.

**Comment by icfantv** [comment]
@goyatparmod, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.

If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

Unfortunately, if you think you have found a bug and do not follow the above instructions within a reasonable amount of time, we will close the issue due to lack of activity.

**Comment by icfantv** [comment]
Actually, on second thought, I'm closing this as a support-only issue.  If you feel this is incorrect, please follow the instructions above and we will consider reopening if valid.
