### ISSUE TITLE
uib-accordion is not working

### ISSUE THREAD

**Issue by tempx** [angular-ui/bootstrap#4726]
Hi,

To try the features of uib-accordion I have downloaded the files supplied by you in the Plunker. Although uib-accordion is working in the Plunker, uib-accordion in the files I have downloaded are not working on IE, Chrome and Opera browsers. 

Can you please check the files you have uploaded? What may be the problem?

Also can you please supply more information about uib-accordion?(e.g. in your example I could not find any information about "status.open" variable. Also "is-open" is not working to show/hide the glyphicons in the header.)

I will be glad if you can provide an extensive and complete solution for uib-accordion. 

Regards,

**Comment by icfantv** [comment]
@tempx, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.

I suspect the files you've downloaded are not correct or you have a bug in your code.  Unfortunately, you've given us nothing via which to help you debug so it would be impossible to provide any meaningful assistance.  You might start with the browser debugger and see if you're getting any errors in the console.

**Comment by tempx** [comment]
Hi @icfantv, thank you very much for your answer. Unfortunately I can not give the punker link since it is not provided in the website. However, I can describe how to get the files: when you go the "Accordion (ui.bootstrap.accordion)" section click on the "Edit on plunker" button and then download to files to your locale and try to run the index.html. You will see that the supplied accordion code is not working. 

I am not using the of mine, rather the code supplied in the website. There may be a problem with the files you have uploaded or there may be a bug in the accordion. Can you please recheck the code and the files you have provided in the website?

Regards,

**Comment by icfantv** [comment]
@tempx, the content of the plunkers is auto-generated and a real link is created once the plunk is saved.

While we here on the Angular UI Bootstrap team like to think we're a pretty smart bunch, we are not clairvoyant.  Try as we might, we cannot read your mind to know what exactly "is not working."  Until you provide specifics and a plunker that demonstrates exactly the issue you are having, we cannot help you.

**Comment by Andrew-By** [comment]
I've figured out that the "angular-animate" dependency is not mentioned anywhere on the web site, you can notice it only in Plunker example. Without that package uib-accordion don't work.

**Comment by Foxandxss** [comment]
So let me explain how this work (this applies to all angular libraries, not just ui-bootstrap).

All the animations in angular are optional (which is good). So what Angular did is bring all the animation API to the core library (stuff like `$animate` and `$animateCss`).

So when angular runs any of those, it will check if the animation **external** module is loaded, if so, it will  do the animations, if not, angular will skip them.

To load the external animation module, you load its `.js` in a script tag and then you add it as a dependency in your module:

```javascript
angular.module('foo', ['ngAnimate']);
```

By doing that, angular will execute all the animations now.

I guess you simply removed the script tag and tried. That will raise an error because you are still loading the module as dependency and it is nowhere found. If you remove that `ngAnimate` from the demo module (the .js is optional to remove) you will see that it works:

http://plnkr.co/edit/oFRAtCMrR8hA51J8R2HG?p=preview

On the other hand, I will add that to the homepage, doesn't hurt.

**Comment by Andrew-By** [comment]
Oh, yes, thank you. I just realized that, so I deleted my post :)
