### ISSUE TITLE
Modal window closed too late

### ISSUE THREAD

**Issue by erkanarslan** [angular-ui/bootstrap#4727]
When I call `$uibModalInstance.dismiss()` modal window is closed immediately. However, if I click the backdrop, it takes up to 8 seconds for modal window to close.

This started to happen after I migrated from version 0.13.4 to 0.14.3.

**Comment by kukac7** [comment]
http://plnkr.co/ examples please?

**Comment by icfantv** [comment]
@erkanarslan, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.

If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

Unfortunately, if you think you have found a bug and do not follow the above instructions within a reasonable amount of time, we will close the issue due to lack of activity.
