### ISSUE TITLE
Alert dismiss-on-timeout does not support data binding

### ISSUE THREAD

**Issue by zjkyz8** [angular-ui/bootstrap#4729]
After update bootstrap to 0.14, I found dismiss-on-time directive does not support data binding, I have to use same time for different mssage.

**Comment by icfantv** [comment]
@zjkyz8, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.

If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

Unfortunately, if you think you have found a bug and do not follow the above instructions within a reasonable amount of time, we will close the issue due to lack of activity.

**Comment by Foxandxss** [comment]
That got fixed in the latest version
