### ISSUE TITLE
Accordion with button in the header

### ISSUE THREAD

**Issue by kasarun** [angular-ui/bootstrap#4777]
I just update from 0.13.0 to 0.14.3.
Now when i click on a button in uib-accordion-heading the page reload if the handler have an event.stopPopagation().
Here is a plunker :
plnkr.co/edit/187zWiPMX37IVMK6A8tF?p=preview

**Comment by icfantv** [comment]
@kasarun, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.

If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

Unfortunately, if you think you have found a bug and do not follow the above instructions within a reasonable amount of time, we will close the issue due to lack of activity.

-----------------

Also, please do a search of both open and closed issues before entering anything as, given the maturity of this library, it is likely your issue has come up before.  In this case, it has with #3299 and #3145.

**Comment by icfantv** [comment]
Linking issues, #5361, #4533, #4104, and #3199.  For the relevant conversation in Bootstrap, see [this thread](https://github.com/twbs/bootstrap/issues/18975).
