### ISSUE TITLE
$uibModal injects $modalInstance instead of $uibModalInstance

### ISSUE THREAD

**Issue by SamiTriki** [angular-ui/bootstrap#4778]
I'm currently using ui-bootstrap version '0.14.2', I created a modal associated with a controller, I tried to inject $uibModalInstance as in the docs, but I get an Unknown provider error, while simply injecting $modalInstance works, this might have to be updated.

Thanks

**Comment by icfantv** [comment]
@SamiTriki, in the future, if you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

Unfortunately, if you think you have found a bug and do not follow the above instructions within a reasonable amount of time, we will close the issue due to lack of activity.

Please try against a build from `master` as we have removed all deprecated code in the 1.0 SNAPSHOT release.  You can perform a custom build by cloning the repo and executing `npm install` followed by `grunt`.

**Comment by wesleycho** [comment]
In 0.14.3, `$uibModalInstance` support was added.

**Comment by SamiTriki** [comment]
Cheers
