### ISSUE TITLE
Close mutually exclusive dropdowns

### ISSUE THREAD

**Issue by matthieusieben** [angular-ui/bootstrap#4790]
It would be nice to be able to close all the dropdown menus when a new one is opened

    <div uib-dropdown dropdown-tag="top_bar">[TOP MENU 1]</div>
    <div uib-dropdown dropdown-tag="top_bar">[TOP MENU 2]</div>

When opening a menu, all the other menus with the same tag would be closed.

**Comment by icfantv** [comment]
@matthieusieben, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.

If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

Unfortunately, if you think you have found a bug and do not follow the above instructions within a reasonable amount of time, we will close the issue due to lack of activity.

This is already implemented as can be seen in [our demo page](http://angular-ui.github.io/bootstrap/#/dropdown).

**Comment by matthieusieben** [comment]
-_- This is not a support related request. This is a feature request.
If the feature exists then its not documented.

**Comment by icfantv** [comment]
Gah.  I really need to read thoroughly first.

You are talking about selective closing of menus based on a group.  This is pretty poor UX given that dropdowns are meant for performing an action (navigation, etc...).

**Comment by icfantv** [comment]
Yea, sorry about that.

**Comment by matthieusieben** [comment]
Yeah but if you have two dopdowns and a user opens a new one, if would be nicer to close the previous one. Or at least be able to do that.

**Comment by icfantv** [comment]
When you describe it like that, my original comment about our demo page holds.  When you open one dropdown and then open another, the first one closes.

**Comment by icfantv** [comment]
You should never have two dropdowns open.  I'm trying to think of a use case and I can't think of one.  I'm happy to be enlightened however.

**Comment by matthieusieben** [comment]
My bad, i am using popover, not dorpdowns.

**Comment by matthieusieben** [comment]
If i have a dropdown openend and i open a popover, then the dropdown is closed.
The opposite is not true (opening a dropdown does not close the popover).

**Comment by icfantv** [comment]
Hah.  In that case, you can use the `*-is-open` property to programmatically open and close the tooltip/popover as you see fit.  Or you can just use the built in triggers if they suffice.

**Comment by icfantv** [comment]
I just checked this on our demo page.  If you have a dropdown open and are using the `mouse*` triggers, the dropdown stays open.  If you use a `click` trigger, it will close.  I didn't test the `focus` trigger.

**Comment by matthieusieben** [comment]
I believe that the source of my issue is that dropdown are closed when you click anywhere else on the dom. Popover aren't.

Does this mean that i should add a custom event listener on document for every popover element if I want to close them on document clicks ?

**Comment by BobbieBarker** [comment]
What this means is that you should open an issue on SO as described by the [contributing](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md) guidelines to this repository. These issue pages aren't here for support related questions as icfantv previously pointed out.

**Comment by matthieusieben** [comment]
Forget it, I'll just do it myself. Thanks for the quick answer.

**Comment by icfantv** [comment]
@matthieusieben, you **REALLY** need to look at the examples page.  The `focus` trigger on popovers will close a dropdown.  Look at the **Triggers** section of [popovers](http://angular-ui.github.io/bootstrap/#/dropdown).

**Comment by matthieusieben** [comment]
Clicking anywhere in the dom will indeed close a dropdown. Clicking anywhere in the dom will not close a popover. In order to close a popover when another dom element is clicked, i need to set a variable in `popover-is-open`, and make that variable false when another part of the dom is pressed. I do not see an option allowing me to do that in another way than creating an event listener on the dom. Using `popover-trigger` with a value of `focus` is not suitable in my case as i want to be able to click _inside_ it without it being closed.

**Comment by icfantv** [comment]
@matthieusieben, what trigger are you using for your popover?  If you use the `focus` trigger, the popover will close.  If you're using the `click` trigger then the only thing that will close it is clicking on it again.

Just a note that you either use the built in triggers or you use `*-is-open` - not both.

**Comment by icfantv** [comment]
Then in your case, you might have to do a DOM level event handler.  I get this stinks, but popovers weren't originally designed to be interactive.  There may be a way for you to wrap the popover directive that lets you add a focus handler whose purpose is toggle the `popover-is-open` property.  But I haven't investigated this.

And at this point, this question IS a support-related question better suited StackOverflow because you have a MUCH wider audience.
