### ISSUE TITLE
Strangeness with tabs, won't render my directive in it

### ISSUE THREAD

**Issue by vprasanth** [angular-ui/bootstrap#4819]
So I have a directive that has compile function that adds text to the inner html of the element it is a tag on, i..e 

```html
<span my-directive></span>
==
<span>some text, may have an anchor tag in it too</span>
```

However, when I try to use it within the `uib-tab` the span does not have the content. If I print out the actual element form the directive to the console I can see it does have my update? I'm obviously doing something terrible with my directive :S Any help would be appreciated. 

Thanks!

**Comment by icfantv** [comment]
@vprasanth, please do not use the issues forum for support related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.

**Comment by icfantv** [comment]
Also, when requesting help (even on StackOverflow), having a minimal and working plunker is essential in someone being able to assist you - otherwise it's basically impossible and we'd just be guessing.

That said, my first guess is that you're probably running into [this](https://github.com/angular-ui/bootstrap/wiki/FAQ#my-input--select-element-doesnt-work-as-expected-inside-the-tab--accordion-directive) issue.

**Comment by vprasanth** [comment]
@icfantv sorry and thank you for the link!
