### ISSUE TITLE
Carousel not working within a modal (with ngAnimate)

### ISSUE THREAD

**Issue by Luddinus** [angular-ui/bootstrap#4861]
Hi.

I'm trying to show a carousel within a modal but it does not work with ngAnimate.

Here is the "non-working" plunkr: http://plnkr.co/edit/3KoiOJPLTJsxDqgvmp9v?p=preview

Why is this happening?

Thx.

**Comment by wesleycho** [comment]
I believe this is an ngAnimate regression in 1.4 in Angular, but I need to investigate this in detail.

**Comment by shprink** [comment]
I have the same problem :(

**Comment by wesleycho** [comment]
So this turns out to be a very subtle Angular gotcha - one should always bootstrap the app to the `body` element or higher (i.e. `html` or `document`) due to how ngAnimate works.

[Here](http://plnkr.co/edit/8AkPw8qmtnfPo36JBPvz?p=preview) is a Plunker with the fix by moving `ng-app` to the `body` element.
