### ISSUE TITLE
Tag uib-tab-heading finally present 

### ISSUE THREAD

**Issue by hmillet** [angular-ui/bootstrap#4897]
I've noticed that, when  using <uib-tab-heading> for defining a rich tab heading text,
this tag stay finally present in the HTML source page.

You can check for that in your demo page (https://angular-ui.github.io/bootstrap/#/tabs) with the "Alert" tab.

Is this the expected behaviour ? 

Because <uib-tab-heading> is not really an official tag in the HTML5 specifications...

**Comment by icfantv** [comment]
@hmillet, sorry, it's not at all clear what you're asking.  what tag?  the spec does allow for a `data-` prefix on element and attribute names and both Angular and Angular UI Bootstrap take this into account.

**Comment by hmillet** [comment]
@icfantv 

Just have a look at this html code, that I paste from your demo page when I inspect "Alert !" tab

``` html
<li ng-class="{active: active, disabled: disabled}" select="alertMe()" class="ng-isolate-scope active">
  <a href="" ng-click="select()" uib-tab-heading-transclude="" class="ng-binding">
    <uib-tab-heading class="ng-scope">
       <i class="glyphicon glyphicon-bell"></i> Alert!
    </uib-tab-heading>
  </a>
</li>
```

you can see an ```<uib-tab-heading>``` (that what i called "tag").
I think that such a tag should be transformed to an official HTML5 tag by your directive.

**Comment by BobbieBarker** [comment]
I think you're wrong and that's not really how angular works.

**Comment by BobbieBarker** [comment]
Are you suggesting we prefix all of our custom elements with "data-"
?

**Comment by RobJacobs** [comment]
I think what @hmillet is pointing out is the element:

    <uib-tab-heading></uib-tab-heading>

is a non-standard html tag.  Your going to see a lot more of these non-standard html tags in the future as angular is deprecating the replace option on directives [link](https://docs.angularjs.org/api/ng/service/$compile)

**Comment by hmillet** [comment]
@RobJacobs that precisely what I was pointing out. Thanks for your answer. "You're going to see a lot more of these non-standard html tags in the future"... Have these non-standard tags some impact on browsers behaviour, or is it a non problematic evolution ?

@icfantv @BobbieBarker no, I don't talk about attributes.

**Comment by icfantv** [comment]
@hmillet, new browsers **should** not have any issues with them - but certain older browsers (whom shall remain nameless) can and will barf.

@wesleycho, @Foxandxss, and team, what do what do with this?

**Comment by Foxandxss** [comment]
First, I really really appreciate this kind of issues @hmillet. Even if you feel like it could be right or not, it is always good to raise flags against potentially bad behavior.

That said, this concrete one is not a problem. This is how angular (and angular 2 for that matter) works. If you're not using `replace: true`, it will leave the custom element on the final HTML.

There is no way that we (or any other library) can remove those things from the final HTML because as @RobJacobs said, `replace` is deprecated. We have lots of `replace` in our library, and perhaps we should consider about removing them for 1.0.0.

So for example, if you have a directive called `my-custom-thing` that has a `<p>` tag as a template, you use it like:

```html
<my-custom-thing></my-custom-thing>
```

If it has replace, it will **replace** the original element, resulting with:

```html
<p>something</p>
```

But the expected behavior (replace is problematic) is to have it like:

```html
<my-custom-thing>
  <p>something</p>
</my-custom-thing>
```

That being said, that concrete element is a bit generated by hand, but it just simulating the expected angular behavior.

Don't worry, it won't cause you any problem in any supported browser by angular.

**Comment by hmillet** [comment]
@Foxandxss 

Thanks a lot for your answer. This is perfectly clear.
I confirm that this cause no problem to the browsers I tested my app with.
I even used it in my css files without any trouble.

Modern browsers are clever :-)
