### ISSUE TITLE
Alignment with respect to the calendar entry field

### ISSUE THREAD

**Issue by triplustri** [angular-ui/bootstrap#4905]
Sometimes field calendar last item on a page, and in this case falls when the calendar page body is increased by the height of the calendar. It would be desirable that in such cases, the calendar dropped the top, not the bottom.

**Comment by icfantv** [comment]
@triplustri, If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

When you have updated this issue with the requisite requirements, we will reopen.  Thanks.

Also, if my understanding of your issue is correct, you may want to keep a very close eye on #4762 as we intend to support smart/fixed positioning in a much more robust fashion.
