### ISSUE TITLE
It's not using Bootstrap grid system.

### ISSUE THREAD

**Issue by hfuccillo** [angular-ui/bootstrap#4927]
Hi, I'm using angular-ui but when I tried to place a div with "col-md-4" it's not working. It's placing DIVS below each other.
http://plnkr.co/edit/grOTgNEvFLTwzBTd2rFr?p=preview
Any thoughts?

**Comment by icfantv** [comment]
@hfuccillo, please do not use the issues forum for support related-requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.  Thanks.

First off, this is a Bootstrap CSS question and has nothing to do with the Angular UI Bootstrap project.  Second, you didn't read the docs for the Bootstrap Grid system because you're not using it correctly.  You need to wrap the block-level column elements correctly.  Read [these docs](http://getbootstrap.com/css/#grid) for proper usage.  Finally, you need to understand how media queries work.  The reason your classes aren't getting applied in the plunker is that you've only specified that it should work on the @screen-md-min devices, i.e., those with a width of 992px and up - something you are not getting on your Plunker.  If you add the three other column classes `col-xs-4 col-sm-4 col-lg-4` you will see that it works correctly.  In this case, the `xs` class is being applied.

Please extend us the courtesy of making sure you understand the frameworks you are attempting to use and how they fit together.  Thanks.

**Comment by hfuccillo** [comment]
Thanks @icfantv and sorry for posting this in the wrong place.
