### ISSUE TITLE
uib-popover Button Disabled

### ISSUE THREAD

**Issue by Hansel03** [angular-ui/bootstrap#4931]
you can use a uib-popover in a disabled button?

http://plnkr.co/edit/Vyl8ly8tXcQp1a9c57X9?p=preview

**Comment by icfantv** [comment]
@Hansel03, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help).  The issues forum is reserved for bugs.  Thanks.

If you are asking if you can use the `uib-popover`directive when an item is disabled, the answer is no because the browser does not fire events for DOM elements that are disabled.

**Comment by Hansel03** [comment]
thanks and sorry.
