### ISSUE TITLE
Remove datepicker feature from ui-bootstrap

### ISSUE THREAD

**Issue by priyankanaik26** [angular-ui/bootstrap#4998]
I'm using jquery-ui for datepicker. I recently added pagination to my application from ui-bootstrap because of which there are 2 datepickers appearing on the page. I want to show just the datepicker getting loaded from the first script i.e. jquery-ui. How do I disable the ui-bootstrap datepicker from getting displayed on the page without affecting my pagination code from ui-bootstrap?

**Comment by icfantv** [comment]
Please do not use the issues forum for support requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap/blob/master/README.md#need-help).

In general, it's not a good idea to mix UI libraries like you are doing.  Both jQuery UI and Bootstrap provide their own, different, CSS themes.  You've not indicated what version of UIBS you are using nor provided any code snippets so my current guess is that you're using the deprecated directive names instead of the new, prefixed ones.
