### ISSUE TITLE
Date parser not working if format string contains literal words

### ISSUE THREAD

**Issue by jpmitche11** [angular-ui/bootstrap#5091]
I believe a recent commit broke the parsing of dates that contain quoted literals:
9513f1007f1fa800a50f83d8b71e8ed1bafdbdcd

Tested with the 'mediumDate' format using the portuguese locale pt-br (d 'de' MMM 'de' y HH:mm:ss)

The angular date formats use single quotes, not backticks.  If you claim to support the locale base date formats, then this should be fixed.

Attn: @wesleycho

**Comment by wesleycho** [comment]
I changed it to backticks because single quotes are really awkward due to having to do a lot of escaping.

**Comment by wesleycho** [comment]
@Foxandxss what do you think? I could revert the breaking change, but this will be cumbersome for normal consumption & lead to hard to read strings in the HTML.

Very much dislike this request.

**Comment by jpmitche11** [comment]
I think this is a mistake. Angular has supplied the date format syntax, this library is merely an implementation of that.  
If you want to use your own format, then it would be an error to look up the date format strings from $locale. Those are angular formats, not ui-bootstrap formats.

**Comment by jpmitche11** [comment]
Here is a plunkr that illustrates my problem.
All I am doing is attempting to use the date parser with 'mediumDate' as  the format, while using the pt-br locale.
http://plnkr.co/edit/ulvQQMc3OkET2VDfxktc

**Comment by wesleycho** [comment]
IMO I think Angular/Google got this wrong, but getting them to change it is probably not going to happen from an engineering standpoint (it would break prior contract, creating compatibility problems maintaining two different formats), so this appears that it might force us into a subpar API.

I understand your request, and we may end up reverting the change I made, I just want a second opinion since I really do not like the awkwardness of using a single quote.
