### ISSUE TITLE
IE throws exceptions on removeModalWindow on close from javascript

### ISSUE THREAD

**Issue by Hadev-JHH** [angular-ui/bootstrap#5096]
When you open and close a modal from javascript, on a page that does not have any inputs or buttons.  body.focus() throws a 'focus not supported' error. 

The bug only occurs in IE, when body.activeElement is undefined.

Browser: IE11
Angular: 1.4.7
Angular-bootstrap: 0.14.3

**Comment by elTallarin** [comment]
This issue is now fixed from version 1.10 and beyond right? But this bug is present in older versions too.
For example 0.13.3. And is not that easy to move to 1.10 since the names of components (directives, factories) are prefixed with 'uib' there. Do you think it's possible to fix the issue for older versions?

**Comment by wesleycho** [comment]
Our release process makes this extremely complicated to backport fixes due to our build setup.

**Comment by elTallarin** [comment]
Ok wesly. Am I right in the fact that the version with the fix is not compatible with 0.13.3?
