### ISSUE TITLE
Error: "No provider for Http!"  in beta release

### ISSUE THREAD

**Issue by Toadskin** [angular-ui/bootstrap#5117]
Upgraded working alpha application to beta and fixed up the many change-related errors, but now getting this:

EXCEPTION: No provider for Http! (MyComponent -> MyService -> Http)
 
I am booting with HTTP_PROVIDERS specified in my boot.ts file (same as it was in NG2 alpha). 

```
import {Http} from 'angular2/http'
import {Injectable} from 'angular2/core'
@Injectable() export class MyService {
    constructor(public http:Http) { }
    getStuff() {
        return this.http.get('http://localhost:4000/api/stuff').map((stuff:any) => stuff.json().devices)
    }
}
```

**Comment by icfantv** [comment]
@Toadskin, if you're working with the ng2 version of the library, this is not the correct forum.  This forum is for Angular 1.x.  You probably at least want [this library](https://github.com/ng-bootstrap/core), but that said, we've not yet released anything for ng2 so in that vein, there's not really anything for us to do here because I'm pretty sure you're not working with our library.

Also, please do not use the issues forum for support related requests.  Support questions are best served by and for the community at large and as such, StackOverflow is probably your best bet.  These instructions are posted [here](https://github.com/angular-ui/bootstrap#need-help).

Finally, when asking for help, regardless of the location, please be respectful of the reader's time by providing as much information as possible, including a minimally working plunker that demonstrates the issue.
