### ISSUE TITLE
Warning when using "popup" class

### ISSUE THREAD

**Issue by yoorek** [angular-ui/bootstrap#5121]
When any tag has "popup" class popup directive fires and console gets ""$tooltip is now deprecated. Use $uibTooltip instead."

https://jsbin.com/femino/1/edit?html,console

**Comment by icfantv** [comment]
@yoorek, maintaining a large and popular OSS library is a difficult task performed by a lot of people.  As such we ask that you please be respectful of our time by looking at both open and closed issues before you enter anything in the issues forum.

That said, the deprecation warnings were added in the 0.14.x releases as we introduced a `uib-` prefix for all our directives (to avoid namespace clashes with both other angular frameworks and native HTML) and the purpose of deprecation warnings are to let the API user know that the API has changed and they need to update their code accordingly.  In your example, you need to use `uib-popover` instead of just `popover`.

I should also note that with the 1.0 release all the deprecation warnings and the deprecated code will be removed.  This means that your example would no longer throw a deprecation warning but also not work at all.

**Comment by yoorek** [comment]
I know about warnings. Try to understand what THIS ISSUE MEANS.  
You attach "popup" Directive to "popup" Class not attribute. So, after 1.0 i should use "uib-popup" CSS Class ?! Try to convince bootstrap

Dnia 24.12.2015 o godz. 05:11 Adam Gordon <notifications@github.com> napisał(a):

**Comment by icfantv** [comment]
@yoorek, reading your initial post as I did, i.e., someone who is not yourself and from the perspective of a library maintainer, that is how I interpreted it.  You need to be more clear about what you were trying to say.

All that aside, you don't have to use the CSS class directive, you can use the `uib-popover` attribute directly instead.  We apply the appropriate Bootstrap classes via the tooltip and popover template.  The only thing that has changed here is the name of the directive.

**Comment by yoorek** [comment]
I don't need to but i want to use "popup" css Class. And you force popup directive when i do it. Class selector directive are considered BAD practice. JUST RESTRICT DIRECTIVE TO "EA"
I attached JSBIN with JUST class="popup" (no popup attribute) which causes popup directive to fire and warnings in console. How much more specific can i be?

Dnia 24.12.2015 o godz. 15:05 Adam Gordon <notifications@github.com> napisał(a):

**Comment by icfantv** [comment]
@yoorek, relax and take a breath.  Your last comment was clear and you should have led with that.  We are not savants and aren't able to read minds.  We are aware that class directives are bad and it is on our radar to remove them.  But as we are focused on the 1.0 release, this is a lower priority.  Feel free to use the non-class based directives with the build from `master` and you'll be fine.
