### ISSUE TITLE
Bug-When carousel active

### ISSUE THREAD

**Issue by duongtuan1793** [angular-ui/bootstrap#5134]
i have found :
when carousel active all other relative or absolute text item(especially colored text ) will twinkling and blur .
i used:
AngularJS v1.4.7
angular-bootstrap v0.14.3

pls fix it !

**Comment by icfantv** [comment]
@duongtuan1793, If you think you've found a bug, please follow [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug).

Please be respectful of our time by fully clarifying exactly what your issue is and give us a reproducible plunker.  What you've typed above is not very helpful.  Thanks.

We will consider reopening when we have something to verify.
