### ISSUE TITLE
Add limit of items in the typeahead's results

### ISSUE THREAD

**Issue by alexdemers** [angular-ui/bootstrap#526]
I have an autocomplete field that has a couple of thousands of records. If I type "s" then I get all of the records that have an s in it, but I can a couple of thousand entries all rendered on the page which makes it slow. Also, the list gets pretty huge when rendered on the page. The bootstrap plugin supports limiting results and even defaults it at 8.

**Comment by davincho** [comment]
@pkozlowski-opensource Using this template https://github.com/angular-ui/bootstrap/blob/master/template/typeahead/typeahead-popup.html and changing the ng-repeat directive as you described above to ``match in matches | limitTo:5 track by $index`` with matches being an array with more than 5 items, I get an error ``Cannot read property 'parentNode' of undefined`` as soon as I hit the end of the dropdown via keyboard navigation.

The reason is that in https://github.com/angular-ui/bootstrap/blob/master/src/typeahead/typeahead.js#L413 and https://github.com/angular-ui/bootstrap/blob/master/src/typeahead/typeahead.js#L407 the length of `matches` is considered to calculate the new active index.

**Comment by davincho** [comment]
Ok nevermind - I got confused with the templates. Everything works as expected!
