### ISSUE TITLE
ngClick not trigged when radio with ngIf

### ISSUE THREAD

**Issue by piernik** [angular-ui/bootstrap#5289]
Where's plunk: http://plnkr.co/edit/38GrcvcFlGcxGp6Yq8cq?p=preview
When clicking button ngClick should be trigged but it's not.
When delete ngIf everything works.
Before 1.0 that worked as it should.

**Comment by pkozlowski-opensource** [comment]
Not sure what is the exact change that causes different behavior (and I'm not even sure if this is due to this lib change or AngularJS change - are you sure that you are not updating AngularJS version at the same time?) but using `ng-click` here is asking for trouble. You should be using `ng-change` instead: http://plnkr.co/edit/XzYSU3tEKx0HOu46DY10?p=preview

**Comment by piernik** [comment]
I'm still on angular 1.4.8
As for me ng-change is great solution - I think You can close this topic if You like.
