### ISSUE TITLE
Previous date is set as model value after picking a date

### ISSUE THREAD

**Issue by gmodrogan** [angular-ui/bootstrap#5318]
I know there are some problems with what type of value ng-model accepts but this bug is a nasty one.
Please have a look at the following plnkr http://plnkr.co/edit/lMNfweJN7xakBPPaR2GQ?p=preview

No matter what type of value I assign for the model (string, Date(), empty) the value set for the model is always with a day BEFORE.

Are you guys aware of this problem? Also have a look please at #5223 another issue that I reported.
These kind of issues are stopping me from delivering to the client quality on time

**Comment by Foxandxss** [comment]
I can't see the issue, perhaps it is a timezone issue? Or perhaps I am not following you

![](http://puu.sh/mDS3u/f2ba97b304.png)

And that last paragraph of yours is not needed here.

**Comment by gmodrogan** [comment]
you pinpointed the problem. Thanks! It's about timezone, I will set it in ng-model-options and should work ok.

**Comment by vsthakur78** [comment]
Hi gmodrogan,

I am facing a similar issue where I am sending a UTC date to browser and since client browser is in EST (eastern time) it automatically moves the date backword since there is some -5 hours difference in utc and est. 
For example I am sending 20th feb with time value 3am utc which automatically converts the 20th feb to 19th feb because after subtracting 5 hours from the date i sent - it comes as 19th feb.

I tried sending without time and still same story. It doesn't happen if time instance in utc has passed more hours/minutes than utc-to-est difference. I think it assumes the timestamp as midnight utc when I dont send time info.

I am  assuming above problem is similar to mine and would like to know if there a solution made available. What options I need to set if ng-mode-options is going to help me to restrict this conversion? 

Appreciate if you let me know HOW to fix this, if its already addressed.

**Comment by gmodrogan** [comment]
I did not do anything. I'm just storing everything in UTC now in the backend. So if the user picks "27 nov" in the db it will be 26 nov 2016 22:00:00. When I read the data on the FE it will be automatically converted when **displayed** to user's computer local timezone. I guess storing in UTC everything is a good idea
