### ISSUE TITLE
BUG: Popover closes itself even though popover-is-open is set to true

### ISSUE THREAD

**Issue by shyamal890** [angular-ui/bootstrap#5337]
Following are the options set:
```
    uib-popover="I am activated manually" 
    popover-is-open="true" 
    popover-trigger="none"
    popover-append-to-body="true"
```

When a route change occurs(ui-router) the popover closes itself.

- Version Info:
- Angular UI Bootstrap version: 1.1.0
- UI-Router version: 0.2.15
- Angularjs version: 1.4.7

Demonstration in [PLUNKER](http://plnkr.co/edit/tNwexNKsznSucoZrYxxH?p=preview)

**Comment by shyamal890** [comment]
Can anyone please have a look at this: @wesleycho @icfantv

**Comment by wesleycho** [comment]
Looks like the culprit is https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/tooltip.js#L544-L553 - this seems like odd code to me, and history seems to indicate that it is old as 041261b5366aa44a0c0314e8262c91d1d867f4d1 is the original commit.

I'm in favor of just removing this outright, the scope.$on('$destroy', ...) listener should be enough to catch this.
