### ISSUE TITLE
DropDown isOpen on input focus flashes drop down and then hides again

### ISSUE THREAD

**Issue by JohnGalt1717** [angular-ui/bootstrap#5348]
I have a input group with a drop down. On the uib-dropdown I have is-open = a variable.

I have an ng-focus on the input control that does nothing other than set the variable to true so that the drop down shows again when the user clicks into the input control (and obviously it automatically hides on loss of focus)

However when I do this the menu flashes and then goes away again. How do I get it to stay open on focus?

**Comment by icfantv** [comment]
@JohnGalt1717, please do not use the issues forum for support-related requests.  Rather, please follow the instructions [here](https://github.com/angular-ui/bootstrap#need-help) as support-related questions are best served by and for the community.  The issues forum is reserved for bugs.  Thanks.

Also, a minimally-working plunker is imperative for most support issues as it gives everyone a chance to see what you are actually doing rather than trying to picture it in their head and then guessing.
