### ISSUE TITLE
template-url attribute support

### ISSUE THREAD

**Issue by geroyche** [angular-ui/bootstrap#5405]
overriding templates via attrs.templateUrl is not consistently implemented across directives.
some support it, others don't.
i specifically came across it trying to override uib-tab in order to remove the empty href.

**Comment by Foxandxss** [comment]
That is pretty much correct. I will consider it.

**Comment by wesleycho** [comment]
It should be noted that all components that support it has it mentioned in the documentation.

This is missing though, and I believe I have seen that it was missing in the past, but I forgot to file a PR/issue implementing it for tabs.

**Comment by agrahamlincoln** [comment]
I've taken a look at the documentation and identified some of the work that needs to be done.

The following components need `template-url` implementations and currently have none:
- Button
- Collapse
- ProgressBar
- Rating
- Tabs

The following directives have a similar implementation but naming is inconsistent:
- Datepicker - uses `datepicker-popup-template-url` and `datepicker-template-url`
- Modal - uses `templateUrl` and `windowTemplateUrl` instead of `*template-url`
- Popover - uses `uib-popover-template` instead of `*template-url`
- Tooltip - uses `uib-tooltip-template` instead of `*template-url`
- Typeahead - uses `typeahead-template-url` and `typeahead-popup-template-url`

For directives with multiple templates, the naming scheme seems to be `[component]-<subcomponent>-template-url`.

**Comment by Foxandxss** [comment]
Better to open a new issue for that.

It is not that inconsistent :P

Modal is a service so that is why it is camelCase and not kebab-case.

Datepicker is fine, that is the way it should be done (same with typeahead).

Popover / tooltip is a bit different because those uib-xxx-template are directives and it is not a mere template-url option to override a concrete template.

**Comment by wesleycho** [comment]
Collapse also has no template, and not sure it makes sense to have this feature for buttons either.
