### ISSUE TITLE
Guys we need we need that the activity that we are currently looking at will be highlighted. And also ol

### ISSUE THREAD

**Issue by ilcheivanovski** [angular-ui/bootstrap#5406]
k

**Comment by ilcheivanovski** [comment]
![screen shot 02-03-16 at 02 56 pm](https://cloud.githubusercontent.com/assets/10915515/12784303/a810e3da-ca86-11e5-905a-bf3faa60ee4f.JPG)

**Comment by icfantv** [comment]
Please be respectful of our time by reading the project documentation and making an effort to follow the instructions on how to enter an issue and/or receive support.  This post is awful because you've given us absolutely nothing to go on.  I'm closing this until you can show this is a bit in our library.
