### ISSUE TITLE
Datepicker popup - handle json ISO 8601 date strings

### ISSUE THREAD

**Issue by RobJacobs** [angular-ui/bootstrap#5456]
I know there's been a lot of work done for parsing dates in the datepicker-popup, so please excuse me if I'm opening old wounds.  The change I propose would be to parse the ISO 8601 date string used in json to a date object.  I think this would cover most of the use cases and alleviate the majority of the feedback in regards to the datepicker-popup ng-model requiring a date object.  The change would involve adding the following snippet [here](https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L923)

        if (ISO_8601_DATE_REGEX.test(value)) {
          value = new Date(value);
        }

And the regex would look like so:

        var ISO_8601_DATE_REGEX = /^([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))([T\s]((([01]\d|2[0-3])((:?)[0-5]\d)?|24\:?00)([\.,]\d+(?!:))?)?(\17[0-5]\d([\.,]\d+)?)?([zZ]|([\+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/;

Let me know if this is acceptable and I will create a PR, thanks.

**Comment by wesleycho** [comment]
This would be very difficult, because MS browsers & Chrome handle supported date strings differently from Firefox and Safari - the date string supported would be near impossible to reconcile consistently.

**Comment by togakangaroo** [comment]
I don't think this would need to be parsed to a date object, just pick out the year, month and day and create a new one. The ISO standard is the ISO standard.

Let me give a use case where this would be really helpful.

I fetch some data using $resource for which one of the properties is a date that gets displayed in a datepicker. The server is doing everything right by sending things in an ISO standard format but the datepicker cannot handle it!

Because this is a $resource, there isn't a great place in my controller to fix up the dates, so I end up having to `transformResponse` which is....just nuts you guys. Having to go to a subsystem of a common service in order for a primary ui control to be able to use the standard format passed in.

Again, you don't need to `new Date()` and have it parse as @RobJacobs suggested. Instead, just pluck out the year, month, day components (which is easy in the standard) and create a new date from that.

**Comment by wesleycho** [comment]
But date strings could be arbitrary - in addition, when converting model to string, timezone information and such are lost, which means we would progressively lose correct hour/minute information with each transformation when converting back to the model from the string (say if the user or something else modifies the value). There are also problems with different date strings being supported across browsers, and regex parsing of strings to determine the date is out of the question because any such parser will be highly flawed due to the different string support browsers have.

This is outright not going to be implemented in this library.

You are better off using the inline datepicker and building a widget around it to display it as desired. Having this feature in the library itself will cause very significant bloat, and not necessarily desired by all users.

**Comment by togakangaroo** [comment]
They can't be arbitrary, iso is a standard

I'm trying to think of examples where timezone could possibly be an issue for a datepicker and all I got is if the server is running on one side of the international date line and is visited by someone in fiji during the southern summer? Even then, the offset is part of the standard and can be parsed out as easily as the other stuff. 

Maybe I'm missing something but this really sounds like 3 lines of code. Can you help me understand with a counterexample?

**Comment by RobJacobs** [comment]
My suggestion was specific to handling the json ISO 8601 date string as that would allow people to bind directly to web service response and handle a majority of the use cases.

**Comment by wesleycho** [comment]
Then we'd need to regex parse every time - there was a lot of bloat & fragility prior with generic string support, this seems like it'd be worse.

**Comment by togakangaroo** [comment]
yes? you'd regex parse every time? how often are models binding to datepickers? Simple regex parsing is a fast operation that I've never seen be a bottleneck in perf tests. And again, we're not talking about generic string support, we're talking about the internationally recognized ISO 8601 standard which is [quite well defined](https://en.wikipedia.org/wiki/ISO_8601) 

You don't even need regex If you don't handle timezones (which again, is something that could possibly matter *only* to someone who is in a timezone more than 24 hours difference from where data is stored - so people who travel from the Midway islands to New Zealand or Fiji during very specific times of the year) a simple split will do. If you *do* handle timezones then maybe we're talking 8 lines instead of 3, but I really can't think of a counterexample

**Comment by wesleycho** [comment]
It's more complicated than you think - we then have to potentially consider model state in addition.

I'm strongly against adding this complexity anytime soon given that there are far more important issues to tackle, and one can attain this support on the user side currently with less library bloat - there hasn't been hugely convincing reasons yet as to why this should go in the library itself.

**Comment by circuitrider** [comment]
Boo to this. Lacking this prevents simple model binding with nothing between it and calling server side functions that depend on ISO 8601 format, which is largely the standard now. That is why it should be included.
