### ISSUE TITLE
uibModalInstance as an Optional Service

### ISSUE THREAD

**Issue by kirangsa** [angular-ui/bootstrap#5463]
Hi,

I have a situation that needs to use uibModalInstance as an optional injector. Because I need to use the same controller for two views. One is the popup view and other is normal view. When am using the popup it's working fine. In another case, it's throwing an unknown injector Error.

**Comment by icfantv** [comment]
Please do not use the issues forum for support related requests.  Instructions on how to get help is noted in our project documentation.

The uibModalInstance object only exists in the context of a modal.  While I appreciate you trying to reuse controller code, you will need to restructure it so that it is not injected where it is not needed.
