### ISSUE TITLE
Typeahead is-open change via document click does not trigger digest on original scope

### ISSUE THREAD

**Issue by trogowski** [angular-ui/bootstrap#5467]
When typeahead's drop-down is open, clicking outside of it closes the drop-down but variable bound to is-open does not change to false. Here's a minimal [test case] (http://plnkr.co/edit/fkl2wd?p=preview).

Changing 'scope.$digest()' to 'originalScope.$digest()' [here](https://github.com/angular-ui/bootstrap/blob/master/src/typeahead/typeahead.js#L452) seems to fix the problem.

**Comment by icfantv** [comment]
This looks like a good catch.  @wesleycho, thoughts?

**Comment by mkozhukharenko** [comment]
I've encountered the same problem +1

**Comment by mkozhukharenko** [comment]
Found temporary workaround:

` <input type="text" 
           click-outside="typeaheadIsOpen = false;"
           ng-model="model"
           uib-typeahead="option as option.name for option in new.options | filter:{$:$viewValue}"
           typeahead-is-open="typeaheadIsOpen">
`

I used click-outside directive to manipulate typeaheadIsOpen variable;

**Comment by azizmaredia20** [comment]
Hi mkozhukharenko,
can you please share your click-outside="typeaheadIsOpen = false;" directive code

**Comment by azizmaredia20** [comment]
Does anyone has a fix for this isssue?

**Comment by icfantv** [comment]
@azizmaredia20, hi there.  Please understand that we are all unpaid volunteers on this team, managing a VERY popular OSS project.  It maybe as simple as making the change indicated above, but we would need to make sure it doesn't have any negative side effects.  I've flagged it as needing investigation and we will get to it.  You will need to be patient.

Barring that, you could always fork the repo and make the change yourself using a custom build until this issue is fixed.

**Comment by azizmaredia20** [comment]
@icfantv, Yes sure i will fork the repo and try to solve the issue

**Comment by mkozhukharenko** [comment]
@azizmaredia20 I'm using [IamAdamJowett/angular-click-outside](https://github.com/IamAdamJowett/angular-click-outside ) directive

**Comment by wesleycho** [comment]
Similar to the recently fixed issue with 313ba83, we should change this to `originalScope`.
