### ISSUE TITLE
Setting uibDatepickerPopupConfig.closeText not working?

### ISSUE THREAD

**Issue by mbuzun** [angular-ui/bootstrap#5468]
Hi, there is a sample plunkr
http://plnkr.co/edit/AxwouJotQL8CeCRbX38P?p=preview

With popup, while setting closeText as 'CustomText', when the popups gets opened, got still 'Close'
Other, like

```
uibDatepickerPopupConfig.currentText
uibDatepickerPopupConfig.clearText
```

Works well.
Any help?

**Comment by icfantv** [comment]
@mbuzun, the reason this is happening is because the directive attribute takes precedence over the your default config value as can be seen by [this line of code](https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L977).  If you remove the `close-text` attribute on your directives, it will work as you would like.
