### ISSUE TITLE
resolve does not work when using modal with ng-controller, but works with controller-as syntax.

### ISSUE THREAD

**Issue by ravshansbox** [angular-ui/bootstrap#5477]

**Comment by ravshansbox** [comment]
I've created an example app to demonstrate behaviour:
https://github.com/ravshansbox/angular-bootstrap-modal-example

**Comment by wesleycho** [comment]
ng-controller is an anti-pattern - there is no good use case for it.

Resolve does not work with ng-controller because the controller instantiated from the modal service uses the resolve values as locals. If one wants to use the resolve values, one must consume it from a controller instantiated by $modal.open.
