### ISSUE TITLE
Dropdown: not working starting with 1.0.0 version 

### ISSUE THREAD

**Issue by julia-bougaev** [angular-ui/bootstrap#5527]
Hi,
Dropdown is working with UIBS versions less than 1.0.0: [plunker](http://plnkr.co/edit/pkYeMUoyoYMnG2QQPCBa?p=preview
)
and not working with 1.0.0 and later: [plunker]( http://plnkr.co/edit/JgJ8BxW68kmRaFyL8ZmC?p=preview)

Angular: 1.4.
UIBS:1.0.0
Bootstrap:3.2.0

**Comment by icfantv** [comment]
@julia-bougaev, please be respectful of our time by not using the issues forum for support requests.  This was very clearly stated in the template you removed prior to entering this issue.

Secondly, your plunker is a very poor example because it includes:
1. Two different versions of the bootstrap CSS
2. The Bootstrap JS file - you're using Angular, you don't need this file.
3. You've pulled in jQuery unnecessarily.

Finally, you neglected to read the CHANGELOG before upgrading.  1.0 removed the legacy, non-prefixed UIBS directive names.  We've added namespacing to our directives and thus you must add `uib-` to our directives.  This is in our project documentation as well.

Again, in the future please be respectful of our time.
