### ISSUE TITLE
Popover - Optional in case of watching on popover-is-open

### ISSUE THREAD

**Issue by Rouche** [angular-ui/bootstrap#5538]
Hello,

Ive read in the last days that the only way to get notified on the onClose() for the popover is to watch the same property bound for the popover-is-open option.
Like this: http://plnkr.co/edit/wIgZzH1Dw1Bm7QtZvZMn?p=preview

In a particular case, inside a ng-repeat, i need to make the popover out of the dom, so i do not receive watch callback. (A user preference to not show popups.)

Would it be possible to add a ng-if="popoverVisible" option on root div in the popover-template.html? Default true so theres no regressions.

Right now its very ugly since i need to duplicate the code, <span> with the popover another without it. Im still trying to figure out another way but it does not look possible.
In any case i can do it and ask PR.

Thanks.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.0

UIBS: 1.1.2

Bootstrap: 3.3.6

**Comment by icfantv** [comment]
I don't understand your statement `i need to make the popover out of the dom, so i do not receive watch callback.`  What do you mean?  Every item in an ng-repeat has it's own scope, so every `popover-is-open` has its own scope.

Perhaps, if you explained what UX you want (instead of the technical problem) we can assist you further.  Other than that, I'm inclined to reject this request as it adds an additional watch - one that would almost never be used.

**Comment by Rouche** [comment]
Ok this was just a bad solution, too much.

ill just put the ng-if in a parent div.
