### ISSUE TITLE
Timepicker changes the date when using NgModelOptions Timezone=UTC

### ISSUE THREAD

**Issue by migajek** [angular-ui/bootstrap#5592]
When using TimePicker with ``ng-model-options`` timezone specified to UTC, I've got this strange behavior of TimePicker switching the date one day backward when increasing the hour from 11 PM.

My local timezone is UTC+01

Plunker: http://plnkr.co/edit/rh7Nv4ZrgQV2FYMqC1sg?p=preview

This is what happens when I keep "increasing" the time by one hour (clicking hour arrow up)

![image](https://cloud.githubusercontent.com/assets/581492/13557436/a7d6aa02-e3f0-11e5-90b2-f7575ee37758.png)

when using local timezone (i.e. not enforcing the UTC via ngModelOptions), it works fine (see the "Good" section on the plunker)

I know it might be hard to reproduce for you, please let me know if there's any way to help you with debugging.

**Comment by wesleycho** [comment]
Timepicker does not currently support ng-model-options.

**Comment by wesleycho** [comment]
So to clarify on this particular issue more in depth, we do need to change the date in some instances for sure - the request in this issue would be in direct opposition to the reported bug in #5485. The fix for that bug requires date changing for example.

The timezone support is certainly an issue - we should support ng-model-options.

**Comment by wesleycho** [comment]
Closing in favor of #5594
