### ISSUE TITLE
Dropdown not working for me

### ISSUE THREAD

**Issue by kolkov** [angular-ui/bootstrap#5597]
http://plnkr.co/edit/KyKeQ2juOQEP7VLJ6iic?p=preview

What I do wrong?

**Comment by icfantv** [comment]
@kolkov, i'm going to close this because as indicated by the text you summarily deleted to enter this, the issues forum is not for support requests.  In the future, please be more respectful of our time by reading the project documentation (a link to which was also in the text you deleted) for how to properly ask for and receive help.

**Comment by kolkov** [comment]
Thanks! I spent many hours for search of the decision! Any didn't work. New good documentation with examples is necessary.

**Comment by icfantv** [comment]
Have you tried looking at [our demo site](http://angular-ui.github.io/bootstrap/) where we have fully working examples?

**Comment by kolkov** [comment]
Yes! I used source from this site as example for building my own. But my site is not working like this. For example, if I use ng-click="isCollapsed = !isCollapsed" for closing menu I see moving horisontal scrollbar for a seconds when I switch between pages or when I reload page. https://in-frame.com:8088/angular#/home

**Comment by kolkov** [comment]
notice: This bug appearing when I click on any link with ng-click="isCollapsed = !isCollapsed" twice.

**Comment by icfantv** [comment]
@kolkov, as this is a support issue, please follow those instructions.  Thanks.
