### ISSUE TITLE
[popover] Popover element does not display when using uib-popover-html

### ISSUE THREAD

**Issue by james04321** [angular-ui/bootstrap#5651]
### Bug description:

When using `uib-popover-html`, the popover element does not display at all.

When inspecting the popover element, the CSS rule `display: none` is not overridden like it is for the regular `uib-popover`.

The fix seems to be to update the CSS rules in the head `<style>` to include `[uib-popover-html-popup].popover`.

### Link to minimally-working plunker that reproduces the issue:

https://plnkr.co/edit/SF6YlT

The expected behavior here is for a popover to display below the button with the text "Line1" and "Line2" in separate lines.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.0

UIBS: 1.2.4

Bootstrap: 3.3.6

**Comment by icfantv** [comment]
@james04321 this is fixed in `master`.  Please be respecful of our time by searching both open and closed issues as this has been reported _NUMEROUS_ times.  Thanks.

**Comment by sgarbesi** [comment]
+1

**Comment by icfantv** [comment]
@sgarbesi, three things:

1.  don't just add `+1` to issues - especially issues that are closed as duplicates.  simply adding a `+1` adds no intrinsic value and only clutters up the thread.

2. this issue was closed as a duplicate because, well, it was a duplicate and it's already fixed.

3.  GitHub how has emojis for indicating support of an issue, comment, resolution, solution, etc... - it's available via the smiley icon next to the pencil and X icons on a response.

Thanks.
