### ISSUE TITLE
when using ng-include, uib-pagination is not working normally.

### ISSUE THREAD

**Issue by andyandox** [angular-ui/bootstrap#5673]
I create a controller using in a.html, and then, a.html uses `ng-include` to include page.html. Content in page.html just include only one row code(`<uib-pagination first-text="首页" last-text="尾页" previous-text="上一页" next-text="下一页" num-pages="numPages" items-per-page="itemPerPage" total-items="totalItems" ng-model="currentPage" max-size="maxSize" class="pagination-sm" boundary-links="true" rotate="false"
	ng-change="pageChanged()"></uib-pagination>`).function `pageChanged` is defined in the controller,and now, whether how I click the page, `currentPage ` just do not change.when I not use `ng-include`, everything is normally.

**Comment by RobJacobs** [comment]
This is due to prototypal inheritance as described [here](https://github.com/angular/angular.js/wiki/Understanding-Scopes)

**Comment by icfantv** [comment]
@andyandox, in the future, please be respectful of our time by adhering to the issue template and following the instructions therein rather than summarily ignoring and then deleting it.  The issues forum is not for support requests (per the text you deleted).

The issue template is to save us time in finding bugs in submitted issues.  Failure to adhere to the template will result in the issue being closed without any further action.  We are all unpaid volunteers on this project.
