### ISSUE TITLE
carousel: hide left arrow for first slide and right arrow for last slide.

### ISSUE THREAD

**Issue by m2omou** [angular-ui/bootstrap#5695]
Is it possible to hide the left arrow when on the first slide and hide the right arrow when at the last slide ?

Just adding a class name when it reaches that state, so we could hide them by overwriting the css, without having to touch the directive itself.

angular-ui-bootstrap: 0.14.3 - 2015-10-23

https://github.com/angular-ui/bootstrap/tree/master/src/carousel

Thank you !

**Comment by icfantv** [comment]
@m2omou, please be respectful of our time by reading the issue template instead of summarily deleting it.  the first line states that the issues forum is not for support requests and the second line indicates where you need to go to learn how to properly ask for help.  please don't be lazy.

to answer your question, you can override the template via the `template-url` attribute.
