### ISSUE TITLE
web

### ISSUE THREAD

**Issue by exejutable** [angular-ui/bootstrap#5750]
### Bug description:
The web fails to inject angular module ui.bootstrap.demo
http://angular-ui.github.io/bootstrap/

**Comment by icfantv** [comment]
@exejutable, per the issue template, please search both open and closed issues prior to entering anything.  The issue is most likely due to a browser extension (say Adblock Plus blocking the FastClick library).  Looking at your console will indicate thus.

We have seen issues with users behind proxy servers as well.

**Comment by icfantv** [comment]
this is now fixed - even with an adblocker installed.
