### ISSUE TITLE
Rating rendered HTML should not have ng-click attribute when readOnly

### ISSUE THREAD

**Issue by karensg** [angular-ui/bootstrap#5764]
### Bug description:

I use the rating directive with a read only attribute and I get an error in Google Pagespeed report which influences my SEO. Google considers the rating stars clickable while they are not.
Therefore the `ng-click` attribute should not be generated when the readOnly attribute is true.

### Link that reproduces the issue:

[Pagespeed report of Angular Bootstrap homepage](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fangular-ui.github.io%2Fbootstrap%2F%23%2Frating)
Mobile -> User Experience

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.4

UIBS: 1.3.1

Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
Removing the attributes would be a mess - this is because this variable is two-way bound. In addition, that doesn't change the actual clickability.

In addition, the pagespeed link does not mention this at all - I strongly believe there are far larger hanging fruit for improving SEO ratings.

Going to close this as won't support, it doesn't make sense & opens a rabbit hole we do not want to go down.
