### ISSUE TITLE
Tab active is not working anymore

### ISSUE THREAD

**Issue by abides** [angular-ui/bootstrap#5774]
### Version of Angular, UIBS, and Bootstrap
Angular:1.4.9
UIBS:1.3.1
Bootstrap:3.3.6

Simple plunker shows active tab does not working on 1.3.1. When i switch it to 1.1.2 its working and start of 1.2.0 its not working.

Something totally changed on this area which i'm not aware of?

Best regards.

**Comment by abides** [comment]
I read this : #5489 and just realized active is moved to tabset and its getting index of tab and make it active. I don't undestand why old method is broken in the way of this change.

This kind of dramatic changes affect lots of project. For example i have lots of pages in my project and all pages are now broken because i want to upgrade 1.1.x to 1.3.1.

Also in my opinion bind it to data already there was better instead of bind to another variable.

**Comment by wesleycho** [comment]
Closing as support.

Yes, this is a big breaking change.

The reason for this change is due to various big issues with having the state tracked on a tab by tab basis, instead of it being centralized in the tabset controller. This led to some special issues such as where when tabs were removed, callbacks were executed incorrectly. See #4836 for some of the issues that are related to the former api.
