### ISSUE TITLE
ng-model-options with datepicker

### ISSUE THREAD

**Issue by benhalverson** [angular-ui/bootstrap#5825]
### Bug description: 

When using ng-model-options="{updateOn: 'blur'}" with the UIB Datepicker, the calendar does not disappear after selecting a date. Removing ng-model-options="{updateOn: 'blur'}" makes the calendar work again. ng-model-options="{updateOn: 'default blur'}" also does not work.

Expected Results:
ng-model-options="{updateOn: 'default blur'}"  or ng-model-options="{updateOn: 'blur'}" should work. 
https://docs.angularjs.org/api/ng/directive/ngModelOptions 

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/LyWR5miigK76tQo7OwuY

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.0

UIBS: 1.1.2

Bootstrap: 3.2

**Comment by wesleycho** [comment]
Hey @benhalverson !

You actually stumbled upon an issue that we're already discussing some in #5811 - I agree with your thoughts on this.

**Comment by benhalverson** [comment]
@wesleycho I'm interested in submitting a PR for this issue. Can you point me in the right direction? Unfortunately  I can't do it during working hours.

**Comment by wesleycho** [comment]
I think there might have to be modifications in both the datepicker and datepicker-popup components for supporting this - basically we need to somehow decouple the config of the two components so that one can independently modify the ng-model-options of both the popup and inline datepicker.

It may be possible to just do it on the datepicker-popup alone, but I haven't investigated it in depth.

**Comment by wesleycho** [comment]
So I believe I have the fix - @benhalverson can you check out #5933 and the Plunker that it works the way you expect?
