### ISSUE TITLE
UI-tabset not updating tab index when removing a tab

### ISSUE THREAD

**Issue by anay0001** [angular-ui/bootstrap#5875]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Version of Angular, UIBS, and Bootstrap

Angular: 1.4.10

UIBS:

Bootstrap:1.3.2

Not able to select tabs using dynamic index value. scope is not binding to tabset.
as per my requirement i have to add and remove tabs dynamically.

Here i am able to add tab with rootscope variable as active value in tabset. But while removing the tab the index value is not updating. 

e.g. after adding 3 tabs if i remove 2nd one and add again one more tab the tabset index coming as 0,2,2. which causes multiple selection of tab.

http://plnkr.co/edit/EWopbbr9WDYybI6LoO0k?p=preview

**Comment by wesleycho** [comment]
This is a user error - see [here](http://plnkr.co/edit/JFbFQ7jgJ7kFYxiGsIza?p=preview) for how to handle this correctly.

**Comment by icfantv** [comment]
@anay0001, I don't know if it's just your plunker or what, but just a note that you do not want to be generating your tab indices (workspace ID) in this manner.  per our documentation, the tab index MUST be unique and indeed if you play with the solution plunker by @wesleycho you will break it rather quickly because your tab index algorithm is bad.

**Comment by anay0001** [comment]
Thanks Wesleycho for immediate response.
Still facing issue. 
I added one tab in (http://plnkr.co/edit/EWopbbr9WDYybI6LoO0k?p=preview) and removed 2nd tab.
Now i want to add two more tabs but add button seems not working and if,  clicking remove tab of existing tabs it is displaying  4 tabs (i.e.: no of clicks that i failed on add tab button.)

As per my requirement when i add a new tab that should be selected and if remove any tab that should be removed from tab list. and again if i continues to add that should work properly

**Comment by icfantv** [comment]
@anay0001, a couple things:  1), your plunker does not match what @wesleycho gave you and you haven't read what I wrote because you're still using an ID generating algorithm that allows for duplicates, which ng-repeat does not allow (when you switch to `track by`), and 2) the issues forum is not for support requests.  In the link we have in the issue template, we document how to get help.
