### ISSUE TITLE
Two way data binding for the active attribute on a tab

### ISSUE THREAD

**Issue by Theo-** [angular-ui/bootstrap#5899]
### Bug description:

When modifying the property "active" of a tab from the javascript side during a digest cycle, the tabset doesn't update the view to the current active tab.

In the plunker below, the data structure specifies that the second tab should be selected. However the first tab is selected at run time.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/HY6UaOSTsW7YwEvTDlFm?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular:
AngularJS v1.5.5

UIBS:
1.3.2

Bootstrap:
Bootstrap v3.3.6

**Comment by Theo-** [comment]
Opened a pull request with the fix https://github.com/angular-ui/bootstrap/pull/5900

**Comment by icfantv** [comment]
@Theo- why are you touching the `active` property of the tabs?  we manage and set these internally after rendering to ensure the right CSS class is set.

**Comment by Theo-** [comment]
Why is it internal ? Let's say I have a data structure like this:

`
$scope.tabs = 
[
{
name: "tab1",
active: true
},
{
name: "tab2",
active: false
}
]
`
Let's set active='tab.active' in the ng-repeat. If I do `$scope.tabs[0] = false` and `$scope.tabs[1]=true` (for example when the user clicks on a button), the second tab will not get selected. If that an expected result ?

I understand it is supposed to be an internal property, but would't it be easier to just modify the current tab by change the active flag on the data structure instead of changing the "active" attribute on the tabset.

If not please close this issue.

**Comment by icfantv** [comment]
Funny you should ask.  Until quite recently, we had it at the tab level.  We moved it to the tabset level because it made more sense to have the parent container manage its children and leave the children agnostic.

You can still set an active tab via its index - which can be a number or a string, but must be unique.  The latter of which is in `master`, but should be released this week.

I'm going to close this per this and your comments.
