### ISSUE TITLE
uib-typeahead isn't being respected in directive.

### ISSUE THREAD

**Issue by zatchgordon** [angular-ui/bootstrap#5907]
### Bug description:
   When using uib-typeahead in a thrid-party directive (in this case [TreeGrid](https://github.com/khan4019/tree-grid-directive)) the tag uib-typeahead isn't being respected.

### Link to minimally-working plunker that reproduces the issue:

In this plunker, the top input works and the lower input does not. 
They Both use:
`<input type="text" class="form-control" ng-model="vm.Selected" uib-typeahead="item for item in ['hello', 'hoover' , 'world'] | filter:$viewValue | limitTo:8" />`
The difference is the lower one is being initiated by the treegrid directive via vm.colDefs.
http://plnkr.co/edit/dGd7X4HvETaGxqdbWyr5?p=preview

### Version of Angular, UIBS, and Bootstrap
Angular: 1.4.3

UIBS: 1.3.2

Bootstrap: 2.3.1

**Comment by icfantv** [comment]
@zatchgordon you have not indicated where you think the bug is located.  per our demo page, the typeahead component is working correctly.  if there is a bug in that component that is causing interaction with another, 3rd party, component, the onus is on you to prove that our component is the culprit.  as we are all volunteers, we simply do not have the bandwith to do this.  thanks.

i'm going to close this until then.  sorry.

**Comment by zatchgordon** [comment]
Thank you.
