### ISSUE TITLE
Typeahead with show-hint enabled focuses wrong input field on label click

### ISSUE THREAD

**Issue by grobgl** [angular-ui/bootstrap#5926]
### Bug description:
When using the `typeahead` component with the flag `typeahead-show-hint` set to `true` and a label, clicking on the label will focus the wrong input field (the one that is used to show the hint text). This is probably because the ID is passed to the wrong input field.

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/YPDrR76uEnXoyYO5F9pP?p=preview

### Version of Angular, UIBS, and Bootstrap
Angular: v1.4.3
UIBS: v1.3.3
Bootstrap: v2.3.1

**Comment by icfantv** [comment]
@grobgl, this is a good catch.  the issue is that (and you can see this if you look at the generated HTML) there are two elements with the same `id` - which is a recipe for badness in a browser.

The culprit is [this line](https://github.com/angular-ui/bootstrap/blob/master/src/typeahead/typeahead.js#L136) where we clone the element but never change the ID, if present.

I'm going to play around with this some more, but I believe the fix simply to remove the ID from the original element until after it's cloned - which would be a breaking change should anyone be relying on it.

@wesleycho, if this sounds like the right fix, I'll make a PR.

**Comment by wesleycho** [comment]
I'm fine with that fix
