### ISSUE TITLE
HELP! datepicker-option lead to [$compile:nonassign]

### ISSUE THREAD

**Issue by cesiya23** [angular-ui/bootstrap#5948]
Angular: 1.4.7

UIBS:1.3.2

```
Error: [$compile:nonassign] Expression '{formatMonth:'MMMM',datepickerMode:'day',minMode:'day',maxDate:vm.today}' in attribute 'datepickerOptions' used with directive 'uibDatepickerPopup' is non-assignable!
```

This happens when I get into month-choose-mode and year-choose-mode, when I first open the datepicker-popup, there is no error, I want to know why and a solution.

I have already found that if no maxDate is setted, everything will be ok.

Bellow is my use of datepicker:
```
<input class="form-control" type="text" id="basicInfo-{{key}}"
                       uib-datepicker-popup="yyyy/MM/dd"
                       datepicker-append-to-body="true"
                       datepicker-options="{formatMonth:'MMMM',datepickerMode:'day',minMode:'day',maxDate:vm.today}"
                       popup-placement="top-left"
                       current-text="{{'currentText' | i18n}}"
                       clear-text="{{'clearText' | i18n}}"
                       close-text="{{'closeText' | i18n}}"
                       ng-model="vm.basicInfos[key]"
                       is-open="open">
```

**Comment by wesleycho** [comment]
The reason for this is that `datepicker-options` is bound via two-way binding. You should use something like
```js
$scope.options = {
  formatMonth: 'MMMM',
  datepickerMode: 'day',
  minMode: 'day',
  maxDate:vm.today
};

datepicker-options="options"
```
In the future, please note that the issue queue isn't for support issues, but for legitimate verified bugs/feature requests.

**Comment by cesiya23** [comment]
thans!

**Comment by MaheshSasidharan** [comment]
@wesleycho 
Is there a way to avoid this? I have several date pickers on a page. I don't want to create a datepicker -options object for each. So I am adding datepicker-options in the HTML like this
 **datepicker-options="{maxDate: vm.oGrantData.TotStop, showWeeks:false}"**

And since I have not created a datepicker-options object, it throws [this error](https://docs.angularjs.org/error/$compile/nonassign?p0=%7BminDate:%20vm.oGrantData.TotStart,%20maxDate:vm.oGrantData.TotStop,%20showWeeks:false%7D&p1=datepickerOptions&p2=uibDatepickerPopup) when I am changing the Date enter mode, (Year, month).

![datepicker-options](https://cloud.githubusercontent.com/assets/9265496/18799358/c557be64-819c-11e6-9fcc-e7beba04316c.PNG)

**Comment by cesiya23** [comment]
@wesleycho Try to assign a variable in your scope or controller to the expression, not literal value.
