### ISSUE TITLE
Modal open action transform div origin when hovering

### ISSUE THREAD

**Issue by vjoao** [angular-ui/bootstrap#5949]
### Bug description:

This is a very strange bug: 
I hover an element to show the "Add to cart" button which opens a modal. When closing the modal (via button or backdrop) the element position just jumps to another anchor (strange thing is the developer tools doesn't show the top/bottom attribute changing)

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/3685ZuyNLsJC6iNnVXpU

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.3

UIBS: 1.3.3

Bootstrap: 3.3.6

**Comment by wesleycho** [comment]
This looks like a Chrome and IE bug, and nothing we can do about - the Plunker actually works fine on Firefox and Safari. I haven't tried it on Edge.

Going to close this as won't fix due to the nature of this bug.

**Comment by icfantv** [comment]
@vjoao have you tried removing the CSS animation/eye candy to see if this is the reason.  what i've found that helps is to remove everything but the fundamental necessities of the feature to try and narrow down where exactly the bug lies.  we use UIBS modals a lot in our application at work and have no such issues with DOM elements moving around.
