### ISSUE TITLE
Feature request: alert service / notification 

### ISSUE THREAD

**Issue by billyaraujo** [angular-ui/bootstrap#5969]
Would be nice if  ui.bootstrap.alert had a service which could be called to do notifications similar to angular strap ($alertservice). 

http://mgcrea.github.io/angular-strap/#/alerts-usage

ATM I am using bootstrap for everything and another library for notifications but would prefer to use bootstrap ui if it had that functionality (less one dependency).

**Comment by icfantv** [comment]
@billyaraujo you can implement this yourself fairly easily with a wrapper around the library's alert feature.   other than that, while it would be a nice feature, it's quite low on our priority list.  Please understand that I do agree Toasters are a good UI feature.

Remember, we are all unpaid volunteers and simply don't have the time to implement every feature request because every new feature requires more support and inevitably results in more requests for ehancements/changes to that feature.

I'm going to close this as something we aren't going to be able to support.
