### ISSUE TITLE
Tab selection shows blank area when tabs removed and re-added

### ISSUE THREAD

**Issue by hookedupjoe** [angular-ui/bootstrap#5972]
### Bug description:
When attempting to select a tab index where a tab has been removed, it goes blank.  

Note: Using $scope.tabs.splice(index, 1); to remove, source code is very short.

### Link to minimally-working plunker that reproduces the issue:
Note: Press the buttons in order left to right to see the issue recreated.
http://plnkr.co/edit/KPC0hmjvrLD92v1DWPnS?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular:
1.5.3

UIBS:
ui-bootstrap-tpls-1.3.3.js

Bootstrap:
3.3.6

**Comment by wesleycho** [comment]
I'm not sure if I consider this a bug - the user should be managing the tabs present, and what index gets selected.

**Comment by hookedupjoe** [comment]
Scenario: Someone clicks the support link in the app header and it dynamically opens a new support tab.  Then they are in another tab doing something and need support and click the link on the header again.   When this happens  .. I reopen the tab for them as opposed to opening a new duplicate page.  

Scenario 2: You have a tabbed form and something fails validation.  You want to focus on the field, which is in another tab.  You need to be able to problematically open the tab.  

The list of use cases for this is long and I have implemented this in all the other tab systems in other libraries that allow for dynamic tabs.   I'd call it a bug or would say the tabs do not support dynamic use.  

This was from a quick evaluation of how robust the various libraries are or I'd be hunting down the bug myself.  If I select this library for use, more details and guidance for fixes will be included future bug reports when possible.   Just noticed this and figured I'd report it .. since I had it recreated.  - Regards.

**Comment by wesleycho** [comment]
So I attempted to change this, but this is a breaking change. Currently the deselect callbacks are called when no valid active tab is selected (due to programmatic changes on the user side). It turns out breaking this behavior will cause a lot of other unexpected cases where there are test cases written against them.

I'm going to close this as won't support, as it is the user's responsibility to manage the model correctly when the user is manipulating it, and adding guards to predict that is not sound from a library standpoint.

**Comment by j306796405** [comment]
@hookedupjoe then how do you fix this?
