### ISSUE TITLE
Feature Request: broadcast an event on select date in datepicker

### ISSUE THREAD

**Issue by roymiloh** [angular-ui/bootstrap#6042]
I'm using my own template (pass `template-url`) in order to make a different html structure and apply some transformation on data coming from the [original controller](https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L608). It works fine, however, I cannot know when the actual date was changed. 

The controller exports a method called `select(date)`, so I can actually monkey patch it and use my own select that calls `UibDaypickerController`'s `select` internally and do my own things on date selection, so basically it's ok, because I have guarantee that `select` _always_ changes the date. 
The controller exports another method, for keyboard event handling, called [`keydown`](https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L310) and here's the problem: I don't know if the key used for date selection or not. Of course, I can monkey patch this method as well, but then I'll have to duplicate logic (if space / enter is pressed, it means that a date selected), ... which can leads for unexpected behaviour in the future (if, say, enter is no longer used for date selection).

My suggestion is simply broadcast another event, called `uib:datepicker.selected` right after this [line](https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js#L269), so no matter method is used to select a date, I can listen it and handle my own implementation on date selection.

**Comment by icfantv** [comment]
Firstly, in general, one needs a VERY good reason to use an event-based API.  This is not a good reason.

Secondly, this issue has been requested numerous times:  #5860, #5609, #5409, #4461, #3738.  In nearly all those cases, the user was trying to solve some problem using events as a band-aid rather than trying to solve the solution properly and as a result, all were rejected.

Thirdly, can you not just watch the model for changes to determine if the selected date has changed?

I'm inclined to reject this.

**Comment by wesleycho** [comment]
Closing as per comments in prior issues. Eventing is a bad solution for something that is simply handled through $scope.$watch here & meets all the requirements as a hook the user can use to then do whatever the user desires.
