### ISSUE TITLE
Turn off datepicker validation

### ISSUE THREAD

**Issue by daviatorstorm** [angular-ui/bootstrap#6052]
I do not need to validate value on every keypress.

Angular: 1.5.5

UIBS: datepicker

Bootstrap: 3

**Comment by icfantv** [comment]
@daviatorstorm to be quite honest, as we are all unpaid volunteers, I don't think we are going to be able to commit resources to doing this.  if you're finding that your app is really sluggish because of this then you might want to start with one of the Angular watchers plugins which will show you how many watches you have on a given page.

I'm going to close this as won't support, but please feel free to convince me otherwise.  Thanks.

**Comment by daviatorstorm** [comment]
I need to validate by untouch with 'dd.MM.yyyy', 'd.MM.yyyy', 'dd.M.yyyy', 'd.M.yyyy'.
How can I do it with current validation?

**Comment by daviatorstorm** [comment]
I found a solution for that :)
Just pasted right parameters to alt-input-formats and create a attribute restricted directive with validation on input blur.
altFormats: 'd!', 'd!.', 'd!.M!', 'd!.M!.', 'd!.M!.y', 'd!.M!.y'.
