### ISSUE TITLE
Misplaced caret on tooltip at right

### ISSUE THREAD

**Issue by brunomperes** [angular-ui/bootstrap#6082]
### Bug description:

After upgrading from 0.13.3 to 1.3.3, some tooltips positioned at right were appearing wrongly as if their width does not fit.

### Link to minimally-working plunker that reproduces the issue:

Behaviour is observed on UIBS page: https://angular-ui.github.io/bootstrap/#/tooltip

Here's a plunker: http://plnkr.co/edit/ureLc8K03P6pTUoMsvx5?p=preview

![screenshot from 2016-07-11 20 03 25](https://cloud.githubusercontent.com/assets/1819575/16749707/9b069cae-47a2-11e6-8470-9bed452ace42.png)

### Version of Angular, UIBS, and Bootstrap

Angular: 1.5.3

UIBS: 1.3.3

Bootstrap: 3.3.6

**Comment by icfantv** [comment]
@RobJacobs is this a bug in the positioning service?

**Comment by RobJacobs** [comment]
This is because the tooltip element grows vertically when the text wraps (it's not just the caret that's off, the tooltip itself is not centered vertically).  The text wrapping occurs at some point in the render cycle after the tooltip has been positioned.  @wesleycho worked on this recently on PR #5959

**Comment by icfantv** [comment]
@RobJacobs awesome.  thanks.  @brunomperes, this is already fixed in `master` and there was already an issue for this.  in the future, please be respectful of our time by searching both open and closed issues prior to entering a new one.
