### ISSUE TITLE
End glitch when collapsing uib-collapse

### ISSUE THREAD

**Issue by lucianflorea** [angular-ui/bootstrap#6096]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
I have a panel that uses uib-collapse directive created used an angular 1.5 component. This panel can contain other angular 1.5 components. When collapsed, this panel has a glitch at the end of the transitions...it is too dirrect from what i can see . In the original bootstrap component this does not happen. Please see component `<custom-filter-accordion2>` from bellow link plunker. When collapsed, the glitch can be seen.

### Link to minimally-working plunker that reproduces the issue:
https://plnkr.co/edit/VKoMO7UrHeMbHaJG1AE4?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular:
1.5.7

UIBS:
1.3.3

Bootstrap:
3.3.6.

**Comment by icfantv** [comment]
I suspect this has to do with using angular 1.5 components specifically and the event lifecycle used therein.  We've basically decided that we cannot support 1.5 component architecture until we drop support for Angular 1.4 and we do not have a timetable for that yet as we feel 1.4 is still fairly ubiquitous.

**Comment by lucianflorea** [comment]
If it helps you with something, you can check  [here](https://plnkr.co/edit/SbvKZe1BldqOntrbXi0l?p=preview) that by changing a little bit the order of the panels, the transition it is much smoother.

**Comment by wesleycho** [comment]
Updated the Plunker a bit [here](https://plnkr.co/edit/7MSQrKEWUdg19neOD3KE?p=preview) to ensure there isn't a mismatch of versions of Angular & the various libraries (in particular, ngAnimate), as well as avoid any distractions.

The issue here is actually that the panel body has a padding, and that needs to be tweaked in order to avoid this jank through smart CSS. This is unfortunately unavoidable with using the collapse directive just due to how the height calculations work at the various stages of the animation.
