### ISSUE TITLE
empty href disables draggable on Safari

### ISSUE THREAD

**Issue by yoshiokatsuneo** [angular-ui/bootstrap#6106]
Safari does not allow the element draggable if the element have empty href.
So, for example, I cannot make tab draggable on Safari.
And, I guess empty href is invalid HTML ?
Changing empty 'href' to 'href="#"' fixes the problem.

**Comment by pkozlowski-opensource** [comment]
> Changing empty 'href' to 'href="#"' fixes the problem.

Unfortunately this introduces other problems (ex. unwanted page reloads)

**Comment by yoshiokatsuneo** [comment]
For me, I don't see the reload issue on angularjs 1.5.7.

**Comment by icfantv** [comment]
@yoshiokatsuneo, your best bet here is to override the template to something that will work for you.  Be advised that if you do this, we can no longer realistically be able to support your implementation.  Anchor tags are tricky and we tried switching to divs, but that introduced both styling and ARIA issues.  I'm going to close this because a workaround exists and we have not had any/many requests to allow for draggable tabs.
