### ISSUE TITLE
Wrong modules dependencies dropdownConfig and $position

### ISSUE THREAD

**Issue by zakrava** [angular-ui/bootstrap#6181]
After running thru ng-annotate it reveals unmet dependencies / wrong naming.

These errors are thrown:
Error: [$injector:unpr] Unknown provider: $positionProvider <- $position <- $uibTooltip <- uibTooltipDirective <- $uibTooltip
Error: [$injector:unpr] Unknown provider: dropdownConfigProvider <- dropdownConfig <- $uibTooltip <- UibDropdownController

Renaming these solved issues:
dropdownConfig -> uibDropdownConfig
$position -> $uibPosition

**Comment by wesleycho** [comment]
That sounds like an ng-annotate bug - we correctly handle minification in the library.

**Comment by zakrava** [comment]
it is exactly what i am talking about.
tooltip line you pointed out:
 this.$get = ['$window', '$compile', '$timeout', '$document', '$uibPosition', '$interpolate', '$rootScope', '$parse', '$$stackedMap', function($window, $compile, $timeout, $document, $position, $interpolate, $rootScope, $parse, $$stackedMap) {

in list of dependencies there is $uibPosition, but in function is $position, i think, that is what causes problems.

and 

dropdown line you pointed out:
.controller('UibDropdownController', ['$scope', '$element', '$attrs', '$parse', 'uibDropdownConfig', 'uibDropdownService', '$animate', '$uibPosition', '$document', '$compile', '$templateRequest', function($scope, $element, $attrs, $parse, dropdownConfig, uibDropdownService, $animate, $position, $document, $compile, $templateRequest) {

in list of dependencies there is $uibDropdownConfig, but in function is drowdownConfig, i think, that is what causes problems.

I am not an angular guru, but it looks weird to me.
Thanks for reply.

**Comment by wesleycho** [comment]
How this library explicitly handles DI is valid for guarding against minification. This is not an issue with this library.

**Comment by zakrava** [comment]
But why this different naming?
uibDropdownService is same in both cases, but uibDropdownConfig is in one case and dropdownConfig in second?
and with $uibPosition and $position in case of tooltip?

Thanks for clarification, because it doesn't make sense to me.
Otherwise good work. I appreciate it.

**Comment by wesleycho** [comment]
The arguments can be named whatever the user likes - they can be named `foo` or `bar` if wanted (although those aren't particularly useful names). The important part is that there is a string reference to the injectable to be fetched by the injector. Because we have this in one of the two minification safe DI syntaxes available in Angular, this library handles it fine - this can easily be verified by a Plunker with the use of the minified version, such as [this](https://plnkr.co/edit/KmLsg4UceOx9NRxbl0qz?p=preview).

This narrows down the issue to one of ng-annotate then - if this is indeed an issue there, it should be reported there, but I don't see why ng-annotate wouldn't be able to recognize this scenario. I have never encountered this in the past while using it.
