### ISSUE TITLE
AngularJS UI Bootstrap NuGet out of date

### ISSUE THREAD

**Issue by bbodenmiller** [angular-ui/bootstrap#6206]
AngularJS UI Bootstrap 2.1.3 was just released but NuGet is only showing 1.3.3: https://www.nuget.org/packages/Angular.UI.Bootstrap/

**Comment by xt0rted** [comment]
All of the current v2 releases have just been pushed to NuGet with the most recent being 2.1.3.

I no longer use NuGet for frontend assets, or this project, which is why I stopped publishing them when v2 came out. I'll continue to release these since there seems to be some demand for them but they'll probably lag behind some.

The NuGet package is maintained at [xt0rted/angular-ui-bootstrap-nuget](https://github.com/xt0rted/angular-ui-bootstrap-nuget) so if there's ever a version missing you can create an issue there about it which I'll see sooner than something posted on this project.

**Comment by wesleycho** [comment]
Thanks @xt0rted!

Closing this as we don't maintain the NuGet releases, and due to the information posted here as a location for contacting for updating the releases.
