### ISSUE TITLE
popover-trigger="'outside click'" does not hide if click takes places on embedded iframe.

### ISSUE THREAD

**Issue by twwwt** [angular-ui/bootstrap#6243]
When using a popover with `popover-trigger="'outside click'"`, an opened popover does not hide if the page contains an iframe and the click is done within the iframe. This appears logically, since the click event is dispatched within the iframe's context. Is there a possibility that the enclosing context gets the even as well such that the popover closes.

Tested with Angular 1.5.8, UIBootstrap 2.1.3, Bootstrap 3.3.7

**Comment by wesleycho** [comment]
The value used should be `popover-trigger="'outsideClick'"`

**Comment by twwwt** [comment]
Sorry, that was a typo. The issue exists equally with `popover-trigger="'outsideClick'"`.

Please, consider reopening the issue. Yet, I'm not sure whether something can be done about it or whether the behavior described is a matter of the fact that there is an `<iframe>` inside the page and clicks within the `<iframe>` box cannot be captured by the enclosing browsing context (that contains an instance of the popover directive).

**Comment by wesleycho** [comment]
Hm, but if we cannot capture clicks in an iframe, I don't think we can do anything about this. If you have control over the iframe, one thing you can do is to use `postMessage` to send a message to the parent window and then use that to with the `popover-is-open` binding to close it, but I don't see anything that can be added in the library side to help address this otherwise.
