### ISSUE TITLE
uib-tabset: content of not active tab evaluate before make it active.

### ISSUE THREAD

**Issue by cumajkeee** [angular-ui/bootstrap#6329]
The issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
uib-tabset: content of not active tab evaluate before make it active.

### Link to minimally-working plunker that reproduces the issue:
https://plnkr.co/edit/RViQ5u5z9P7a57UMhzRq?p=preview

### Version of Angular, UIBS, and Bootstrap

Angular:
1.5.8
UIBS:
2.2.0
Bootstrap:

**Comment by icfantv** [comment]
It's not at all clear what you're reporting and you didn't provide explicit steps to show us the issue.  I'm closing this until you do.

**Comment by cumajkeee** [comment]
What do you mean by "you didn't provide explicit steps to show us the issue"? 

Please see plunker. There I showed case that you have 4 tabs. Inside last one I have div with a controller that should request access to mic and camera.

Actual result: controller was executed before I click on tab.
Expected result: controller should execute only when I click on corresponding tab.

**Comment by icfantv** [comment]
@cumajkeee i mean, you just added more context to the issue.  Your original post has a one sentence description of the issue whereby it wasn't at all clear what the issue was.

You did, however, inadvertently expose an issue in our template, namely, that we don't explicitly ask for steps to reproduce.  So thank you for that, I will fix our template.
