### ISSUE TITLE
uib-datepicker-popup not updating textbox when year 0000 is entered in texbox

### ISSUE THREAD

**Issue by rrmehta83** [angular-ui/bootstrap#6348]
when manually typing date if year 0000 is entered model value gets updated with year 1 (i.e 0001) but text box still shows year as 0000 where as calendar popup shows 0001 year. I don't know if it is bug, but from user point of view text box should also get updated in case of two way binding.

[http://plnkr.co/edit/juq5j9HI3rzPI22bis4H?p=preview](url)

Enter year as 0000, see model value updating but text box does not update

**Comment by wesleycho** [comment]
This looks like a bug in Angular's date filter - see [here](http://plnkr.co/edit/p6PqxCEvut9BL4395awF?p=preview) for demonstration date is correct here. 

I just opened an issue https://github.com/angular/angular.js/issues/15548 to track this, closing this issue - be sure to follow the issue in Angular in order to track it.
