### ISSUE TITLE
Include minified build in npm package

### ISSUE THREAD

**Issue by romanzoller** [angular-ui/bootstrap#6365]
This is a feature request.

As discussed previously in https://github.com/angular-ui/bootstrap/issues/5877, the npm package of angular-ui-bootstrap currently does not include a minified version of the library.

AFAICT it is common practice to include a minified version of the library in the npm package (see e.g. [this pdf.js issue](https://github.com/mozilla/pdf.js/issues/5487)), and would be helpful to me and other people.

**Comment by wesleycho** [comment]
The reason it isn't included is because with commonjs & npm, you can take advantage of using `require` to include only the pieces you are using to avoid unnecessary loading of pieces of the library that are not being used and save users accessing the app wasted bandwidth.

Is there a good reason why you are not concatenating & minifying your JS?

**Comment by wesleycho** [comment]
Going to close this as something we are not going to support - this was decided by the team prior because we want to encourage making sure the end user does not receive an unnecessarily large payload, especially if not all of the components are used.
