### ISSUE TITLE
no npm module for version 0.8.0

### ISSUE THREAD

**Issue by jbadeau** [angular-ui/bootstrap#6416]
We are still using bootstrap 2 and are moving to npm but there does not seem to be a angular-ui-bootstrap 0.8.0 node module in npm. Would it be possible to add it for people still on bootstrap 2?

**Comment by icfantv** [comment]
@jbadeau Unfortunately, that version is so old, it does not make sense for us to apply any of our limited resources for this.  We don't even have any generated docs for releases older than 0.12.0.  You might consider hosting your own, internal NPM repo instead.

**Comment by JG247** [comment]
Hi Adam

Thanks for taking a look and provide your advice.




On 20 Jan 2017 21:22, "Adam Gordon" <notifications@github.com> wrote:

@jbadeau <https://github.com/jbadeau> Unfortunately, that version is so
old, it does not make sense for us to apply any of our limited resources
for this. We don't even have any generated docs for releases older than
0.12.0. You might consider hosting your own, internal NPM repo instead.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/angular-ui/bootstrap/issues/6416#issuecomment-274183244>,
or mute the thread
