### ISSUE TITLE
uib-popover not closing on outside click

### ISSUE THREAD

**Issue by kjartanvalur** [angular-ui/bootstrap#6458]
I´m using the Angular UI Bootstrap Popover, but I´m unable to get it to close on outside click. I´m using the outsideClick trigger (popover-trigger="outsideClick") Why is this not working?

```
  <button uib-popover-template="'myPopoverTemplate.html'"  
   popover-placement="right"class="btn btn-default"
   popover-trigger="outsideClick">Click Me</button>
```

[PLUNKER](http://plnkr.co/edit/IgP9EnpHVLJ4JCS8OhJ1?p=preview)
[Stack Overflow](http://stackoverflow.com/questions/42138694/uib-popover-not-closing-on-outside-click)

**Comment by AngularPlayer** [comment]
I think it's because on new release you have to do :
`popover-trigger="**'outsideClick'**">Click Me</button>`

Or use something like $scope.myTrigger = "outsideClick" then
`popover-trigger="myTrigger">Click Me</button>`

In your case it's 'click' (default) trigger that is used because the directive doesn't recognize your parameter so the popover open on click but not close on outsideClick :)

**Comment by kjartanvalur** [comment]
haha, Thanks @AngularPlayer

**Comment by jeserkin** [comment]
So this `popover-trigger="outsideClick"` assigns closing trigger, when in docs for 1.2.5 version it says following:
> `popover-trigger` (Default: click) - What should trigger a show of the popover? Supports a space separated list of event names (see below).

**Comment by saijayaprakash** [comment]
We can use a small hack,
add an attribute `tabindex="-1"` and `popover-trigger="focus"` to make it work
