### ISSUE TITLE
Is there an to trigger function when Daptepicker is closed and value selected by the user

### ISSUE THREAD

**Issue by tarekahf** [angular-ui/bootstrap#6666]
I am using Datepicker, and I want to perform special calculation while the Datepicker is opened, and value not selected, and when the user selects a value and the picker box is closed, then the calculation will change depending on the status of the picker box and if value is selected.

How I can do that?

Tarek

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.

**Comment by tarekahf** [comment]
Appreciate it if you could point me to the documents where it mentions the project is no longer maintained? I just need to know if this applies to the entire Angular-UI Bootstrap or the old versions?

**Comment by icfantv** [comment]
@tarekahf TBH, it's in a lot of places:  it's _literally_ the first thing on the page [here](https://github.com/angular-ui/bootstrap) (the comment to read the project status), and the first thing in the README below the root project files listing.  It's also listed in the ISSUE_TEMPLATE that you deleted when you entered in your support request above, which is [a documented](https://github.com/angular-ui/bootstrap#need-help), but totally moot since the project is no longer being maintained, incorrect use of the project issues.
