### ISSUE TITLE
New Issues & Expectations

### ISSUE THREAD

**Issue by tbasallo** [angular-ui/bootstrap#6684]
@icfantv I appreciate your position and have read the posts around the support of this repo. However, is closing all newly posted issues a good solution? I ask only because until someone takes over this project or a fork gets popular enough to become the new standard, this is the only resource. At the very least a dialog around known issues and possible workarounds can continue. Shutting it down does not allow for that conversation to occur. 

At this moment there's no viable alternative yet, but a lot of folks, myself included, are using this project in production and still need support and a forum for discussion. AngularJS is still being worked on and, from what I can tell, will have a 1.7 version released.

I think with the warning presented when a new issue is being opened you have taken the opportunity to allow posters to know the situation - there should be no expectations from anyone around this project.

**Comment by icfantv** [comment]
Closing this as this project is no longer being maintained, per the README and the ISSUE_TEMPLATE.

**Comment by icfantv** [comment]
@tbasallo, To answer your first question, my initial thought is yes, it is a good solution.  My reasoning is because if not, the last post, the one that calls for maintainers and for a separate repo will just scroll off and get lost until the next time someone creates yet another post complaining about there being no calls for maintainers on this project.  Additionally, I disagree with your assessment that closing the bugs shuts down the conversation and doesn't allow conversation to occur because we aren't locking the conversations.  Web crawlers will still index the posts and they will still show up in search results.  Indeed I still get notification emails from GH nearly daily from comments on [significantly] older posts talking about how to work around intentional library limitations.

I won't get into a viability discussion because there are viable options, they just happen to involve a willingness to put in the time and [sometimes significant] effort.  I will also note that since early October, no one has stepped up to fork the repo and start actively maintaining it, at least not publicly.

I appreciate you taking the time to create your post and vocalize your thoughts.
