### ISSUE TITLE
package.json for 2.5.6 tag contains version=2.5.4

### ISSUE THREAD

**Issue by ispringer** [angular-ui/bootstrap#6702]
https://github.com/angular-ui/bootstrap/blob/2.5.6/package.json

contains:

```
 "version": "2.5.4",
```

**Comment by icfantv** [comment]
@ispringer Sorry about that.  We've never automated  (or documented) our release process and when I had to update the readme and templates, I clearly missed this.  Since this is the first complaint I've seen in the 6 months since that last release, I'm hesitant to correct it.  Especially since the project is EOL'd.  Surely, it's not blocking you, correct?
