### ISSUE TITLE
$modal does not stop tabbing on the background 

### ISSUE THREAD

**Issue by chriswu14** [angular-ui/bootstrap#738]
This can be reproduced on the sample page on http://angular-ui.github.io/bootstrap/
- in the Dialog section click 'Open Dialog' button
- keep hitting tab key

result: tab going through background page and data can also be entered.

Hope someone can advise on this problem. Thanks.

**Comment by icfantv** [comment]
Hey all, it's been nearly seven months since the last update and nearly two years since this issue was first opened.  Are we any closer to an acceptable solution?  Thanks.

**Comment by theider** [comment]
I started having this problem after upgrading AngularJS in my application and starting to use "smart table" (not sure which came first but these two things changed).

I was able to fix it (i.e. get the modal backdrop to go away) by doing this:

In angular-bootstrap 0.13.0 ui-bootstrap-tpls.js line 2165 in removeAfterAnimate():

      function removeAfterAnimate(domEl, scope, done) {
        // Closing animation
        scope.animate = false;

        if (domEl.attr('modal-animation') && $animate.enabled()) {
          // transition out
          $rootScope.$evalAsync(afterAnimating); // <-- calling this directly makes the backdrop go away.
// this domEl.one does not resolve properly and so the critical afterAnimating method does not get executed.
//          domEl.one('$animate:leave', function closeFn() {
//            $rootScope.$evalAsync(afterAnimating);
//          });
        } else {
          // Ensure this call is async
          $timeout(afterAnimating);
        }

        function afterAnimating() {
          if (afterAnimating.done) {
...

How can we turn this into a fix?  I'm not sure of the impact of not using the .one approach through $animate.close.  BTW $animate.close does not seem to be a method; I see enter and leave but I don't fully understand $animate yet.

**Comment by keyurpatel** [comment]
Really very nicely crafted and explained. @michelbetancourt, @chriswu14 , @jmwolfe

**Comment by Luukash** [comment]
There is an error in the keypress event binding, if you disable the keyboard (in order to disallow the esc key to close the modal) this event never runs, i think this isnt correct (As i want my modals not to be closed, but i dont want tab to go to the background), here is my fix (in my case i never care about esc key)
It could be solved easily.

$document.bind('keydown', function (evt) {

        if (evt.isDefaultPrevented()) {
          return evt;
        }

        var modal = openedWindows.top();
        if (modal /*&& modal.value.keyboard*/) {
          switch (evt.which) {
            //case 27: {
            //  evt.preventDefault();
            //  $rootScope.$apply(function() {
            //    $modalStack.dismiss(modal.key, 'escape key press');
            //  });
            //  break;
            //}
            case 9: {
              $modalStack.loadFocusElementList(modal);
              var focusChanged = false;
              if (evt.shiftKey) {
                if ($modalStack.isFocusInFirstItem(evt)) {
                  focusChanged = $modalStack.focusLastFocusableElement();
                }
              } else {
                if ($modalStack.isFocusInLastItem(evt)) {
                  focusChanged = $modalStack.focusFirstFocusableElement();
                }
              }

              if (focusChanged) {
                evt.preventDefault();
                evt.stopPropagation();
              }
              break;
            }
          }
        }
      });

Ps. Sorry for my bad english

**Comment by icfantv** [comment]
@Luukash:  Hi there!  It sounds like you think you've found a bug.  The horror!  If so, please follow  [these instructions](https://github.com/angular-ui/bootstrap/blob/master/CONTRIBUTING.md#you-think-youve-found-a-bug) so we don't lose this since you're commenting on an already closed (and quite old) issue.  Thanks!

Unfortunately, if you think you've found a bug and do not follow the above instructions when opening a new issue, we will close the issue due to lack of activity after a reasonable amount of time.
