### ISSUE TITLE
Custom templates in Typeahead?

### ISSUE THREAD

**Issue by braco** [angular-ui/bootstrap#814]
Am I right in thinking there's no way to override the default template path in Typeahead? If there is a way to do this, docs should be updated.

**Comment by maciej-gurban** [comment]
Perhaps because I'm new to angular-bootstrap, but to me it seems very unintuitive that it isn't enough to just set `typeahead-template-url` to a file path of a template I want to use, but instead I need to use hacky solutions like (http://stackoverflow.com/a/26339919/2066118)[this one] or (this one)[http://stackoverflow.com/a/19720026/2066118]. Wouldn't it be much easier to just load a template from a specified file path specified via the  `typeahead-template-url` attribute?

The solution with <script> tags is also quite unfortunate. Where are we supposed to define these <script> tags, and include them?  All in our central index.html file?
