### ISSUE TITLE
typeahead drop-down li items unreadable under angularjs-1.20rc1

### ISSUE THREAD

**Issue by bkc** [angular-ui/bootstrap#868]
I am developing an application that until today used angularjs 1.1.5 and ui-bootstrap-tpls-0.4.0

The screenshot image typeahead-115.png shows how the drop-down menu looks under 1.1.5

I upgraded to 1.20rc and now the li items are unreadable (shown in typeahead-120rc1.png)

I then upgraded to ui-bootstrap-tpls-0.5.0 but the problem persists

Can anyone else recreate this? 

I am using this code

``` html
                    <input type="text"
                           required="true"
                           class="input-xxlarge"
                           autocomplete="off"
                           ng-model="lineitem.description"
                           ng-change="lineitem_changed(lineitem)"
                           title="Description of commodities"
                           typeahead-min-length="-1"
                           typeahead="item as item.description for item in commodity_list | filter:$viewValue"
```

![typeahead-115](https://f.cloud.github.com/assets/119869/1018485/45c4d488-0c2a-11e3-83ce-05889a48c28f.png)
![typeahead-120rc1](https://f.cloud.github.com/assets/119869/1018486/45d27cfa-0c2a-11e3-9de8-c8b31b3c195a.png)

**Comment by PruthviKumarBK** [comment]
HI @bkc @pderksen @pkozlowski-opensource  @duncanbeevers  @miketierney , I would like to know if this issue is fixed. I am using Angular 1.5.6 and  get the same error as described above. Its pretty frustrating to also have no proper documentation around this :( Please let me know if there is a fix. I cant downgrade my Angular since i need routing and others which arent available in previous versions. 

Thanks in advance,
Pruthvi

**Comment by icfantv** [comment]
@PruthviKumarBK, if this is still an issue for you, please create a new issue making sure you follow the instructions in the issue template.  Thanks.
