### ISSUE TITLE
$modal: Cannot disable backdrop/keyboard after modal has been instantiated

### ISSUE THREAD

**Issue by georgiosd** [angular-ui/bootstrap#967]
In a common modal with a submit action, we need to be able to change whether the modal can be closed by clicking on the backdrop or by hitting ESC.

example case:

- User clicks submit and is waiting for response from server (there is even an activity indicator)
- User hits ESC by mistake or clicks on backdrop because he gets bored, modal goes poof

**Comment by wesleycho** [comment]
I am closing this as I do not think this is an appropriate feature to move into this library. One can always work around this by having a modal controller with a close method that checks a condition before allowing the user to close the modal, which is the appropriate approach.

**Comment by thesaxonedone** [comment]
@wesleycho Can we re-open this?  As it stands, the 'backdrop' and 'keyboard' properties can only be specified when the modal is instantiated and @georgiosd use-case is reasonable and probably frequently utilized (disable escaping the modal via esc key or clicking outside the modal while data retrieval is in process).    

Hitting escape on your keyboard or clicking outside the modal do not invoke (at least natively) any controller function and instead make calls to $dismiss and $close in the modalStack object, so your solution to have a "controller with a close method that checks a condition before allowing the user to close the modal" doesn't seem applicable.   

As it stands the only solution that works is the decorator solution @lucassus provided, and I think its a reasonable request to be able to modify these properties within the modal itself, rather than only at insantiation time.

**Comment by abdullahmaswadeh** [comment]
` $('#myModal').data('bs.modal')._isShown = false;`
Just worked perfect for me on Bootstrap 4.1
