### ISSUE TITLE
$modal breaks forms b/c of transclusion

### ISSUE THREAD

**Issue by boneskull** [angular-ui/bootstrap#969]
Say I instantiate a modal:

``` javascript
$modal.open({
  controller: 'MyCtrl'
});
```

In my modal, I have a form:

``` html
<form name="myForm">...</form>
```

Because of transclusion, `myForm` is not available on `MyCtrl`'s scope and I can't check for `$valid`, for example.  A workaround I've found is to simply put an `ng-controller="MyCtrl"` within my modal template itself, and do this:

``` javascript
$modal.open({
  controller: function($scope, $modalInstance) {
    $scope.$modalInstance = $modalInstance;
  }
});
```

...and now I can get to the instance from within `MyCtrl`.  

This is not ideal, but I'm not sure of what the fix should be.  Instead of transclusion, would it be a good idea to actually insert an `ngController` directive within the `template/modal/window.html` template itself then say, `ngTransclude` within a child tag?  Any better way to tackle this problem?

thanks
Chris

**Comment by devendher** [comment]
check it this plunker 
might be it will helpful and i think it is complete solution that really what do you want http://plnkr.co/edit/ZM3UUt16P3cRainp0LK3?p=preview

**Comment by solerman** [comment]
I was fighting over ng-model/ng-form myself this days. My problem was a bit different but also cased by the way scopes/controllers are handled. Basically I have a directive to watch from the parent form for changes and warn the user if he's about to leave the page without saving and that wasnt working if you only changed the modal's values. The workaround:

In the parent controller inject your form

```javascript
   modalInstance = $modal.open({
        resolve: {
          containerForm: function () {
            return $scope.containerForm;
          }
        }
      });
```
And in the modal's template set the parent form before any control has the chance to initialize

```html
    <ng-form name="$parent.modalForm">
        <any ng-init="$parent.modalForm.$$parentForm = containerForm"/>
```

**Comment by icfantv** [comment]
@solerman, I should point out that using `ng-init` outside the very limited, documented areas is not correct.

Also, doing this with your form is not correct.  You should be returning the model from the form in the modal as a result of the $promise from the modal and then, if needed, update your form's model with that data.

**Comment by solerman** [comment]
The problem is, with bindings the model is already updated in the model. To do what you say I would need to clone the (very complex) model, provide it to the modal and then hand-copy all the values back. For every modal.

**Comment by icfantv** [comment]
@solerman, that sounds like an issue with design and UX rather than our library.  do you need to send the entire model to the modal or can you just send the bit that the model intends to edit?

For the record, this is a very common paradigm - say, having a grid of data and then editing a grid item in a modal.

**Comment by solerman** [comment]
@icfantv the parent its a dashboard and the modal its just for a single dashboard item. There is a lot of stuff to configure in the item, I ain't sending the entire dashboard but just a single item. Think a bar chart, all the series, axis titles, colors, ranges, etc.

**Comment by icfantv** [comment]
@solerman, without knowing exactly what you're using the modal to configure, it's hard to make a recommendation.  It *sounds* like you're using the modal to configure chart options, but that's just a guess.

I can certainly appreciate not wanting to copy a "huge" model object.  The only other options I can think of are:

1.  Don't copy the model, rather, send it live and use a `cancel` to restore the model, or
2.  Don't use a modal.  Rather, use a physically separate details page.  This would depend on the amount of data that needs to be edited.

I still think this boils down to a design and UX issue and not the library.  We do get a lot of issues surrounding the use of parent forms wrapping "compartmentalized" forms (tabs, accordions, etc...).  There are ways of working around our `replace: true` directives, including an example in our tabs demo - but in general, I'd argue that doing this is a somewhat bad approach.  Part of that is due to how angular form validation was architected for 1.x.  I don't know if or how this changes for ng2.
